import fs from 'node:fs';
import path from 'node:path';
import {performance} from 'node:perf_hooks';

const base=process.env.SMOKE_BASE_URL||'http://127.0.0.1:5181';
const root=path.resolve(import.meta.dirname,'..');
const schema=JSON.parse(fs.readFileSync(path.resolve(root,'../../tests/bootstrap/fixtures/sales-v1/schema.json'),'utf8'));
const request=JSON.parse(fs.readFileSync(path.resolve(root,'../../tests/bootstrap/fixtures/sales-v1/request.json'),'utf8'));
const definitions={
  interpretation:{type:'object',additionalProperties:false,required:['request_kind','objective','kpis','dimensions','filters','pages','assumptions','clarifications'],properties:{request_kind:{type:'string',enum:['POWER_BI_REPORT']},objective:{type:'string'},kpis:{type:'array',items:{type:'string'}},dimensions:{type:'array',items:{type:'string'}},filters:{type:'array',items:{type:'string'}},pages:{type:'array',items:{type:'string'}},assumptions:{type:'array',items:{type:'string'}},clarifications:{type:'array',items:{type:'object',additionalProperties:false,required:['id','category','question','reason','required'],properties:{id:{type:'string'},category:{type:'string',enum:['METRIC_DEFINITION','TIME_COMPARISON','SECURITY','AUDIENCE','PAGE_SCOPE','FILTER_SCOPE','OTHER']},question:{type:'string'},reason:{type:'string'},required:{type:'boolean'}}}}}},
  design:{type:'object',additionalProperties:false,required:['artifact_kind','schema_version','objective','semantic_model','pages','applied_standards','assumptions','limitations'],properties:{artifact_kind:{type:'string',enum:['AIDesignPlan']},schema_version:{type:'integer',enum:[1]},objective:{type:'string'},semantic_model:{type:'object',additionalProperties:false,required:['grain','date_table','relationships','measures'],properties:{grain:{type:'string'},date_table:{type:'string'},relationships:{type:'array',items:{type:'string'}},measures:{type:'array',items:{type:'object',additionalProperties:false,required:['name','business_definition','formula_guidance'],properties:{name:{type:'string'},business_definition:{type:'string'},formula_guidance:{type:'string'}}}}}},pages:{type:'array',items:{type:'object',additionalProperties:false,required:['name','purpose','visuals','slicers'],properties:{name:{type:'string'},purpose:{type:'string'},visuals:{type:'array',items:{type:'object',additionalProperties:false,required:['type','title','fields'],properties:{type:{type:'string'},title:{type:'string'},fields:{type:'array',items:{type:'string'}}}}},slicers:{type:'array',items:{type:'string'}}}}},applied_standards:{type:'array',items:{type:'object',additionalProperties:false,required:['citation','application'],properties:{citation:{type:'string'},application:{type:'string'}}}},assumptions:{type:'array',items:{type:'string'}},limitations:{type:'array',items:{type:'string'}}}},
};
async function post(url,body){const start=performance.now();const response=await fetch(base+url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const latencyMs=Math.round(performance.now()-start);const data=await response.json();if(!response.ok)throw new Error(`${url} failed: ${data?.error?.code||response.status}`);return {data,latencyMs}}
async function chat(name,schema,messages){const {data,latencyMs}=await post('/api/ai/chat',{messages,response_format:{type:'json_schema',json_schema:{name,strict:true,schema}}});return {value:JSON.parse(data.choices[0].message.content),metrics:{model:data.model,latencyMs,...data.usage}}}
const status=await (await fetch(base+'/api/ai/status')).json();if(!status.configured)throw new Error('Foundry adapter is not configured');
const interpretation=await chat('power_bi_requirement_interpretation',definitions.interpretation,[{role:'system',content:'You are a Power BI solution architect. Interpret the supplied request against the supplied synthetic schema. Ask at most five concise targeted questions for material ambiguities and combine related metric questions when practical. A requested metric is materially ambiguous when the schema offers multiple monetary or count interpretations; ask which field and aggregation defines it. For year-over-year or other time comparisons, clarify coverage, grain, and missing-prior-period behaviour when unspecified and classify that question as TIME_COMPARISON. If users must filter by a security-sensitive organisational dimension such as Region or Business Area and the request does not state whether this is only a slicer or access control, ask a SECURITY clarification. Derive every question from the actual input and schema; do not assume fixture answers and do not invent schema fields.'},{role:'user',content:JSON.stringify({request:request.original_text,schema})}]);
function answer(q){const text=q.question.toLowerCase();if(q.category==='TIME_COMPARISON'||/(year.over.year|yoy|prior.year|prior period|time grain)/.test(text))return request.clarifications[1].golden_answer;if(q.category==='SECURITY'||/(row.level security|\brls\b|access control)/.test(text))return request.clarifications[2].golden_answer;if(/average order value/.test(text))return 'Average Order Value is Total Sales divided by distinct Total Orders.';if(/total orders|unique order|distinct.*order/.test(text))return 'Count distinct FactSales[OrderId]; an order may contain multiple sales lines.';if(q.category==='METRIC_DEFINITION'&&/(sales|revenue|gross|net|salesamount)/.test(text))return request.clarifications[0].golden_answer;if(q.category==='PAGE_SCOPE')return 'Use an Executive Summary and Regional Performance view.';if(q.category==='AUDIENCE')return 'Executive leaders are the primary audience.';if(q.category==='FILTER_SCOPE')return 'Use region, business area and product category slicers.';return 'Apply the governed local standards and record unsupported information.'}
const answers=Object.fromEntries(interpretation.value.clarifications.map(q=>[q.id,answer(q)]));
const snapshot={artifact_kind:'AIRequirementsSnapshot',version:1,processing:'AZURE_OPENAI_GPT_4_1',original_request:request.original_text,schema_id:schema.schema_id,interpretation:interpretation.value,clarification_answers:answers,confirmation:'EXPLICIT_LOCAL_USER_CONFIRMATION'};
const files=[['corporate-branding.md','CB'],['powerbi-modelling-standards.md','PM'],['report-design-standards.md','RD'],['accessibility-standards.md','AC'],['deployment-standards.md','DP']];
const chunks=files.flatMap(([source,prefix])=>fs.readFileSync(path.join(root,'knowledge',source),'utf8').split(/^##\s+/m).slice(1).map((section,index)=>{const [heading,...body]=section.trim().split(/\r?\n/);const text=`${heading}\n${body.join('\n').trim()}`;const chunkId=`${prefix}-${String(index+1).padStart(3,'0')}`;return {source,version:'1.0.0',chunkId,text,citation:`local-knowledge:${source}@1.0.0#${chunkId}`}}));
const indexed=await post('/api/ai/embeddings',{input:chunks.map(c=>c.text)});const vectors=indexed.data.data.map(x=>x.embedding);
const evaluation=[['What colours and theme should the corporate report use?','corporate-branding.md'],['Which executive sales KPIs are required?','powerbi-modelling-standards.md'],['How should year-over-year date modelling work?','powerbi-modelling-standards.md'],['What accessibility and readability rules apply?','accessibility-standards.md'],['Which chart types should be used for comparisons?','report-design-standards.md'],['Does a Region slicer provide row-level security?','powerbi-modelling-standards.md'],['What must deployment handover evidence contain?','deployment-standards.md']];
const query=[request.original_text,interpretation.value.objective,...interpretation.value.kpis,...interpretation.value.dimensions,...Object.values(answers)].join('\n');const queried=await post('/api/ai/embeddings',{input:[query,...evaluation.map(x=>x[0])]});const queryVectors=queried.data.data.map(x=>x.embedding);
function cosine(a,b){let dot=0,aa=0,bb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i]}return dot/(Math.sqrt(aa)*Math.sqrt(bb)||1)}
function top(vector,k=3){return chunks.map((chunk,i)=>({...chunk,score:cosine(vectors[i],vector)})).sort((a,b)=>b.score-a.score).slice(0,k)}
const retrieved=top(queryVectors[0],4);const evalResults=evaluation.map(([question,expectedSource],i)=>{const hits=top(queryVectors[i+1]);return {question,expectedSource,hit:hits.some(x=>x.source===expectedSource),retrieved:hits.map(x=>x.citation)}});const design=await chat('grounded_power_bi_design_plan',definitions.design,[{role:'system',content:'Produce the required structured Power BI design using the confirmed requirements, schema, and retrieved customer standards. Use only supplied citations for customer policy, distinguish requirements from recommendations, never invent customer policy, and put unknown items in limitations.'},{role:'user',content:JSON.stringify({confirmedRequirements:snapshot,schema,retrievedStandards:retrieved.map(c=>({citation:c.citation,text:c.text}))})}]);
const allowed=new Set(retrieved.map(c=>c.citation));if(design.value.artifact_kind!=='AIDesignPlan'||!design.value.applied_standards.length||design.value.applied_standards.some(x=>!allowed.has(x.citation)))throw new Error('Grounded plan citation validation failed');
const evidence={executedAt:new Date().toISOString(),status:'PASS',configuration:status,interpretation:{metrics:interpretation.metrics,objective:interpretation.value.objective,clarifications:interpretation.value.clarifications},rag:{embeddingModel:indexed.data.model,chunksIndexed:chunks.length,topK:4,indexLatencyMs:indexed.latencyMs,queryAndEvaluationLatencyMs:queried.latencyMs,indexUsage:indexed.data.usage,queryUsage:queried.data.usage,retrieved:retrieved.map(x=>({citation:x.citation,score:x.score}))},evaluation:{k:3,hits:evalResults.filter(x=>x.hit).length,total:evalResults.length,hitRate:evalResults.filter(x=>x.hit).length/evalResults.length,results:evalResults},design:{metrics:design.metrics,objective:design.value.objective,appliedStandards:design.value.applied_standards},totals:{llmCalls:2,embeddingCalls:2,latencyMs:interpretation.metrics.latencyMs+indexed.latencyMs+queried.latencyMs+design.metrics.latencyMs,tokens:(interpretation.metrics.total_tokens||0)+(indexed.data.usage?.total_tokens||0)+(queried.data.usage?.total_tokens||0)+(design.metrics.total_tokens||0)}};
const out=path.resolve(root,'../../artifacts/local/foundry-smoke.json');fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({...evidence,artifact:out},null,2));
