import {describe,expect,it} from 'vitest';
import {applyClarificationAnalysis,beginClarificationAnalysis,confirmClarificationUnderstanding,correctClarificationUnderstanding,createClarificationSession,reopenClarificationForDesignConflict,submitClarificationAnswers,validateClarificationSession,type ClarificationSession,type IterativeClarificationQuestion,type MaterialConfirmationSummary} from './clarification';
import type {ConfirmedRequirementInterpretation} from './foundry';

const interpretation=(objective='Understand performance'):ConfirmedRequirementInterpretation=>({request_kind:'POWER_BI_REPORT',objective,businessQuestions:[],kpis:[],dimensions:[],filters:[],audience:'Business leaders',pages:[],assumptions:[],ambiguities:[],clarifications:[],coverageRequirements:[],businessQuestionCoverage:[]});
const summary=(objective='Understand performance'):MaterialConfirmationSummary=>({objective,businessQuestions:[],kpiDefinitions:[],scopeAndTime:[],dimensionsAndFilters:[],lifecycleDefinitions:[],materialPolicyDecisions:[]});
const question=(id='meaning'):IterativeClarificationQuestion=>({id,category:'METRIC_DEFINITION',question:'What does performance mean for this decision?',reason:'The requested outcome depends on the business definition.',required:true,suggestions:[{id:'outcome-a',label:'Use the primary business outcome'}],allowFreeText:true});
const create=(request='Build a performance dashboard',maxRounds=3)=>beginClarificationAnalysis(createClarificationSession({sessionId:'session-1',mode:'BUSINESS',originalRequest:request,limits:{maxRounds,maxQuestionsPerRound:3,maxAnswerCharacters:200}}));
const confirm=(session:ClarificationSession,confirmedAt:string)=>confirmClarificationUnderstanding(session,{confirmedAt,readinessBinding:session.readinessBinding??'',contextBinding:session.contextBinding??''});
const analyse=(session:ClarificationSession,state:'NEEDS_CLARIFICATION'|'READY_FOR_CONFIRMATION',questions:IterativeClarificationQuestion[],unresolved:string[])=>(applyClarificationAnalysis(session,{state,interpretation:interpretation(),questions,unresolvedAmbiguities:unresolved,confirmationSummary:summary(),conflictReasons:[],analysedAt:'2026-09-21T00:00:00Z'}));

describe('AI-native clarification state authority',()=>{
  it('defaults the governed fixture to Business Mode and preserves the original request',()=>{const session=create();expect(session).toMatchObject({mode:'BUSINESS',state:'ANALYSING',originalRequest:'Build a performance dashboard',rounds:[]})});

  it('preserves raw natural-language answers and every AI interpretation while permitting an adaptive follow-up round',()=>{let session=analyse(create(),'NEEDS_CLARIFICATION',[question()],['Performance is materially ambiguous.']);session=submitClarificationAnswers(session,{answers:[{questionId:'meaning',rawAnswer:'  Revenue and margin by region.  '}],answeredAt:'2026-09-21T00:01:00Z'});expect(session.rounds[0].answers[0]).toMatchObject({rawAnswer:'  Revenue and margin by region.  ',suggestionId:''});const followUp=question('margin-definition');followUp.question='Should margin mean an amount or a percentage?';session=applyClarificationAnalysis(session,{state:'NEEDS_CLARIFICATION',interpretation:interpretation('Compare revenue and margin'),questions:[followUp],unresolvedAmbiguities:['Margin meaning remains unresolved.'],confirmationSummary:summary('Compare revenue and margin'),conflictReasons:[],analysedAt:'2026-09-21T00:02:00Z'});expect(session).toMatchObject({state:'NEEDS_CLARIFICATION',rounds:[{round:1},{round:2,questions:[{id:'margin-definition'}]}],analyses:[{interpretation:{objective:'Understand performance'}},{interpretation:{objective:'Compare revenue and margin'}}]})});

  it('requires explicit human confirmation and sends corrections back to AI analysis',()=>{let session=applyClarificationAnalysis(create(),{state:'READY_FOR_CONFIRMATION',interpretation:interpretation(),questions:[],unresolvedAmbiguities:[],confirmationSummary:summary(),conflictReasons:[],analysedAt:'2026-09-21T00:00:00Z'});const corrected=correctClarificationUnderstanding(session,'Margin must be percentage, not amount.','2026-09-21T00:01:00Z');expect(corrected).toMatchObject({state:'ANALYSING',corrections:[{rawCorrection:'Margin must be percentage, not amount.'}]});session=confirm(session,'2026-09-21T00:02:00Z');expect(session).toMatchObject({state:'CONFIRMED',confirmedAt:'2026-09-21T00:02:00Z'})});

  it('rejects stale visible meaning or changed material input context at confirmation',()=>{const ready=applyClarificationAnalysis(create(),{state:'READY_FOR_CONFIRMATION',interpretation:interpretation(),questions:[],unresolvedAmbiguities:[],confirmationSummary:summary(),conflictReasons:[],analysedAt:'2026-09-21T00:00:00Z'}),tampered={...ready,currentInterpretation:{...ready.currentInterpretation!,objective:'Unseen changed meaning'}};expect(()=>confirm(tampered,'2026-09-21T00:01:00Z')).toThrow('exact complete visible understanding');expect(()=>confirmClarificationUnderstanding(ready,{confirmedAt:'2026-09-21T00:01:00Z',readinessBinding:ready.readinessBinding!,contextBinding:'different input context'})).toThrow('exact complete visible understanding')});

  it('keeps legacy version-one confirmed transcripts valid while new sessions require exact bindings',()=>{const ready=applyClarificationAnalysis(create(),{state:'READY_FOR_CONFIRMATION',interpretation:interpretation(),questions:[],unresolvedAmbiguities:[],confirmationSummary:summary(),conflictReasons:[],analysedAt:'2026-09-21T00:00:00Z'}),confirmed=confirm(ready,'2026-09-21T00:01:00Z'),legacy={...confirmed,schemaVersion:1 as const};delete legacy.contextBinding;delete legacy.readinessBinding;expect(validateClarificationSession(legacy,true).state).toBe('CONFIRMED');expect(validateClarificationSession(confirmed,true).schemaVersion).toBe(2)});

  it('reopens a confirmed material design conflict for AI reasoning and fresh human confirmation',()=>{let session=applyClarificationAnalysis(create(),{state:'READY_FOR_CONFIRMATION',interpretation:interpretation(),questions:[],unresolvedAmbiguities:[],confirmationSummary:summary(),conflictReasons:[],analysedAt:'2026-09-21T00:00:00Z'});session=confirm(session,'2026-09-21T00:01:00Z');session=reopenClarificationForDesignConflict(session,['Confirmed scope exceeds supported readable layout.'],'2026-09-21T00:02:00Z');expect(session).toMatchObject({state:'ANALYSING',confirmedAt:'',designConflicts:[{reason:'Confirmed scope exceeds supported readable layout.'}]});expect(()=>confirm(session,'2026-09-21T00:03:00Z')).toThrow('exact complete visible understanding')});

  it('shares the configured clarification-cycle budget across confirmation corrections and fails closed with raw provenance',()=>{let session=applyClarificationAnalysis(create('Build a report',1),{state:'READY_FOR_CONFIRMATION',interpretation:interpretation(),questions:[],unresolvedAmbiguities:[],confirmationSummary:summary(),conflictReasons:[],analysedAt:'2026-09-21T00:00:00Z'});session=correctClarificationUnderstanding(session,'Use fiscal months.','2026-09-21T00:01:00Z');session=applyClarificationAnalysis(session,{state:'READY_FOR_CONFIRMATION',interpretation:interpretation(),questions:[],unresolvedAmbiguities:[],confirmationSummary:summary(),conflictReasons:[],analysedAt:'2026-09-21T00:02:00Z'});session=correctClarificationUnderstanding(session,'Also exclude internal activity.','2026-09-21T00:03:00Z');expect(session).toMatchObject({state:'HUMAN_REVIEW_REQUIRED',corrections:[{rawCorrection:'Use fiscal months.'},{rawCorrection:'Also exclude internal activity.'}]});expect(session.conflictReasons.at(-1)).toContain('round limit exhausted');expect(validateClarificationSession(session).state).toBe('HUMAN_REVIEW_REQUIRED')});

  it('bounds repeated design-conflict re-entry and preserves the conflict that triggered human review',()=>{let session=applyClarificationAnalysis(create('Build a report',1),{state:'READY_FOR_CONFIRMATION',interpretation:interpretation(),questions:[],unresolvedAmbiguities:[],confirmationSummary:summary(),conflictReasons:[],analysedAt:'2026-09-21T00:00:00Z'});session=confirm(session,'2026-09-21T00:01:00Z');session=reopenClarificationForDesignConflict(session,['Confirmed scope exceeds supported readable layout.'],'2026-09-21T00:02:00Z');session=applyClarificationAnalysis(session,{state:'READY_FOR_CONFIRMATION',interpretation:interpretation(),questions:[],unresolvedAmbiguities:[],confirmationSummary:summary(),conflictReasons:[],analysedAt:'2026-09-21T00:03:00Z'});session=confirm(session,'2026-09-21T00:04:00Z');session=reopenClarificationForDesignConflict(session,['The reconfirmed scope still exceeds supported layout.'],'2026-09-21T00:05:00Z');expect(session).toMatchObject({state:'HUMAN_REVIEW_REQUIRED',confirmedAt:'',designConflicts:[{reason:'Confirmed scope exceeds supported readable layout.'},{reason:'The reconfirmed scope still exceeds supported layout.'}]});expect(session.conflictReasons.at(-1)).toContain('round limit exhausted');expect(validateClarificationSession(session).state).toBe('HUMAN_REVIEW_REQUIRED')});

  it('rejects readiness while the structured interpretation still contains ambiguity',()=>{expect(()=>applyClarificationAnalysis(create(),{state:'READY_FOR_CONFIRMATION',interpretation:{...interpretation(),ambiguities:['Reporting period is unresolved.']},questions:[],unresolvedAmbiguities:[],confirmationSummary:summary(),conflictReasons:[],analysedAt:'2026-09-21T00:00:00Z'})).toThrow('no unresolved material ambiguity')});

  it('fails closed to human review when the configured round limit is exhausted',()=>{let session=analyse(create('Build a report',1),'NEEDS_CLARIFICATION',[question()],['Meaning unresolved.']);session=submitClarificationAnswers(session,{answers:[{questionId:'meaning',rawAnswer:'It means the main outcome.'}],answeredAt:'2026-09-21T00:01:00Z'});session=applyClarificationAnalysis(session,{state:'NEEDS_CLARIFICATION',interpretation:interpretation(),questions:[question('follow-up')],unresolvedAmbiguities:['A material ambiguity remains.'],confirmationSummary:summary(),conflictReasons:[],analysedAt:'2026-09-21T00:02:00Z'});expect(session.state).toBe('HUMAN_REVIEW_REQUIRED');expect(session.conflictReasons.at(-1)).toContain('round limit exhausted');expect(validateClarificationSession(session).state).toBe('HUMAN_REVIEW_REQUIRED')});

  it('rejects missing, oversized, duplicate, and unsupported answers without interpreting prose',()=>{const pending=analyse(create(),'NEEDS_CLARIFICATION',[question()],['Meaning unresolved.']);expect(()=>submitClarificationAnswers(pending,{answers:[],answeredAt:'now'})).toThrow("has no answer");expect(()=>submitClarificationAnswers(pending,{answers:[{questionId:'meaning',rawAnswer:'x'.repeat(201)}],answeredAt:'now'})).toThrow('length limit');expect(()=>submitClarificationAnswers(pending,{answers:[{questionId:'meaning',rawAnswer:'A',suggestionId:'invented'}],answeredAt:'now'})).toThrow('unknown suggestion');expect(pending.rounds[0].answers).toEqual([])});

  it.each([
    'Monitor service operations and response outcomes',
    'Analyse sales performance and commercial outcomes',
    'Evaluate marketing effectiveness and campaign outcomes',
    'Understand customer retention and relationship outcomes',
  ])('uses the same state path for an unrelated synthetic domain: %s',request=>{let session=analyse(create(request),'NEEDS_CLARIFICATION',[question()],['A material definition is unresolved.']);session=submitClarificationAnswers(session,{answers:[{questionId:'meaning',rawAnswer:'Use the organisation-approved business definition.'}],answeredAt:'now'});expect(session.state).toBe('ANALYSING');expect(session.originalRequest).toBe(request)});
});
