import {expect,it} from 'vitest';
import {materializeConfirmedRequirements,materializeIterativeConfirmedRequirements,validateConfirmedRequirementContract,type ConfirmedRequirementContract,type ConfirmedRequirementObligation} from './confirmedRequirements';
import {applyClarificationAnalysis,beginClarificationAnalysis,confirmClarificationUnderstanding,createClarificationSession,submitClarificationAnswers} from './clarification';
import type {ConfirmedRequirementInterpretation,RequirementCoverageContract,RequirementMeasureSemantic} from './foundry';

const schema={tables:[{name:'Cases',columns:[{name:'Id',type:'text'},{name:'Status',type:'text'},{name:'CreatedAt',type:'date'}]}]};
const count:RequirementMeasureSemantic={id:'case-count',name:'Case Count',businessDefinition:'Count of cases',aggregation:'COUNT',field:'Cases.Id',numeratorMeasureId:'',denominatorMeasureId:'',format:'integer',filterField:'',filterValue:'',contextField:''};
const open:RequirementMeasureSemantic={id:'open-cases',name:'Open Cases',businessDefinition:'Count of cases in the confirmed open lifecycle',aggregation:'FILTERED_COUNT',field:'Cases.Id',numeratorMeasureId:'',denominatorMeasureId:'',format:'integer',filterField:'Cases.Status',filterValue:'Open',contextField:''};
const obligation=(value:Partial<RequirementCoverageContract>&Pick<RequirementCoverageContract,'id'|'kind'|'measureNames'|'fields'>):RequirementCoverageContract=>({pageNames:['Overview'],required:true,minimumRepresentations:1,measures:[],timeGrain:'NONE',lifecycleValues:[],...value});
const monthly=obligation({id:'monthly-trend',kind:'TREND',measureNames:['Case Count'],fields:['Cases.CreatedAt'],measures:[count],timeGrain:'MONTH'});
const quarterly={...monthly,timeGrain:'QUARTER' as const};
const interpretation=():ConfirmedRequirementInterpretation=>({request_kind:'POWER_BI_REPORT',objective:'Monitor case volume and lifecycle',businessQuestions:['How many cases arrive over time?','Which cases are open?'],kpis:['Case Count'],dimensions:['CreatedAt','Status'],filters:['Cases.Status'],audience:'Operations leaders',pages:['Overview'],assumptions:[],ambiguities:['Requested trend grain'],clarifications:[{id:'trend-grain',category:'TIME_COMPARISON',question:'Which reporting grain is required?',reason:'The trend grain changes the confirmed time obligation.',required:true,coverageRequirementIds:['monthly-trend'],selection:'SINGLE',options:[{id:'monthly',label:'Monthly',coverageOverrides:[monthly],pageScope:[],audience:''},{id:'quarterly',label:'Quarterly',coverageOverrides:[quarterly],pageScope:[],audience:''}]}],coverageRequirements:[obligation({id:'case-count-kpi',kind:'KPI',measureNames:['Case Count'],fields:[],measures:[count]}),obligation({id:'status-filter',kind:'FILTER',measureNames:[],fields:['Cases.Status']}),monthly,obligation({id:'open-lifecycle',kind:'LIFECYCLE',measureNames:['Open Cases'],fields:['Cases.Status'],measures:[open],lifecycleValues:['Open']})],businessQuestionCoverage:[{question:'How many cases arrive over time?',coverageRequirementIds:['case-count-kpi','monthly-trend']},{question:'Which cases are open?',coverageRequirementIds:['open-lifecycle','status-filter']}]});
const build=(selections:Record<string,string>={'trend-grain':'monthly'})=>materializeConfirmedRequirements({requirement:'Show monthly case volume, status filters, and the open lifecycle.',dataStructure:schema,interpretation:interpretation(),selections,confirmedAt:'2026-09-21T00:00:00Z'});

it('deterministically materializes a selected typed option and preserves separate provenance',()=>{const contract=build();expect(contract).toMatchObject({artifact_kind:'ConfirmedRequirementContract',schema_version:1,objective:'Monitor case volume and lifecycle',pages:[{name:'Overview',required:true}],dimensions:['Cases.CreatedAt','Cases.Status'],provenance:{requirement:'Show monthly case volume, status filters, and the open lifecycle.',selections:[{clarificationId:'trend-grain',optionId:'monthly',optionLabel:'Monthly'}]}});expect(contract.obligations.find(item=>item.id==='monthly-trend')).toMatchObject({timeGrain:'MONTH',required:true,minimumRepresentations:1});expect(contract.provenance.questions[0].question).toContain('reporting grain');expect(validateConfirmedRequirementContract(contract,schema)).toEqual(contract)});

it('fails closed for missing or unknown selections without parsing free text',()=>{expect(()=>build({})).toThrow("Required clarification 'trend-grain' has no typed selection");expect(()=>build({'trend-grain':'Use the last 30 days'})).toThrow("selected an unknown option")});

it('fails closed for schema drift, altered selections, obligation tampering, unsupported cardinality, and duplicate measure names',()=>{const contract=build(),duplicateName={...count,id:'second-count'},duplicateObligation=obligation({id:'duplicate-name',kind:'BREAKDOWN',measureNames:['Case Count'],fields:['Cases.Status'],measures:[duplicateName]}) as ConfirmedRequirementObligation;const cases:ConfirmedRequirementContract[]=[{...contract,dimensions:['Cases.Missing']},{...contract,provenance:{...contract.provenance,selections:[{...contract.provenance.selections[0],optionLabel:'Altered'}]}},{...contract,obligations:contract.obligations.map(item=>item.id==='monthly-trend'?{...item,timeGrain:'YEAR' as const}:item)},{...contract,obligations:contract.obligations.map(item=>item.id==='case-count-kpi'?{...item,minimumRepresentations:0}:item)},{...contract,obligations:[...contract.obligations,duplicateObligation]}];for(const candidate of cases)expect(()=>validateConfirmedRequirementContract(candidate,schema)).toThrow('CONFIRMED_REQUIREMENT_CONTRACT_INVALID')});

it('rejects contradictory clarification effects targeting the same obligation',()=>{const value=interpretation();value.clarifications.push({...value.clarifications[0],id:'second-grain',question:'Confirm the same grain again'});expect(()=>materializeConfirmedRequirements({requirement:'Cases',dataStructure:schema,interpretation:value,selections:{'trend-grain':'monthly','second-grain':'quarterly'},confirmedAt:'2026-09-21T00:00:00Z'})).toThrow('contradictory typed effects')});

it('materializes page scope and obligation placement from one typed selection',()=>{const value=interpretation();value.pages=['Overview','Detail'];const ids=value.coverageRequirements.map(item=>item.id),onPage=(page:string)=>value.coverageRequirements.map(item=>({...item,pageNames:[page]}));value.clarifications=[{id:'page-scope',category:'PAGE_SCOPE',question:'Which page is required?',reason:'Confirms the required report scope.',required:true,coverageRequirementIds:ids,selection:'SINGLE',options:[{id:'overview',label:'Overview',coverageOverrides:onPage('Overview'),pageScope:['Overview'],audience:''},{id:'detail',label:'Detail',coverageOverrides:onPage('Detail'),pageScope:['Detail'],audience:''}]}];const contract=materializeConfirmedRequirements({requirement:'Cases',dataStructure:schema,interpretation:value,selections:{'page-scope':'detail'},confirmedAt:'2026-09-21T00:00:00Z'});expect(contract.pages).toEqual([{name:'Detail',required:true}]);expect(contract.obligations.every(item=>item.pageNames[0]==='Detail')).toBe(true)});

it('retains optional presentation as an explicit zero-minimum obligation',()=>{const value=interpretation(),optional=obligation({id:'optional-status-breakdown',kind:'BREAKDOWN',measureNames:['Case Count'],fields:['Cases.Status'],measures:[count],required:false,minimumRepresentations:0});value.coverageRequirements.push(optional);const contract=materializeConfirmedRequirements({requirement:'Cases',dataStructure:schema,interpretation:value,selections:{'trend-grain':'monthly'},confirmedAt:'2026-09-21T00:00:00Z'});expect(contract.obligations.at(-1)).toMatchObject({id:'optional-status-breakdown',required:false,minimumRepresentations:0})});

it('keeps interpretation and confirmation cardinalities aligned for grouped KPI and filter obligations',()=>{const contract=build(),kpi=contract.obligations.find(item=>item.id==='case-count-kpi')!,filter=contract.obligations.find(item=>item.id==='status-filter')!,provenanceKpi=contract.provenance.interpretation.coverageRequirements.find(item=>item.id==='case-count-kpi')!,provenanceFilter=contract.provenance.interpretation.coverageRequirements.find(item=>item.id==='status-filter')!;kpi.measureNames=['Case Count','Open Cases'];kpi.measures=[count,open];provenanceKpi.measureNames=[...kpi.measureNames];provenanceKpi.measures=[count,open];filter.fields=['Cases.Status','Cases.CreatedAt'];provenanceFilter.fields=[...filter.fields];expect(validateConfirmedRequirementContract(contract,schema)).toEqual(contract)});

it('rejects unsupported measure enums and cyclic derived operands before RAG',()=>{const unsupported=build(),unsupportedKpi=unsupported.obligations.find(item=>item.id==='case-count-kpi')!,unsupportedReplay=unsupported.provenance.interpretation.coverageRequirements.find(item=>item.id==='case-count-kpi')!,malformed={...count,id:'unsupported',name:'Unsupported',aggregation:'MEDIAN' as any,format:'scientific' as any};unsupportedKpi.measureNames=['Unsupported'];unsupportedKpi.measures=[malformed];unsupportedReplay.measureNames=['Unsupported'];unsupportedReplay.measures=[malformed];unsupported.provenance.interpretation.kpis=['Unsupported'];expect(()=>validateConfirmedRequirementContract(unsupported,schema)).toThrow('unsupported aggregation or format');const cyclic=build(),cyclicKpi=cyclic.obligations.find(item=>item.id==='case-count-kpi')!,cyclicReplay=cyclic.provenance.interpretation.coverageRequirements.find(item=>item.id==='case-count-kpi')!,a:RequirementMeasureSemantic={...count,id:'a',name:'A',aggregation:'RATIO',field:'',numeratorMeasureId:'b',denominatorMeasureId:'b',format:'percentage'},b:RequirementMeasureSemantic={...count,id:'b',name:'B',aggregation:'RATIO',field:'',numeratorMeasureId:'a',denominatorMeasureId:'a',format:'percentage'};cyclicKpi.measureNames=['A'];cyclicKpi.measures=[a,b];cyclicReplay.measureNames=['A'];cyclicReplay.measures=[a,b];cyclic.provenance.interpretation.kpis=['A'];expect(()=>validateConfirmedRequirementContract(cyclic,schema)).toThrow('dependency graph contains a cycle')});

function iterativeSession(){const final={...interpretation(),ambiguities:[],clarifications:[]};let session=beginClarificationAnalysis(createClarificationSession({sessionId:'iterative-1',mode:'BUSINESS',originalRequest:'Show case volume with the organisation-approved reporting grain.',limits:{maxRounds:3,maxQuestionsPerRound:3,maxAnswerCharacters:500}}));session=applyClarificationAnalysis(session,{state:'NEEDS_CLARIFICATION',interpretation:{...final,coverageRequirements:final.coverageRequirements.map(item=>item.id==='monthly-trend'?quarterly:item)},questions:[{id:'reporting-grain',category:'TIME_COMPARISON',question:'Which reporting period should the trend use?',reason:'The business reporting period is material.',required:true,suggestions:[{id:'monthly',label:'Monthly'}],allowFreeText:true}],unresolvedAmbiguities:['Reporting grain is unresolved.'],confirmationSummary:{objective:final.objective,businessQuestions:final.businessQuestions,kpiDefinitions:['Case Count means a count of Cases.Id.'],scopeAndTime:[],dimensionsAndFilters:['Status remains an available filter.'],lifecycleDefinitions:['Open means status Open.'],materialPolicyDecisions:[]},conflictReasons:[],analysedAt:'2026-09-21T01:00:00Z'});session=submitClarificationAnswers(session,{answers:[{questionId:'reporting-grain',rawAnswer:'Use the standard monthly management reporting period.',suggestionId:'monthly'}],answeredAt:'2026-09-21T01:01:00Z'});session=applyClarificationAnalysis(session,{state:'READY_FOR_CONFIRMATION',interpretation:final,questions:[],unresolvedAmbiguities:[],confirmationSummary:{objective:final.objective,businessQuestions:final.businessQuestions,kpiDefinitions:['Case Count means a count of Cases.Id.'],scopeAndTime:['Trend uses a monthly reporting grain.'],dimensionsAndFilters:['Status remains an available filter.'],lifecycleDefinitions:['Open means status Open.'],materialPolicyDecisions:[]},conflictReasons:[],analysedAt:'2026-09-21T01:02:00Z'});return confirmClarificationUnderstanding(session,'2026-09-21T01:03:00Z')}

it('materializes version two only from human-confirmed structured meaning while retaining raw answers as provenance',()=>{const session=iterativeSession(),contract=materializeIterativeConfirmedRequirements({dataStructure:schema,session});expect(contract).toMatchObject({schema_version:2,objective:'Monitor case volume and lifecycle',provenance:{requirement:session.originalRequest,questions:[],selections:[],confirmedAt:'2026-09-21T01:03:00Z',clarificationSession:{state:'CONFIRMED',rounds:[{answers:[{rawAnswer:'Use the standard monthly management reporting period.'}]}]},humanConfirmation:{mode:'BUSINESS'}}});expect(contract.obligations.find(item=>item.id==='monthly-trend')?.timeGrain).toBe('MONTH');expect(validateConfirmedRequirementContract(contract,schema)).toEqual(contract)});

it('rejects unconfirmed or altered structured authority without parsing the raw answer',()=>{const confirmed=iterativeSession(),unconfirmed={...confirmed,state:'READY_FOR_CONFIRMATION' as const,confirmedAt:''};expect(()=>materializeIterativeConfirmedRequirements({dataStructure:schema,session:unconfirmed})).toThrow('explicitly confirmed');const contract=materializeIterativeConfirmedRequirements({dataStructure:schema,session:confirmed});contract.provenance.clarificationSession!.currentInterpretation={...contract.provenance.clarificationSession!.currentInterpretation!,objective:'Altered after confirmation'};expect(()=>validateConfirmedRequirementContract(contract,schema)).toThrow('inconsistent')});
