import type {BusinessQuestionCoverage,ConfirmedRequirementInterpretation,RequirementCoverageContract,RequirementMeasureSemantic,RequirementTimeGrain} from './foundry';
import {validateClarificationSession,type ClarificationSession,type InteractionMode,type MaterialConfirmationSummary} from './clarification';

export type ConfirmedRequirementObligation=Omit<RequirementCoverageContract,'required'|'minimumRepresentations'|'measures'|'timeGrain'|'lifecycleValues'>&{required:boolean;minimumRepresentations:number;measures:RequirementMeasureSemantic[];timeGrain:RequirementTimeGrain;lifecycleValues:string[]};
export type ConfirmedRequirementContract={artifact_kind:'ConfirmedRequirementContract';schema_version:1|2;objective:string;audience:string;pages:Array<{name:string;required:boolean}>;dimensions:string[];obligations:ConfirmedRequirementObligation[];businessQuestions:Array<BusinessQuestionCoverage&{required:true}>;provenance:{requirement:string;dataStructure:unknown;interpretation:ConfirmedRequirementInterpretation;questions:ConfirmedRequirementInterpretation['clarifications'];selections:Array<{clarificationId:string;optionId:string;optionLabel:string}>;confirmedAt:string;clarificationSession?:ClarificationSession;humanConfirmation?:{mode:InteractionMode;summary:MaterialConfirmationSummary;confirmedAt:string}}};
export class ConfirmedRequirementContractError extends Error{constructor(readonly reasons:string[]){super(`CONFIRMED_REQUIREMENT_CONTRACT_INVALID: ${reasons.join(' ')}`);this.name='ConfirmedRequirementContractError'}}

const exact=(value:string)=>value.trim().toLocaleLowerCase();
const empty=(value:string)=>!value.trim();
function schemaFields(value:unknown){const fields:string[]=[];if(!value||typeof value!=='object'||!Array.isArray((value as {tables?:unknown}).tables))return fields;for(const tableValue of (value as {tables:unknown[]}).tables){if(!tableValue||typeof tableValue!=='object')continue;const table=tableValue as {name?:unknown;columns?:unknown};if(typeof table.name!=='string'||!Array.isArray(table.columns))continue;for(const columnValue of table.columns)if(columnValue&&typeof columnValue==='object'&&typeof(columnValue as {name?:unknown}).name==='string')fields.push(`${table.name}.${(columnValue as {name:string}).name}`)}return fields}
function schemaFieldTypes(value:unknown){const fields=new Map<string,string>();if(!value||typeof value!=='object'||!Array.isArray((value as {tables?:unknown}).tables))return fields;for(const tableValue of (value as {tables:unknown[]}).tables){if(!tableValue||typeof tableValue!=='object')continue;const table=tableValue as {name?:unknown;columns?:unknown};if(typeof table.name!=='string'||!Array.isArray(table.columns))continue;for(const columnValue of table.columns)if(columnValue&&typeof columnValue==='object'&&typeof(columnValue as {name?:unknown}).name==='string')fields.set(`${table.name}.${(columnValue as {name:string}).name}`,String((columnValue as {type?:unknown}).type??''))}return fields}
const canonical=(value:unknown):unknown=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([left],[right])=>left.localeCompare(right)).map(([key,item])=>[key,canonical(item)])):value;
const stable=(value:unknown)=>JSON.stringify(canonical(value));

function validateConfirmedRequirementContractInternal(contract:ConfirmedRequirementContract,schema:unknown,semanticProjection=false):ConfirmedRequirementContract{
 const reasons:string[]=[],fields=schemaFields(schema),fieldTypes=schemaFieldTypes(schema),fieldSet=new Set(fields),pageNames=contract.pages.map(page=>page.name),pageSet=new Set(pageNames),obligationIds=contract.obligations.map(item=>item.id),obligationSet=new Set(obligationIds),measureById=new Map<string,RequirementMeasureSemantic>(),measureIdByName=new Map<string,string>(),supportedAggregations=new Set(['SUM','DISTINCTCOUNT','COUNT','AVERAGE','FILTERED_COUNT','RATIO','PERCENTAGE_OF_TOTAL']),supportedFormats=new Set(['currency','integer','decimal','percentage']);
 if(!contract.objective.trim()||!contract.audience.trim())reasons.push('Objective and audience are required.');
 if(!semanticProjection){
  if(contract.artifact_kind!=='ConfirmedRequirementContract'||![1,2].includes(contract.schema_version))reasons.push('Unsupported contract envelope.');
 const interpretation=contract.provenance?.interpretation,questions=contract.provenance?.questions??[],selections=contract.provenance?.selections??[];
 if(!contract.provenance||!contract.provenance.requirement?.trim()||!interpretation||interpretation.request_kind!=='POWER_BI_REPORT'||contract.objective!==interpretation.objective)reasons.push('Contract provenance is missing or inconsistent with the confirmed interpretation.');
 if(contract.schema_version===1&&interpretation&&stable(questions)!==stable(interpretation.clarifications))reasons.push('Questions diverge from interpretation provenance.');
 if(new Set(selections.map(item=>item.clarificationId)).size!==selections.length)reasons.push('Clarification selections must be unique.');
 const replay=new Map((interpretation?.coverageRequirements??[]).map(item=>[item.id,structuredClone(item)])),replayedIds=new Set<string>();let replayPages=interpretation?.pages??[],replayAudience=interpretation?.audience??'',pageScopeSet=false,audienceSet=false;
 for(const question of questions){const selection=selections.find(item=>item.clarificationId===question.id);if(question.required&&!selection)reasons.push(`Required clarification '${question.id}' has no materialized selection.`);if(!selection)continue;const option=question.options.find(item=>item.id===selection.optionId);if(!option||option.label!==selection.optionLabel)reasons.push(`Clarification '${question.id}' has an unknown or altered selection.`);else{if(option.pageScope.length){if(pageScopeSet)reasons.push(`Clarification '${question.id}' has contradictory page-scope effects.`);else{replayPages=option.pageScope;pageScopeSet=true}}if(option.audience){if(audienceSet)reasons.push(`Clarification '${question.id}' has contradictory audience effects.`);else{replayAudience=option.audience;audienceSet=true}}for(const override of option.coverageOverrides){if(!question.coverageRequirementIds.includes(override.id)||!replay.has(override.id)||replayedIds.has(override.id))reasons.push(`Clarification '${question.id}' has contradictory or unsupported effects.`);else{replay.set(override.id,structuredClone(override));replayedIds.add(override.id)}}}}
 if(selections.some(selection=>!questions.some(question=>question.id===selection.clarificationId)))reasons.push('Contract contains a selection for an unknown clarification.');
 if(contract.schema_version===1){if(stable([...replay.values()])!==stable(contract.obligations))reasons.push('Materialized obligations do not equal the deterministic clarification result.');if(stable(pageNames)!==stable(replayPages)||contract.audience!==replayAudience)reasons.push('Materialized page scope or audience does not equal the deterministic clarification result.')}else{const session=contract.provenance.clarificationSession,confirmation=contract.provenance.humanConfirmation,lastAnalysis=session?.analyses.at(-1);try{if(session)validateClarificationSession(session,true);else throw new Error('missing')}catch{reasons.push('Iterative clarification transcript is malformed.')}if(!session||session.state!=='CONFIRMED'||!session.currentInterpretation||!lastAnalysis||lastAnalysis.proposedState!=='READY_FOR_CONFIRMATION'||stable(lastAnalysis.interpretation)!==stable(session.currentInterpretation)||stable(lastAnalysis.unresolvedAmbiguities)!==stable(session.unresolvedAmbiguities)||stable(lastAnalysis.confirmationSummary)!==stable(session.confirmationSummary)||stable(session.currentInterpretation)!==stable(interpretation)||session.originalRequest!==contract.provenance.requirement||session.confirmedAt!==contract.provenance.confirmedAt)reasons.push('Iterative clarification provenance is missing, unconfirmed, or inconsistent.');if(!confirmation||confirmation.confirmedAt!==contract.provenance.confirmedAt||confirmation.mode!==session?.mode||stable(confirmation.summary)!==stable(session?.confirmationSummary))reasons.push('Human confirmation provenance is missing or inconsistent.');if(questions.length||selections.length||interpretation?.clarifications.length)reasons.push('Version-two contracts cannot use legacy clarification selections as semantic authority.');if(stable(interpretation?.coverageRequirements??[])!==stable(contract.obligations)||stable(pageNames)!==stable(interpretation?.pages??[])||contract.audience!==(interpretation?.audience??''))reasons.push('Confirmed contract does not equal the human-confirmed structured interpretation.')}
 }
 if(pageSet.size!==pageNames.length||pageNames.some(name=>!name.trim())||contract.pages.some(page=>!page.required))reasons.push('Page scope contains an empty, duplicate, or non-required confirmed page.');
 if(new Set(obligationIds).size!==obligationIds.length)reasons.push('Obligation IDs must be unique.');
 for(const obligation of contract.obligations){
  const referencedFields=[...obligation.fields,...obligation.measures.flatMap(measure=>[measure.field,measure.filterField,measure.contextField]).filter(value=>!empty(value))];
  if(!obligation.id.trim()||!['KPI','FILTER','BREAKDOWN','TREND','LIFECYCLE'].includes(obligation.kind))reasons.push(`Obligation '${obligation.id}' has an unsupported identity or kind.`);
  if(obligation.required?obligation.minimumRepresentations<1:obligation.minimumRepresentations!==0)reasons.push(`Obligation '${obligation.id}' has contradictory required/presentation cardinality.`);
  if(obligation.pageNames.some(page=>!pageSet.has(page)))reasons.push(`Obligation '${obligation.id}' references an unknown page.`);
  if(referencedFields.some(field=>!fieldSet.has(field)))reasons.push(`Obligation '${obligation.id}' references a field outside the confirmed schema.`);
  if(obligation.measureNames.some(name=>!obligation.measures.some(measure=>measure.name===name))||(obligation.kind!=='FILTER'&&obligation.measures.length===0))reasons.push(`Obligation '${obligation.id}' has inconsistent or incomplete measure semantics.`);
  const shape=(obligation.kind==='KPI'&&obligation.measureNames.length>0&&obligation.fields.length===0)||(obligation.kind==='FILTER'&&obligation.measureNames.length===0&&obligation.fields.length>0)||(obligation.kind==='TREND'&&obligation.measureNames.length>0&&obligation.fields.length===1&&obligation.timeGrain!=='NONE')||(['BREAKDOWN','LIFECYCLE'].includes(obligation.kind)&&obligation.measureNames.length>0&&obligation.fields.length>0);
  if(!shape)reasons.push(`Obligation '${obligation.id}' is structurally incomplete.`);
  if(obligation.kind!=='TREND'&&obligation.timeGrain!=='NONE')reasons.push(`Obligation '${obligation.id}' has unsupported time semantics.`);
  if((obligation.kind==='LIFECYCLE')!==Boolean(obligation.lifecycleValues.length))reasons.push(`Obligation '${obligation.id}' has incomplete or misplaced lifecycle semantics.`);
  if(obligation.kind==='TREND'&&fieldTypes.size>0&&!['date','datetime'].includes(fieldTypes.get(obligation.fields[0])??''))reasons.push(`Obligation '${obligation.id}' does not bind its time grain to a date field.`);
  if(obligation.kind==='LIFECYCLE'&&obligation.lifecycleValues.some(value=>!obligation.measures.some(measure=>measure.filterField&&measure.filterValue===value)))reasons.push(`Obligation '${obligation.id}' does not define every lifecycle member in typed measure semantics.`);
  for(const measure of obligation.measures){const prior=measureById.get(measure.id),nameKey=exact(measure.name),priorNameId=measureIdByName.get(nameKey);if(prior&&stable(prior)!==stable(measure))reasons.push(`Measure '${measure.id}' has contradictory semantics.`);else measureById.set(measure.id,measure);if(priorNameId&&priorNameId!==measure.id)reasons.push(`Measure name '${measure.name}' is assigned to multiple measure IDs.`);else if(nameKey)measureIdByName.set(nameKey,measure.id);const direct=['SUM','DISTINCTCOUNT','COUNT','AVERAGE'].includes(measure.aggregation),filtered=measure.aggregation==='FILTERED_COUNT',ratio=measure.aggregation==='RATIO',percentage=measure.aggregation==='PERCENTAGE_OF_TOTAL';if(!measure.id.trim()||!measure.name.trim()||!measure.businessDefinition.trim())reasons.push(`Measure '${measure.id}' is incomplete.`);if(!supportedAggregations.has(measure.aggregation)||!supportedFormats.has(measure.format))reasons.push(`Measure '${measure.id}' uses an unsupported aggregation or format.`);if(direct&&(!measure.field||!empty(measure.numeratorMeasureId)||!empty(measure.denominatorMeasureId)||!empty(measure.filterField)||!empty(measure.filterValue)||!empty(measure.contextField)))reasons.push(`Measure '${measure.id}' has an incoherent direct aggregation.`);if(filtered&&(!measure.field||!measure.filterField||!measure.filterValue||!empty(measure.numeratorMeasureId)||!empty(measure.denominatorMeasureId)||!empty(measure.contextField)))reasons.push(`Measure '${measure.id}' has an incoherent filtered-count definition.`);if(ratio&&(!empty(measure.field)||!measure.numeratorMeasureId||!measure.denominatorMeasureId||!empty(measure.filterField)||!empty(measure.filterValue)||!empty(measure.contextField)))reasons.push(`Measure '${measure.id}' has an incoherent ratio definition.`);if(percentage&&(!empty(measure.field)||!measure.numeratorMeasureId||!measure.denominatorMeasureId||!measure.contextField||!empty(measure.filterField)||!empty(measure.filterValue)))reasons.push(`Measure '${measure.id}' has an incoherent percentage-of-total definition.`)}
 }
 for(const measure of measureById.values())for(const operand of [measure.numeratorMeasureId,measure.denominatorMeasureId].filter(value=>!empty(value)))if(operand===measure.id)reasons.push(`Measure '${measure.id}' references itself.`);else if(!measureById.has(operand))reasons.push(`Measure '${measure.id}' references unknown operand '${operand}'.`);
 const dependencies=new Map([...measureById.values()].map(measure=>[measure.id,[measure.numeratorMeasureId,measure.denominatorMeasureId].filter(value=>!empty(value)&&measureById.has(value))])),visited=new Set<string>(),visiting=new Set<string>();
 const visit=(id:string):boolean=>{if(visiting.has(id))return true;if(visited.has(id))return false;visiting.add(id);const cyclic=(dependencies.get(id)??[]).some(visit);visiting.delete(id);visited.add(id);return cyclic};
 if([...dependencies.keys()].some(visit))reasons.push('Measure dependency graph contains a cycle.');
 if(new Set(contract.dimensions).size!==contract.dimensions.length||contract.dimensions.some(field=>!fieldSet.has(field)||!contract.obligations.some(item=>item.fields.includes(field))))reasons.push('Confirmed dimensions must be exact schema fields covered by obligations.');
 if(contract.provenance.interpretation.kpis.some(kpi=>!contract.obligations.some(item=>item.required&&item.kind==='KPI'&&item.measureNames.includes(kpi)))||contract.provenance.interpretation.filters.some(filter=>!contract.obligations.some(item=>item.required&&item.kind==='FILTER'&&item.fields.some(field=>exact(field)===exact(filter)||exact(field.split('.').at(-1)??field)===exact(filter.split('.').at(-1)??filter)))))reasons.push('Confirmed KPI or filter obligations are incomplete.');
 if(contract.businessQuestions.length!==contract.provenance.interpretation.businessQuestions.length||new Set(contract.businessQuestions.map(item=>item.question)).size!==contract.businessQuestions.length||contract.businessQuestions.some(item=>!item.required||!contract.provenance.interpretation.businessQuestions.includes(item.question)||!item.coverageRequirementIds.length||item.coverageRequirementIds.some(id=>!obligationSet.has(id)||!contract.obligations.find(obligation=>obligation.id===id)?.required))||stable(contract.businessQuestions.map(({required:_,...item})=>item))!==stable(contract.provenance.interpretation.businessQuestionCoverage))reasons.push('Business-question mappings are incomplete or unsupported.');
 if(reasons.length)throw new ConfirmedRequirementContractError([...new Set(reasons)]);return structuredClone(contract)
}

export function validateConfirmedRequirementContract(contract:ConfirmedRequirementContract,schema:unknown=contract.provenance.dataStructure):ConfirmedRequirementContract{return validateConfirmedRequirementContractInternal(contract,schema)}

function resolveIterativeAuthority(dataStructure:unknown,session:ClarificationSession){
 const interpretation=session.currentInterpretation!;if(interpretation.request_kind!=='POWER_BI_REPORT'||interpretation.clarifications.length||interpretation.ambiguities.length)throw new ConfirmedRequirementContractError(['Iterative interpretation is out of scope, contains legacy questions, or retains unresolved ambiguity.']);
 const fields=schemaFields(dataStructure),dimensions=interpretation.dimensions.map(dimension=>{const matches=fields.filter(field=>exact(field)===exact(dimension)||exact(field.split('.').at(-1)??field)===exact(dimension));if(matches.length!==1)throw new ConfirmedRequirementContractError([`Dimension '${dimension}' does not resolve to one exact confirmed schema field.`]);return matches[0]});
 const obligations=interpretation.coverageRequirements.map(item=>{if(typeof item.required!=='boolean'||typeof item.minimumRepresentations!=='number'||!item.measures||!item.timeGrain||!item.lifecycleValues)throw new ConfirmedRequirementContractError([`Obligation '${item.id}' is not fully typed.`]);return structuredClone(item) as ConfirmedRequirementObligation});
 return{interpretation,dimensions,obligations}
}

export function validateIterativeConfirmationReadiness(input:{dataStructure:unknown;session:ClarificationSession}){
 if(input.session.state!=='READY_FOR_CONFIRMATION'||!input.session.currentInterpretation||!input.session.confirmationSummary)throw new ConfirmedRequirementContractError(['Iterative meaning is not ready for confirmation.']);let session:ClarificationSession;try{session=validateClarificationSession(input.session)}catch{throw new ConfirmedRequirementContractError(['Iterative clarification transcript is malformed or incomplete.'])}const{interpretation,dimensions,obligations}=resolveIterativeAuthority(input.dataStructure,session);
 // This transient projection exists only to reuse the exact deterministic semantic validator. It is neither returned nor authoritative and cannot cross the human-confirmation boundary.
 const projection:ConfirmedRequirementContract={artifact_kind:'ConfirmedRequirementContract',schema_version:2,objective:interpretation.objective,audience:interpretation.audience,pages:interpretation.pages.map(name=>({name,required:true})),dimensions,obligations,businessQuestions:interpretation.businessQuestionCoverage.map(item=>({...structuredClone(item),required:true as const})),provenance:{requirement:session.originalRequest,dataStructure:structuredClone(input.dataStructure),interpretation:structuredClone(interpretation),questions:[],selections:[],confirmedAt:'',clarificationSession:session}};
 validateConfirmedRequirementContractInternal(projection,input.dataStructure,true);return{dimensions:structuredClone(dimensions),obligations:structuredClone(obligations)}
}

export function materializeConfirmedRequirements(input:{requirement:string;dataStructure:unknown;interpretation:ConfirmedRequirementInterpretation;selections:Record<string,string>;confirmedAt:string}):ConfirmedRequirementContract{
 const interpretation=structuredClone(input.interpretation),obligations=new Map(interpretation.coverageRequirements.map(item=>[item.id,structuredClone(item)])),selected:Array<{clarificationId:string;optionId:string;optionLabel:string}>=[],overridden=new Set<string>();let pageScope=interpretation.pages,audience=interpretation.audience,pageScopeSet=false,audienceSet=false;
 for(const clarification of interpretation.clarifications){const optionId=input.selections[clarification.id]?.trim();if(!optionId){if(clarification.required)throw new ConfirmedRequirementContractError([`Required clarification '${clarification.id}' has no typed selection.`]);continue}const option=clarification.options.find(item=>item.id===optionId);if(!option)throw new ConfirmedRequirementContractError([`Clarification '${clarification.id}' selected an unknown option.`]);const overrideIds=option.coverageOverrides.map(item=>item.id);if(new Set(overrideIds).size!==overrideIds.length||overrideIds.length!==clarification.coverageRequirementIds.length||overrideIds.some(id=>!clarification.coverageRequirementIds.includes(id)||!obligations.has(id)||overridden.has(id)))throw new ConfirmedRequirementContractError([`Clarification '${clarification.id}' has incomplete, unknown, duplicate, or contradictory typed effects.`]);if(option.pageScope.length){if(pageScopeSet)throw new ConfirmedRequirementContractError([`Clarification '${clarification.id}' has contradictory page-scope effects.`]);pageScope=option.pageScope;pageScopeSet=true}if(option.audience){if(audienceSet)throw new ConfirmedRequirementContractError([`Clarification '${clarification.id}' has contradictory audience effects.`]);audience=option.audience;audienceSet=true}for(const override of option.coverageOverrides){obligations.set(override.id,structuredClone(override));overridden.add(override.id)}selected.push({clarificationId:clarification.id,optionId:option.id,optionLabel:option.label})}
 const resolved=[...obligations.values()].map(item=>{if(typeof item.required!=='boolean'||typeof item.minimumRepresentations!=='number'||!item.measures||!item.timeGrain||!item.lifecycleValues)throw new ConfirmedRequirementContractError([`Obligation '${item.id}' is not fully typed.`]);return item as ConfirmedRequirementObligation});
 const fields=schemaFields(input.dataStructure),dimensions=interpretation.dimensions.map(dimension=>{const matches=fields.filter(field=>exact(field)===exact(dimension)||exact(field.split('.').at(-1)??field)===exact(dimension));if(matches.length!==1)throw new ConfirmedRequirementContractError([`Dimension '${dimension}' does not resolve to one exact schema field.`]);return matches[0]});
 return validateConfirmedRequirementContract({artifact_kind:'ConfirmedRequirementContract',schema_version:1,objective:interpretation.objective,audience,pages:pageScope.map(name=>({name,required:true})),dimensions,obligations:resolved,businessQuestions:interpretation.businessQuestionCoverage.map(item=>({...structuredClone(item),required:true as const})),provenance:{requirement:input.requirement,dataStructure:structuredClone(input.dataStructure),interpretation,questions:structuredClone(interpretation.clarifications),selections:selected,confirmedAt:input.confirmedAt}},input.dataStructure)
}

export function materializeIterativeConfirmedRequirements(input:{dataStructure:unknown;session:ClarificationSession}):ConfirmedRequirementContract{
 if(input.session.state!=='CONFIRMED'||!input.session.confirmedAt||!input.session.currentInterpretation||!input.session.confirmationSummary)throw new ConfirmedRequirementContractError(['Iterative meaning must be explicitly confirmed before contract materialization.']);let session:ClarificationSession;try{session=validateClarificationSession(input.session,true)}catch{throw new ConfirmedRequirementContractError(['Iterative clarification transcript is malformed or incomplete.'])}const{interpretation,dimensions,obligations}=resolveIterativeAuthority(input.dataStructure,session);
 return validateConfirmedRequirementContract({artifact_kind:'ConfirmedRequirementContract',schema_version:2,objective:interpretation.objective,audience:interpretation.audience,pages:interpretation.pages.map(name=>({name,required:true})),dimensions,obligations,businessQuestions:interpretation.businessQuestionCoverage.map(item=>({...structuredClone(item),required:true as const})),provenance:{requirement:session.originalRequest,dataStructure:structuredClone(input.dataStructure),interpretation:structuredClone(interpretation),questions:[],selections:[],confirmedAt:session.confirmedAt,clarificationSession:session,humanConfirmation:{mode:session.mode,summary:structuredClone(session.confirmationSummary!),confirmedAt:session.confirmedAt}}},input.dataStructure)
}
