import {expect,it} from 'vitest';
import {materializeConfirmedRequirements,validateConfirmedRequirementContract} from './confirmedRequirements';
import type {ConfirmedRequirementInterpretation,RequirementCoverageContract,RequirementMeasureSemantic} from './foundry';

const schema={tables:[{name:'Cases',columns:[{name:'Id',type:'text'},{name:'Status',type:'text'},{name:'CreatedAt',type:'date'}]}]};
const count:RequirementMeasureSemantic={id:'case-count',name:'Case Count',businessDefinition:'Count of cases',aggregation:'COUNT',field:'Cases.Id',numeratorMeasureId:'',denominatorMeasureId:'',format:'integer',filterField:'',filterValue:'',contextField:''};
const open:RequirementMeasureSemantic={id:'open-cases',name:'Open Cases',businessDefinition:'Count of cases in the confirmed open lifecycle',aggregation:'FILTERED_COUNT',field:'Cases.Id',numeratorMeasureId:'',denominatorMeasureId:'',format:'integer',filterField:'Cases.Status',filterValue:'Open',contextField:''};
const obligation=(value:Partial<RequirementCoverageContract>&Pick<RequirementCoverageContract,'id'|'kind'|'measureNames'|'fields'>):RequirementCoverageContract=>({pageNames:['Overview'],required:true,minimumRepresentations:1,measures:[],timeGrain:'NONE',lifecycleValues:[],...value});
const monthly=obligation({id:'monthly-trend',kind:'TREND',measureNames:['Case Count'],fields:['Cases.CreatedAt'],measures:[count],timeGrain:'MONTH'});
const quarterly={...monthly,timeGrain:'QUARTER' as const};
const interpretation=():ConfirmedRequirementInterpretation=>({request_kind:'POWER_BI_REPORT',objective:'Monitor case volume and lifecycle',businessQuestions:['How many cases arrive over time?','Which cases are open?'],kpis:['Case Count'],dimensions:['CreatedAt','Status'],filters:['Cases.Status'],audience:'Operations leaders',pages:['Overview'],assumptions:[],ambiguities:['Requested trend grain'],clarifications:[{id:'trend-grain',category:'TIME_COMPARISON',question:'Which reporting grain is required?',reason:'The trend grain changes the confirmed time obligation.',required:true,coverageRequirementIds:['monthly-trend'],selection:'SINGLE',options:[{id:'monthly',label:'Monthly',coverageOverrides:[monthly],pageScope:[],audience:''},{id:'quarterly',label:'Quarterly',coverageOverrides:[quarterly],pageScope:[],audience:''}]}],coverageRequirements:[obligation({id:'case-count-kpi',kind:'KPI',measureNames:['Case Count'],fields:[],measures:[count]}),obligation({id:'status-filter',kind:'FILTER',measureNames:[],fields:['Cases.Status']}),monthly,obligation({id:'open-lifecycle',kind:'LIFECYCLE',measureNames:['Open Cases'],fields:['Cases.Status'],measures:[open],lifecycleValues:['Open']})],businessQuestionCoverage:[{question:'How many cases arrive over time?',coverageRequirementIds:['case-count-kpi','monthly-trend']},{question:'Which cases are open?',coverageRequirementIds:['open-lifecycle','status-filter']}]});
const build=(selections:Record<string,string>={'trend-grain':'monthly'})=>materializeConfirmedRequirements({requirement:'Show monthly case volume, status filters, and the open lifecycle.',dataStructure:schema,interpretation:interpretation(),selections,confirmedAt:'2026-09-21T00:00:00Z'});

it('deterministically materializes a selected typed option and preserves separate provenance',()=>{const contract=build();expect(contract).toMatchObject({artifact_kind:'ConfirmedRequirementContract',schema_version:1,objective:'Monitor case volume and lifecycle',pages:[{name:'Overview',required:true}],dimensions:['Cases.CreatedAt','Cases.Status'],provenance:{requirement:'Show monthly case volume, status filters, and the open lifecycle.',selections:[{clarificationId:'trend-grain',optionId:'monthly',optionLabel:'Monthly'}]}});expect(contract.obligations.find(item=>item.id==='monthly-trend')).toMatchObject({timeGrain:'MONTH',required:true,minimumRepresentations:1});expect(contract.provenance.questions[0].question).toContain('reporting grain');expect(validateConfirmedRequirementContract(contract,schema)).toEqual(contract)});

it('fails closed for missing or unknown selections without parsing free text',()=>{expect(()=>build({})).toThrow("Required clarification 'trend-grain' has no typed selection");expect(()=>build({'trend-grain':'Use the last 30 days'})).toThrow("selected an unknown option")});

it('fails closed for schema drift, altered selections, obligation tampering, and unsupported cardinality',()=>{const contract=build();const cases=[{...contract,dimensions:['Cases.Missing']},{...contract,provenance:{...contract.provenance,selections:[{...contract.provenance.selections[0],optionLabel:'Altered'}]}},{...contract,obligations:contract.obligations.map(item=>item.id==='monthly-trend'?{...item,timeGrain:'YEAR' as const}:item)},{...contract,obligations:contract.obligations.map(item=>item.id==='case-count-kpi'?{...item,minimumRepresentations:0}:item)}];for(const candidate of cases)expect(()=>validateConfirmedRequirementContract(candidate,schema)).toThrow('CONFIRMED_REQUIREMENT_CONTRACT_INVALID')});

it('rejects contradictory clarification effects targeting the same obligation',()=>{const value=interpretation();value.clarifications.push({...value.clarifications[0],id:'second-grain',question:'Confirm the same grain again'});expect(()=>materializeConfirmedRequirements({requirement:'Cases',dataStructure:schema,interpretation:value,selections:{'trend-grain':'monthly','second-grain':'quarterly'},confirmedAt:'2026-09-21T00:00:00Z'})).toThrow('contradictory typed effects')});

it('materializes page scope and obligation placement from one typed selection',()=>{const value=interpretation();value.pages=['Overview','Detail'];const ids=value.coverageRequirements.map(item=>item.id),onPage=(page:string)=>value.coverageRequirements.map(item=>({...item,pageNames:[page]}));value.clarifications=[{id:'page-scope',category:'PAGE_SCOPE',question:'Which page is required?',reason:'Confirms the required report scope.',required:true,coverageRequirementIds:ids,selection:'SINGLE',options:[{id:'overview',label:'Overview',coverageOverrides:onPage('Overview'),pageScope:['Overview'],audience:''},{id:'detail',label:'Detail',coverageOverrides:onPage('Detail'),pageScope:['Detail'],audience:''}]}];const contract=materializeConfirmedRequirements({requirement:'Cases',dataStructure:schema,interpretation:value,selections:{'page-scope':'detail'},confirmedAt:'2026-09-21T00:00:00Z'});expect(contract.pages).toEqual([{name:'Detail',required:true}]);expect(contract.obligations.every(item=>item.pageNames[0]==='Detail')).toBe(true)});

it('retains optional presentation as an explicit zero-minimum obligation',()=>{const value=interpretation(),optional=obligation({id:'optional-status-breakdown',kind:'BREAKDOWN',measureNames:['Case Count'],fields:['Cases.Status'],measures:[count],required:false,minimumRepresentations:0});value.coverageRequirements.push(optional);const contract=materializeConfirmedRequirements({requirement:'Cases',dataStructure:schema,interpretation:value,selections:{'trend-grain':'monthly'},confirmedAt:'2026-09-21T00:00:00Z'});expect(contract.obligations.at(-1)).toMatchObject({id:'optional-status-breakdown',required:false,minimumRepresentations:0})});
