import {readFileSync} from 'node:fs';
import {expect,it} from 'vitest';
import {createDeploymentGuideModel,deploymentGuideDocument,generateDeploymentGuide,normalizeDocumentText,type DeploymentGuideInput} from './deploymentGuide';
import {defaultTenantSettings} from './tenant';

const input=():DeploymentGuideInput=>({
 run:{id:'run-étude-42',generatedAt:'2026-09-19T10:30:00+10:00',applicationVersion:'bounded-generic-pbip-1'},
 interpretation:{objective:'Monitor café operations — safely',businessQuestions:['Which teams meet the target?'],kpis:['Resolution rate'],audience:'Operations leaders',pages:['Executive overview']},
 data:{kind:'REQUEST_DATA_STRUCTURE',fileName:'operations-échantillon.csv',format:'CSV',parsedAt:'2026-09-19',tables:[{name:'Cases',sourceName:'Cas d’assistance',rowCount:2,rows:[['Paris','4'],['München','7']],columns:[{name:'City',sourceName:'Ville',type:'text',nullable:false,sampleValues:['Paris','München']},{name:'Duration',sourceName:'Durée',type:'integer',nullable:false,sampleValues:['4','7']}]}],relationships:[]},
 design:{artifact_kind:'ReportDesign',schema_version:1,projectName:'Opérations — Qualité',overview:'A concise view of support quality using approved definitions.',audience:'Regional leaders',dataModel:{factTables:['Cases'],dimensionTables:[],relationships:[]},measures:[{id:'duration',name:'Durée moyenne',businessDefinition:'Average duration',aggregation:'AVERAGE',field:'Cases.Duration',numeratorMeasureId:'',denominatorMeasureId:'',format:'decimal'}],pages:[{id:'overview',name:'Vue d’ensemble',purpose:'Compare performance by city',visuals:[{id:'kpi',type:'card',title:'Durée moyenne',categoryField:'',measureIds:['duration'],fields:[],altText:'Durée moyenne — résumé'}]}],filters:[],branding:{themeName:'Tenant',primary:'#0F6CBD',accent:'#2D7D9A'},accessibility:['Text alternatives'],standardsApplied:[{citation:'local:test#1',decision:'Use approved visuals'}],assumptions:[],warnings:['Confirm the production source before publishing.'],generationRequirements:[]},
 tenant:structuredClone(defaultTenantSettings),policy:{outcome:'WARNING',generation:'AVAILABLE',evaluations:[{ruleId:'COMPLEXITY-001',category:'complexity',severity:'warning',result:'WARNING',reason:'Review the executive page density.',recommendedAction:'Review before release.'}]},
 candidate:{kind:'PowerBICandidate',generatorVersion:'bounded-generic-pbip-1',projectName:'OperationsQuality',files:{'OperationsQuality.pbip':'{}'},runtime:{desktop:'NOT_RUN',dax:'NOT_RUN'},release:'NOT_ELIGIBLE'},
 validation:{status:'PASS',checks:[{id:'PROJECT_STRUCTURE',status:'PASS',message:'Project structure is present.'}]},
});

it('creates a valid Unicode PDF artefact with the fixed professional filename',async()=>{const result=await generateDeploymentGuide(input());expect(result.filename).toBe('Report-Deployment-Guide.pdf');expect(new TextDecoder('latin1').decode(result.bytes.slice(0,8))).toContain('%PDF-');expect(new TextDecoder('latin1').decode(result.bytes.slice(-32))).toContain('%%EOF');expect(result.bytes.length).toBeGreaterThan(10_000);expect(result.model.reportName).toBe('Opérations — Qualité');expect(JSON.stringify(deploymentGuideDocument(result.model))).toContain('Opérations — Qualité');});
it('uses the same filename for every report while retaining each Unicode report name inside',async()=>{for(const reportName of ['Opérations — Qualité','営業レポート — 東京']){const source=input();source.design.projectName=reportName;const result=await generateDeploymentGuide(source);expect(result.filename).toBe('Report-Deployment-Guide.pdf');expect(result.model.reportName).toBe(reportName);expect(JSON.stringify(deploymentGuideDocument(result.model))).toContain(reportName);}});
it('uses current report, schema, compiler and warning data',()=>{const model=createDeploymentGuideModel(input());expect(model.purpose).toContain('support quality');expect(model.tables).toEqual([{name:'Cas d’assistance',columns:['Ville','Durée']}]);expect(model.pages[0]).toMatchObject({name:'Vue d’ensemble',visuals:['Durée moyenne (card)']});expect(model.measures).toEqual(['Durée moyenne']);expect(model.warnings).toEqual(['Confirm the production source before publishing.']);expect(model.projectName).toBe('OperationsQuality');expect(model.validationOutcome).toBe('PASS');});
it('handles missing optional values without inventing production configuration',()=>{const source=input();source.design.overview='';source.design.audience='';source.interpretation.objective='';source.interpretation.audience='';source.design.warnings=[];source.design.assumptions=[];const model=createDeploymentGuideModel(source);expect(model.purpose).toBe('To be confirmed');expect(model.audience).toBe('To be confirmed');expect(model.warnings).toEqual([]);expect(model.assumptions).toEqual([]);expect(JSON.stringify(model)).not.toMatch(/gateway name|server name|database name|workspace name/i);});
it('reports RLS only when present in the current design',()=>{const absent=createDeploymentGuideModel(input());expect(absent.rlsRequirements).toEqual([]);const source=input();source.design.generationRequirements=['RLS: Regional reviewers may view their assigned region only.'];const present=createDeploymentGuideModel(source);expect(present.rlsRequirements).toEqual(['RLS: Regional reviewers may view their assigned region only.']);});
it('allowlists safe fields and excludes arbitrary secrets and runtime state',()=>{const source=input() as DeploymentGuideInput&Record<string,unknown>;source.azureApiKey='secret-key-value';source.environment={AZURE_AI_API_KEY:'secret-key-value',path:'/Users/private/project'};source.systemPrompt='private prompt';const serialized=JSON.stringify(createDeploymentGuideModel(source));for(const forbidden of ['secret-key-value','AZURE_AI_API_KEY','/Users/private/project','private prompt'])expect(serialized).not.toContain(forbidden);});
it('contains no scenario-specific product branching',()=>{const source=readFileSync(new URL('./deploymentGuide.ts',import.meta.url),'utf8');for(const forbidden of ['ServiceNow','SalesPerformance','Sales Performance','ServiceDesk','APBRA-90'])expect(source).not.toContain(forbidden);});
it('removes invalid document characters while preserving legitimate Unicode',()=>{expect(normalizeDocumentText('Résumé — “München” request-\u0000\u00ad\u200b\ufffe\uffffspecific')).toBe('Résumé — “München” request-specific');const source=input();source.tenant.organisation.displayName='Société\u0007 internationale';source.design.projectName='Opérations\ufffe — Qualité';source.design.overview='Résumé — “café”\u202e';source.data.tables[0].sourceName='Cas\u0000 d’assistance';source.design.warnings=['Vérifier\u2028la connexion'];const model=createDeploymentGuideModel(source);const serialized=JSON.stringify(model);expect(model.organisation).toBe('Société internationale');expect(model.reportName).toBe('Opérations — Qualité');expect(model.purpose).toBe('Résumé — “café”');expect(model.tables[0].name).toBe('Cas d’assistance');expect(model.warnings).toEqual(['Vérifier la connexion']);expect(serialized).not.toMatch(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f\ufffe\uffff]/);});
it('classifies deployment actions using current-run evidence',()=>{const withoutRls=JSON.stringify(deploymentGuideDocument(createDeploymentGuideModel(input())));expect(withoutRls).toContain('Required for this candidate');expect(withoutRls).toContain('RLS configuration is not applicable');expect(withoutRls).toContain('Gateway requirement: To be confirmed.');expect(withoutRls).not.toContain('where applicable');const source=input();source.design.generationRequirements=['RLS: Regional reviewers may view their assigned region only.'];const withRls=JSON.stringify(deploymentGuideDocument(createDeploymentGuideModel(source)));expect(withRls).toContain('Map the generated RLS requirements');expect(withRls).not.toContain('RLS configuration is not applicable');});
