import React,{useEffect,useRef,useState} from 'react';
import {generationApi,type DurableContract,type GenerationAttempt} from './api';

const statusLabel=(status:GenerationAttempt['status'])=>({PENDING:'Queued',RUNNING:'Building',SUCCEEDED:'Report ready',FAILED:'Build failed',CANCELLED:'Cancelled'}[status]);

export function DurableGeneration({caseId,contract,csrfToken,onError}:{caseId:string;contract:DurableContract|null;csrfToken:string;onError:(error:unknown)=>void}){
 const [attempts,setAttempts]=useState<GenerationAttempt[]>([]),[busy,setBusy]=useState(false),[cancelling,setCancelling]=useState<string|null>(null),buildCommand=useRef<string|null>(null);
 const refresh=async()=>setAttempts((await generationApi.list(caseId)).items);
 useEffect(()=>{void refresh().catch(onError)},[caseId]);
 useEffect(()=>{if(!busy)return;const timer=window.setInterval(()=>void refresh().catch(onError),250);return()=>window.clearInterval(timer)},[busy,caseId]);
 async function run(mode:'BUILD'|'RETRY'|'REGENERATE',source?:GenerationAttempt){if(!contract?.current)return;setBusy(true);if(mode!=='BUILD'||!buildCommand.current)buildCommand.current=crypto.randomUUID();try{const attempt=await generationApi.start(caseId,contract.id,buildCommand.current,csrfToken,mode,source?.id);buildCommand.current=null;setAttempts(current=>[attempt,...current.filter(item=>item.id!==attempt.id)])}catch(error){onError(error)}finally{setBusy(false)}}
 async function cancel(attempt:GenerationAttempt){setCancelling(attempt.id);try{const updated=await generationApi.cancel(caseId,attempt.id,csrfToken);setAttempts(current=>current.map(item=>item.id===updated.id?updated:item))}catch(error){onError(error)}finally{setCancelling(null)}}
 const latest=attempts[0];
 return <section className="generation-panel" aria-labelledby={`generation-${caseId}`}><div className="section-title"><div><h3 id={`generation-${caseId}`}>Generated reports</h3><p>Each build is bound to the exact confirmed meaning and qualified evidence. Validated ZIP outputs remain private.</p></div><span className="status-badge">{attempts.length} attempt{attempts.length===1?'':'s'}</span></div>{!contract?.current?<p role="status"><strong>Confirm the current understanding before building a report.</strong> Historical outputs remain available below.</p>:<div className="command-bar"><button disabled={busy} onClick={()=>void run(latest?.status==='SUCCEEDED'?'REGENERATE':'BUILD')}>{busy?'Building report…':latest?.status==='SUCCEEDED'?'Build another version':'Build report'}</button>{latest?.status==='FAILED'&&<button className="subtle" disabled={busy} onClick={()=>void run('RETRY',latest)}>Retry failed build</button>}{latest&&['PENDING','RUNNING'].includes(latest.status)&&<button className="subtle" disabled={cancelling===latest.id} onClick={()=>void cancel(latest)}>{cancelling===latest.id?'Cancelling…':'Cancel build'}</button>}</div>}{attempts.length===0?<p>No report builds yet.</p>:<ol className="generation-history">{attempts.map(attempt=><li key={attempt.id}><div><strong>Version {attempt.attempt_number} · {statusLabel(attempt.status)}</strong><small>{new Date(attempt.created_at).toLocaleString()} · {attempt.provenance.mode}</small></div>{attempt.failure&&<p role="alert">{attempt.failure.message}</p>}{attempt.artifact&&<><a className="primary-link" href={generationApi.artifactUrl(caseId,attempt.id)} download={attempt.artifact.filename}>Download validated Power BI candidate</a><small>ZIP · {attempt.artifact.byte_size.toLocaleString()} bytes · SHA-256 {attempt.artifact.content_digest.slice(0,12)}…</small></>}</li>)}</ol>}<p className="simulation-note">Local deterministic report-design substitute — no model call. Power BI Desktop, DAX, RLS and deployment validation are not run.</p></section>
}
