import React,{useEffect,useMemo,useState} from 'react';
import {zipFiles} from './archive';
import {foundryStatus,generateGroundedReportDesign,interpretRequirement,type AIMetrics,type FoundryStatus,type ReportDesign,type RequirementInterpretation} from './foundry';
import {compilePowerBI,validateGenericCandidate,type CandidateValidation,type GenericCandidate} from './genericPowerBI';
import {evaluateGuardrails,type GuardrailDecision} from './guardrail';
import {chunkDocuments,clearRagIndex,documents as defaultDocuments,retrieveKnowledge,type KnowledgeDocument,type RagRetrieval} from './rag';
import {parseDataFile,summarizeDataStructure,type DataStructure} from './schemaIngestion';
import {defaultTenantSettings,type TenantSettings} from './tenant';

type View='create'|'runs'|'tenant'|'ai'|'knowledge'|'branding'|'guardrails';
type RequirementsSnapshot={kind:'RequirementsSnapshot';requirement:string;dataStructure:ReturnType<typeof summarizeDataStructure>;interpretation:RequirementInterpretation;questions:RequirementInterpretation['clarifications'];answers:Record<string,string>;confirmedAt:string};
type RunRecord={runId:string;timestamp:string;requirement:string;fileName:string;status:string;clarificationCount:number;model?:string;tokens?:number|null;latencyMs?:number};
type Trace={runId:string;startedAt:string;interpretation?:AIMetrics;clarificationCount:number;embeddingCalls:number;documentCount:number;chunkCount:number;retrievalLatencyMs?:number;topK:string[];design?:AIMetrics;citations:string[];guardrails:GuardrailDecision['evaluations'];compiler?:string;validation?:string;finalStatus:string};
const nav:Array<{group:string;items:Array<[View,string]>}>=[{group:'Workspace',items:[['create','Create Report'],['runs','My Runs']]},{group:'Administration',items:[['tenant','Tenant Settings'],['ai','AI & Models'],['knowledge','Governed Knowledge'],['branding','Branding & Report Standards'],['guardrails','Guardrails & Generation']]}];
const outcomeLabel=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());
export const deploymentGuideEligible=(candidate:GenericCandidate|null,design:ReportDesign|null,validation:CandidateValidation|null,decision:GuardrailDecision|null)=>Boolean(candidate&&design&&validation?.status==='PASS'&&decision?.generation==='AVAILABLE');

export function EnterpriseApp(){
  const [view,setView]=useState<View>('create');const [tenant,setTenant]=useState<TenantSettings>(structuredClone(defaultTenantSettings));const [service,setService]=useState<FoundryStatus|null>(null);const [knowledgeDocuments,setKnowledgeDocuments]=useState<KnowledgeDocument[]>(defaultDocuments);const [lastIndexed,setLastIndexed]=useState('Not indexed in this session');const [runs,setRuns]=useState<RunRecord[]>([]);
  useEffect(()=>{void foundryStatus().then(setService).catch(()=>setService(null))},[]);
  return <div className="app-shell"><aside className="side-nav"><div className="brand"><span className="brand-mark">A</span><div><strong>APBRA</strong><small>Power BI automation</small></div></div>{nav.map(section=><nav key={section.group} aria-label={section.group}><p>{section.group}</p>{section.items.map(([id,label])=><button key={id} className={view===id?'nav-active':''} onClick={()=>setView(id)}>{label}</button>)}</nav>)}</aside><div className="app-main"><header className="top-bar"><div><strong>{tenant.organisation.displayName}</strong><span>{view==='create'?'Report generation':view==='runs'?'Run history':'Administration'}</span></div><span className={`status-pill ${service?.configured?'status-good':'status-bad'}`}>{service?.configured?'AI connected':'AI unavailable'}</span></header>{view==='create'&&<CreateReport tenant={tenant} documents={knowledgeDocuments} onIndexed={()=>setLastIndexed(new Date().toLocaleString())} onRun={run=>setRuns(current=>[run,...current])}/>} {view==='runs'&&<MyRuns runs={runs}/>} {view==='tenant'&&<TenantSettingsPage value={tenant} onChange={setTenant}/>} {view==='ai'&&<AIModelsPage service={service} tenant={tenant}/>} {view==='knowledge'&&<KnowledgePage documents={knowledgeDocuments} lastIndexed={lastIndexed} onChange={setKnowledgeDocuments} onReindex={()=>{clearRagIndex();setLastIndexed('Index cleared; it will rebuild on the next report run.')}}/>} {view==='branding'&&<BrandingPage value={tenant} onChange={setTenant}/>} {view==='guardrails'&&<GuardrailsPage value={tenant} onChange={setTenant}/>}</div></div>
}

function CreateReport({tenant,documents,onIndexed,onRun}:{tenant:TenantSettings;documents:KnowledgeDocument[];onIndexed:()=>void;onRun:(run:RunRecord)=>void}){
  const [requirement,setRequirement]=useState('');const [data,setData]=useState<DataStructure|null>(null);const [fileError,setFileError]=useState('');const [interpretation,setInterpretation]=useState<RequirementInterpretation|null>(null);const [interpretMetrics,setInterpretMetrics]=useState<AIMetrics|null>(null);const [answers,setAnswers]=useState<Record<string,string>>({});const [snapshot,setSnapshot]=useState<RequirementsSnapshot|null>(null);const [retrieval,setRetrieval]=useState<RagRetrieval|null>(null);const [design,setDesign]=useState<ReportDesign|null>(null);const [designMetrics,setDesignMetrics]=useState<AIMetrics|null>(null);const [guardrails,setGuardrails]=useState<GuardrailDecision|null>(null);const [candidate,setCandidate]=useState<GenericCandidate|null>(null);const [validation,setValidation]=useState<CandidateValidation|null>(null);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [trace,setTrace]=useState<Trace|null>(null);
  const download=useMemo(()=>candidate?URL.createObjectURL(new Blob([zipFiles(candidate.files)],{type:'application/zip'})):null,[candidate]);useEffect(()=>()=>{if(download)URL.revokeObjectURL(download)},[download]);
  const [guideDownload,setGuideDownload]=useState<{url:string;filename:string}|null>(null);useEffect(()=>{let active=true,url:string|undefined;if(!data||!interpretation||!design||!guardrails||!candidate||!validation||!trace||!deploymentGuideEligible(candidate,design,validation,guardrails)){setGuideDownload(null);return()=>{active=false}}void import('./deploymentGuide').then(({generateDeploymentGuide})=>generateDeploymentGuide({run:{id:trace.runId,generatedAt:trace.startedAt,applicationVersion:candidate.generatorVersion},interpretation,data,design,tenant,policy:guardrails,candidate,validation})).then(guide=>{if(!active)return;url=URL.createObjectURL(new Blob([guide.bytes],{type:'application/pdf'}));setGuideDownload({url,filename:guide.filename})}).catch(()=>{if(active)setGuideDownload(null)});return()=>{active=false;if(url)URL.revokeObjectURL(url)}},[data,interpretation,design,tenant,guardrails,candidate,validation,trace]);
  const resetDownstream=()=>{setInterpretation(null);setInterpretMetrics(null);setAnswers({});setSnapshot(null);setRetrieval(null);setDesign(null);setDesignMetrics(null);setGuardrails(null);setCandidate(null);setValidation(null);setError('');setTrace(null)};
  async function upload(file:File|undefined){if(!file)return;setFileError('');resetDownstream();try{setData(await parseDataFile(file))}catch(reason){setData(null);setFileError(reason instanceof Error?reason.message:'Unable to parse file')}}
  async function analyse(){if(!data||!requirement.trim())return;resetDownstream();setBusy('Analysing requirement');const runId=crypto.randomUUID();const startedAt=new Date().toISOString();try{const result=await interpretRequirement(requirement,summarizeDataStructure(data),tenant);setInterpretation(result.value);setInterpretMetrics(result.metrics);setTrace({runId,startedAt,interpretation:result.metrics,clarificationCount:result.value.clarifications.length,embeddingCalls:0,documentCount:documents.length,chunkCount:0,topK:[],citations:[],guardrails:[],finalStatus:'Clarification required'});if(result.value.request_kind==='OUT_OF_SCOPE'){const decision=evaluateGuardrails(result.value,null,data,tenant);setGuardrails(decision);setTrace(current=>current?{...current,guardrails:decision.evaluations,finalStatus:decision.outcome}:current);onRun({runId,timestamp:startedAt,requirement,fileName:data.fileName,status:decision.outcome,clarificationCount:result.value.clarifications.length,model:result.metrics.model,tokens:result.metrics.totalTokens,latencyMs:result.metrics.latencyMs})}}catch(reason){setError('AI service unavailable. Requirement analysis did not complete and no fallback was used.');setTrace(current=>current?{...current,finalStatus:'AI service unavailable'}:current)}finally{setBusy('')}}
  const requiredComplete=Boolean(interpretation&&interpretation.clarifications.filter(item=>item.required).every(item=>answers[item.id]?.trim()));
  async function confirmAndContinue(){if(!data||!interpretation||!requiredComplete||!trace)return;const confirmed:RequirementsSnapshot={kind:'RequirementsSnapshot',requirement,dataStructure:summarizeDataStructure(data),interpretation,questions:interpretation.clarifications,answers:structuredClone(answers),confirmedAt:new Date().toISOString()};setSnapshot(confirmed);setBusy('Applying organisational standards');setError('');try{const query=[interpretation.objective,...interpretation.businessQuestions,...interpretation.kpis,...interpretation.dimensions,...Object.values(answers)].join('\n');const rag=await retrieveKnowledge(query,tenant.rag.topK,undefined,documents);setRetrieval(rag);onIndexed();const result=await generateGroundedReportDesign(confirmed,summarizeDataStructure(data),tenant,rag.retrieved.map(item=>({citation:item.citation,text:item.text})));setDesign(result.value);setDesignMetrics(result.metrics);const decision=evaluateGuardrails(interpretation,result.value,data,tenant);setGuardrails(decision);let compiled:GenericCandidate|null=null,checked:CandidateValidation|null=null,compiler='Not started';if(decision.generation==='AVAILABLE'&&tenant.generation.enabled){compiled=compilePowerBI(result.value,data,tenant);checked=validateGenericCandidate(compiled,result.value,data);setCandidate(compiled);setValidation(checked);compiler='Completed'}const finalStatus=decision.generation==='NOT_STARTED'?decision.outcome:checked?.status==='PASS'?'Candidate ready':'Validation failed';setTrace(current=>current?{...current,embeddingCalls:2,chunkCount:rag.chunksIndexed,retrievalLatencyMs:rag.indexMetrics.latencyMs+rag.queryMetrics.latencyMs,topK:rag.retrieved.map(item=>item.citation),design:result.metrics,citations:result.value.standardsApplied.map(item=>item.citation),guardrails:decision.evaluations,compiler,validation:checked?.status,finalStatus}:current);onRun({runId:trace.runId,timestamp:trace.startedAt,requirement,fileName:data.fileName,status:finalStatus,clarificationCount:interpretation.clarifications.length,model:result.metrics.model,tokens:(interpretMetrics?.totalTokens??0)+(result.metrics.totalTokens??0),latencyMs:(interpretMetrics?.latencyMs??0)+rag.indexMetrics.latencyMs+rag.queryMetrics.latencyMs+result.metrics.latencyMs})}catch(reason){setError(reason instanceof Error?reason.message:'Report design failed');setTrace(current=>current?{...current,finalStatus:'Failed'}:current)}finally{setBusy('')}}
  return <main className="content"><div className="page-heading"><div><h1>Create Power BI Report</h1><p>Describe the business outcome and provide a synthetic data structure. Organisational configuration and standards are applied automatically.</p></div><button className="subtle" onClick={()=>{setRequirement('');setData(null);resetDownstream()}}>New report</button></div>
    <section className="panel"><h2>1. Describe what you need</h2><label htmlFor="requirement">Report requirement</label><textarea id="requirement" rows={6} value={requirement} placeholder="Describe the business questions, measures, audience, filters and views you need." onChange={event=>{setRequirement(event.target.value);resetDownstream()}}/><h2>2. Provide your data structure</h2><p className="muted">Upload synthetic CSV or XLSX data only. Parsing stays local; only the detected structure and limited sample values are sent for design.</p><div className="upload-row"><label className="upload-button">Upload Excel<input type="file" accept=".xlsx" onChange={event=>void upload(event.target.files?.[0])}/></label><label className="upload-button">Upload CSV<input type="file" accept=".csv,text/csv" onChange={event=>void upload(event.target.files?.[0])}/></label></div>{fileError&&<p role="alert" className="error-box">{fileError}</p>}{data&&<DataStructurePanel data={data}/>}<div className="command-bar"><button disabled={!data||!requirement.trim()||!!busy||!!interpretation} onClick={()=>void analyse()}>{busy==='Analysing requirement'?'Analysing…':'Analyse Requirement'}</button></div></section>
    {interpretation&&interpretation.request_kind==='POWER_BI_REPORT'&&<section className="panel"><h2>Clarify the requirement</h2><p className="muted">These questions were generated from your requirement and detected data structure.</p>{interpretation.clarifications.length===0&&<p>No material clarification is required.</p>}{interpretation.clarifications.map((item,index)=><div className="form-block" key={item.id}><label htmlFor={`clarification-${index}`}>{item.question}{item.required&&' *'}</label><p className="field-help">{item.reason}</p><textarea id={`clarification-${index}`} rows={2} value={answers[item.id]??''} onChange={event=>setAnswers({...answers,[item.id]:event.target.value})}/></div>)}<h3>Requirements Summary</h3><Summary interpretation={interpretation} answers={answers}/><div className="command-bar"><button className="subtle" onClick={()=>{setInterpretation(null);setAnswers({})}}>Edit</button><button disabled={!requiredComplete||!!busy||!!snapshot} onClick={()=>void confirmAndContinue()}>{busy?'Applying standards…':'Confirm & Continue'}</button></div></section>}
    {busy==='Applying organisational standards'&&<section className="panel progress-panel"><span className="spinner"/>Applying organisational standards and generating the report design…</section>}
    {retrieval&&<section className="panel"><div className="section-title"><div><h2>Organisational Standards Applied</h2><p>{retrieval.retrieved.length} relevant governed-knowledge sections informed this design.</p></div><span className="status-pill status-good">Applied</span></div><div className="standards-grid">{retrieval.retrieved.map(item=><article key={item.chunkId}><strong>{item.heading}</strong><p>{item.text.split('\n').slice(1).join(' ').slice(0,220)}{item.text.length>220?'…':''}</p><small>{item.source} · v{item.version}</small></article>)}</div><details><summary>Technical retrieval evidence</summary><pre>{JSON.stringify(retrieval,null,2)}</pre></details></section>}
    {design&&<ReportDesignPanel design={design}/>} {guardrails&&<PolicyPanel decision={guardrails}/>} {candidate&&validation&&<section className="panel"><div className="section-title"><div><h2>{validation.status==='PASS'?'Power BI candidate ready':'Candidate validation failed'}</h2><p>{candidate.projectName}.pbip · {Object.keys(candidate.files).length} generated files</p></div><span className={`status-pill ${validation.status==='PASS'?'status-good':'status-bad'}`}>{validation.status}</span></div>{validation.status==='PASS'&&download&&<div className="command-bar"><a className="primary-link" href={download} download={`${candidate.projectName}.candidate.zip`}>Download PBIP candidate</a>{guideDownload&&<a className="primary-link" href={guideDownload.url} download={guideDownload.filename}>Download deployment guide (PDF)</a>}</div>}<details><summary>Validation evidence</summary><pre>{JSON.stringify(validation,null,2)}</pre></details><p className="muted">Power BI Desktop remains the final runtime proof.</p></section>}
    {guardrails&&guardrails.generation==='NOT_STARTED'&&<ReviewPanel decision={guardrails}/>}
    {error&&<section className="panel error-box" role="alert"><strong>Unable to complete this stage</strong><p>{error}</p></section>} {trace&&<details className="panel"><summary>Technical run evidence</summary><pre>{JSON.stringify(trace,null,2)}</pre></details>}
  </main>
}

function DataStructurePanel({data}:{data:DataStructure}){return <details className="data-card" open><summary>Data Structure Detected · {data.tables.length} table{data.tables.length===1?'':'s'}</summary>{data.tables.map(table=><div key={table.name}><h3>{table.sourceName}</h3><p>{table.rowCount} rows · {table.columns.length} columns</p><table><thead><tr><th>Column</th><th>Type</th><th>Sample</th></tr></thead><tbody>{table.columns.map(column=><tr key={column.name}><td>{column.sourceName}</td><td>{column.type}</td><td>{column.sampleValues.join(', ')||'—'}</td></tr>)}</tbody></table></div>)}{data.relationships.length>0&&<p>{data.relationships.length} relationship{data.relationships.length===1?'':'s'} inferred from matching keys and cardinality.</p>}</details>}
function Summary({interpretation,answers}:{interpretation:RequirementInterpretation;answers:Record<string,string>}){return <div className="summary-grid"><div><span>Objective</span><p>{interpretation.objective}</p></div><div><span>Audience</span><p>{interpretation.audience||'To be confirmed'}</p></div><div><span>KPIs</span><p>{interpretation.kpis.join(', ')||'None identified'}</p></div><div><span>Views</span><p>{interpretation.pages.join(', ')||'To be designed'}</p></div>{Object.entries(answers).map(([id,value])=><div key={id}><span>Confirmed answer</span><p>{value}</p></div>)}</div>}
function ReportDesignPanel({design}:{design:ReportDesign}){return <section className="panel"><div className="section-title"><div><h2>Report Design</h2><p>{design.overview}</p></div><span className="status-pill status-good">Grounded</span></div><div className="design-grid"><article><h3>Data model</h3><p>Facts: {design.dataModel.factTables.join(', ')||'—'}</p><p>Dimensions: {design.dataModel.dimensionTables.join(', ')||'—'}</p><p>{design.dataModel.relationships.length} relationships</p></article><article><h3>Measures and KPIs</h3><ul>{design.measures.map(item=><li key={item.id}>{item.name} · {item.aggregation}</li>)}</ul></article><article><h3>Pages and visuals</h3>{design.pages.map(page=><p key={page.id}><strong>{page.name}</strong> · {page.visuals.map(item=>item.title).join(', ')}</p>)}</article><article><h3>Branding and accessibility</h3><p>{design.branding.themeName}</p><ul>{design.accessibility.map(item=><li key={item}>{item}</li>)}</ul></article><article><h3>Standards applied</h3><ul>{design.standardsApplied.map(item=><li key={item.citation}>{item.decision}<br/><small>{item.citation}</small></li>)}</ul></article><article><h3>Assumptions and warnings</h3><ul>{[...design.assumptions,...design.warnings].map(item=><li key={item}>{item}</li>)}</ul></article></div><details><summary>Technical Report Design contract</summary><pre>{JSON.stringify(design,null,2)}</pre></details></section>}
function PolicyPanel({decision}:{decision:GuardrailDecision}){return <section className="panel"><div className="section-title"><div><h2>Policy evaluation</h2><p>Tenant-wide deterministic policies evaluated the structured design.</p></div><span className={`status-pill ${decision.outcome==='PASS'||decision.outcome==='WARNING'?'status-good':'status-bad'}`}>{outcomeLabel(decision.outcome)}</span></div><table><thead><tr><th>Rule</th><th>Category</th><th>Result</th><th>Reason</th></tr></thead><tbody>{decision.evaluations.map(item=><tr key={item.ruleId}><td>{item.ruleId}</td><td>{item.category}</td><td>{outcomeLabel(item.result)}</td><td>{item.reason}</td></tr>)}</tbody></table></section>}
export function ReviewPanel({decision}:{decision:GuardrailDecision}){return <section className="panel review-panel"><h2>{decision.outcome==='OUT_OF_SCOPE'?'Outside report-generation scope':'Human Review Required'}</h2><p>Generation status: <strong>Not started</strong></p>{decision.evaluations.filter(item=>item.result!=='PASS').map(item=><article key={item.ruleId}><strong>{item.ruleId} · {outcomeLabel(item.result)}</strong><p>{item.reason}</p><p>Recommendation: {item.recommendedAction}</p></article>)}</section>}
function MyRuns({runs}:{runs:RunRecord[]}){return <main className="content"><div className="page-heading"><div><h1>My Runs</h1><p>Report-generation activity from this local browser session.</p></div></div><section className="panel">{runs.length===0?<div className="empty-state"><h2>No runs yet</h2><p>Completed and review-required report runs will appear here.</p></div>:<table><thead><tr><th>Run</th><th>Requirement</th><th>Data</th><th>Status</th><th>Started</th></tr></thead><tbody>{runs.map(run=><tr key={run.runId}><td><code>{run.runId.slice(0,8)}</code></td><td>{run.requirement.slice(0,80)}</td><td>{run.fileName}</td><td>{outcomeLabel(run.status)}</td><td>{new Date(run.timestamp).toLocaleString()}</td></tr>)}</tbody></table>}</section></main>}
function TenantSettingsPage({value,onChange}:{value:TenantSettings;onChange:(value:TenantSettings)=>void}){const update=(key:keyof TenantSettings['organisation'],next:string)=>onChange({...value,organisation:{...value.organisation,[key]:next}});return <AdminPage title="Tenant Settings" description="Organisation-wide configuration reused across report-generation requests."><div className="form-grid"><Field label="Organisation name" value={value.organisation.name} onChange={next=>update('name',next)}/><Field label="Tenant display name" value={value.organisation.displayName} onChange={next=>update('displayName',next)}/><Field label="Locale" value={value.organisation.locale} onChange={next=>update('locale',next)}/><Field label="Timezone" value={value.organisation.timezone} onChange={next=>update('timezone',next)}/></div><SettingsTable value={value}/></AdminPage>}
function AIModelsPage({service,tenant}:{service:FoundryStatus|null;tenant:TenantSettings}){return <AdminPage title="AI & Models" description="Server-controlled provider configuration. Secrets are never returned to the browser."><dl className="properties"><dt>Provider</dt><dd>{tenant.ai.provider} / Azure OpenAI-compatible endpoint</dd><dt>Status</dt><dd><span className={`status-pill ${service?.configured?'status-good':'status-bad'}`}>{service?.configured?'Connected':'Unavailable'}</span></dd><dt>Chat deployment</dt><dd>{service?.chatDeployment||'Unavailable'}</dd><dt>Embedding deployment</dt><dd>{service?.embeddingDeployment||'Unavailable'}</dd><dt>Endpoint</dt><dd>{service?.endpointDisplay||'Unavailable'}</dd><dt>Authentication</dt><dd>{service?.authentication||tenant.ai.authentication}</dd></dl><div className="info-box">API secrets remain in the server environment. Production should use managed configuration and secret services.</div></AdminPage>}
function KnowledgePage({documents,lastIndexed,onChange,onReindex}:{documents:KnowledgeDocument[];lastIndexed:string;onChange:(value:KnowledgeDocument[])=>void;onReindex:()=>void}){async function add(file:File|undefined){if(!file)return;const content=await file.text();const source=file.name.replace(/[^A-Za-z0-9_.-]/g,'_');const prefix=source.split(/[-_.]/).filter(Boolean).slice(0,2).map(item=>item[0]?.toUpperCase()).join('').padEnd(2,'X');const next={source,version:new Date().toISOString().slice(0,10),prefix,content};onChange([...documents.filter(item=>item.source!==source),next]);clearRagIndex()}return <AdminPage title="Governed Knowledge" description="Tenant administrators establish the organisational corpus consumed automatically by every report run."><div className="command-bar"><label className="upload-button">Add or replace document<input type="file" accept=".md,text/markdown,text/plain" onChange={event=>void add(event.target.files?.[0])}/></label><button className="subtle" onClick={onReindex}>Re-index</button></div><table><thead><tr><th>Document</th><th>Category</th><th>Version</th><th>Status</th><th>Last indexed</th><th>Chunks</th></tr></thead><tbody>{documents.map(document=><tr key={document.source}><td>{document.source}</td><td>{document.source.replace(/[-_]/g,' ').replace(/\.md$/,'')}</td><td>{document.version}</td><td><span className="status-pill status-good">Approved</span></td><td>{lastIndexed}</td><td>{chunkDocuments([document]).length}</td></tr>)}</tbody></table><details><summary>Chunking architecture</summary><p>Level-two headings define semantic boundaries. Sections under 600 estimated tokens remain intact. Longer sections use an approximately 500-token target with about 50 tokens of overlap only where continuity requires splitting. Each chunk retains document, version, heading, chunk ID, character size, token estimate, and content.</p></details></AdminPage>}
function BrandingPage({value,onChange}:{value:TenantSettings;onChange:(value:TenantSettings)=>void}){const update=(key:keyof TenantSettings['branding'],next:string)=>onChange({...value,branding:{...value.branding,[key]:next}});return <AdminPage title="Branding & Report Standards" description="Organisation-wide presentation settings applied to generated Report Designs and supported PBIP output."><div className="form-grid"><Field label="Organisation name" value={value.organisation.name} onChange={next=>onChange({...value,organisation:{...value.organisation,name:next}})}/><Field label="Theme name" value={value.branding.themeName} onChange={next=>update('themeName',next)}/><Field label="Primary colour" value={value.branding.primary} type="color" onChange={next=>update('primary',next)}/><Field label="Accent colour" value={value.branding.accent} type="color" onChange={next=>update('accent',next)}/><Field label="Report naming convention" value={value.branding.reportNaming} onChange={next=>update('reportNaming',next)}/><Field label="Page naming convention" value={value.branding.pageNaming} onChange={next=>update('pageNaming',next)}/><Field label="Executive report convention" value={value.branding.executiveConvention} onChange={next=>update('executiveConvention',next)}/></div><div className="info-box">Logo and full theme-JSON asset management are represented as future production controls; colours and naming settings are active in this prototype.</div></AdminPage>}
function GuardrailsPage({value,onChange}:{value:TenantSettings;onChange:(value:TenantSettings)=>void}){const governance=value.governance;const update=(key:keyof typeof governance,next:number|boolean)=>onChange({...value,governance:{...governance,[key]:next}});return <AdminPage title="Guardrails & Generation" description="Deterministic tenant policies govern scope, complexity, accessibility, schema quality, and compiler eligibility."><div className="form-grid"><NumberField label="Maximum visuals per page" value={governance.maxVisualsPerPage} onChange={next=>update('maxVisualsPerPage',next)}/><NumberField label="Human review threshold" value={governance.humanReviewAtVisuals} onChange={next=>update('humanReviewAtVisuals',next)}/><NumberField label="Maximum pages" value={governance.maxPages} onChange={next=>update('maxPages',next)}/><Toggle label="Require governed knowledge" checked={governance.requireKnowledge} onChange={next=>update('requireKnowledge',next)}/><Toggle label="Require accessibility checks" checked={governance.requireAccessibility} onChange={next=>update('requireAccessibility',next)}/><Toggle label="Require deterministic validation" checked={governance.requireValidation} onChange={next=>update('requireValidation',next)}/><Toggle label="PBIP generation enabled" checked={value.generation.enabled} onChange={enabled=>onChange({...value,generation:{...value.generation,enabled}})}/></div><h2>Supported generation capabilities</h2><ul>{value.generation.supportedCapabilities.map(item=><li key={item}>{item}</li>)}</ul></AdminPage>}
function SettingsTable({value}:{value:TenantSettings}){return <table><thead><tr><th>Area</th><th>Setting</th><th>Value</th></tr></thead><tbody><tr><td>AI</td><td>Provider</td><td>{value.ai.provider}</td></tr><tr><td>RAG</td><td>Retrieval</td><td>{value.rag.enabled?'Enabled':'Disabled'} · top {value.rag.topK}</td></tr><tr><td>RAG</td><td>Chunking</td><td>{value.rag.strategy} · target {value.rag.chunkTargetTokens} tokens</td></tr><tr><td>RAG</td><td>Vector index</td><td>{value.rag.indexType}</td></tr><tr><td>Governance</td><td>Validation</td><td>{value.governance.requireValidation?'Required':'Optional'}</td></tr><tr><td>Generation</td><td>Policy</td><td>{value.generation.policy}</td></tr></tbody></table>}
function AdminPage({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <main className="content"><div className="page-heading"><div><h1>{title}</h1><p>{description}</p></div></div><section className="panel">{children}</section></main>}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label>{label}<input type={type} value={value} onChange={event=>onChange(event.target.value)}/></label>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label>{label}<input type="number" min="1" value={value} onChange={event=>onChange(Number(event.target.value))}/></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="toggle"><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><span>{label}</span></label>}
