import type {TenantSettings} from './tenant';

export type AIMetrics={model:string;latencyMs:number;promptTokens:number|null;completionTokens:number|null;totalTokens:number|null};
export type AIResult<T>={value:T;metrics:AIMetrics};
export type FoundryStatus={configured:boolean;chatDeployment:string;embeddingDeployment:string;apiMode:string;endpointDisplay?:string;authentication?:string};
export type Clarification={id:string;category:'METRIC_DEFINITION'|'TIME_COMPARISON'|'SECURITY'|'AUDIENCE'|'PAGE_SCOPE'|'FILTER_SCOPE'|'OTHER';question:string;reason:string;required:boolean};
export type RequirementInterpretation={request_kind:'POWER_BI_REPORT'|'OUT_OF_SCOPE';objective:string;businessQuestions:string[];kpis:string[];dimensions:string[];filters:string[];audience:string;pages:string[];assumptions:string[];ambiguities:string[];clarifications:Clarification[]};
export type MeasureDesign={id:string;name:string;businessDefinition:string;aggregation:'SUM'|'DISTINCTCOUNT'|'COUNT'|'AVERAGE'|'RATIO';field:string;numeratorMeasureId:string;denominatorMeasureId:string;format:'currency'|'integer'|'decimal'|'percentage'};
export type VisualDesign={id:string;type:'card'|'bar'|'column'|'line'|'table'|'slicer';title:string;categoryField:string;measureIds:string[];fields:string[];altText:string};
export type ReportDesign={artifact_kind:'ReportDesign';schema_version:1;projectName:string;overview:string;audience:string;dataModel:{factTables:string[];dimensionTables:string[];relationships:Array<{fromTable:string;fromColumn:string;toTable:string;toColumn:string}>};measures:MeasureDesign[];pages:Array<{id:string;name:string;purpose:string;visuals:VisualDesign[]}>;filters:string[];branding:{themeName:string;primary:string;accent:string};accessibility:string[];standardsApplied:Array<{citation:string;decision:string}>;assumptions:string[];warnings:string[];generationRequirements:string[]};

const stringArray={type:'array',items:{type:'string'}};
export const interpretationSchema={type:'object',additionalProperties:false,required:['request_kind','objective','businessQuestions','kpis','dimensions','filters','audience','pages','assumptions','ambiguities','clarifications'],properties:{request_kind:{type:'string',enum:['POWER_BI_REPORT','OUT_OF_SCOPE']},objective:{type:'string'},businessQuestions:stringArray,kpis:stringArray,dimensions:stringArray,filters:stringArray,audience:{type:'string'},pages:stringArray,assumptions:stringArray,ambiguities:stringArray,clarifications:{type:'array',items:{type:'object',additionalProperties:false,required:['id','category','question','reason','required'],properties:{id:{type:'string'},category:{type:'string',enum:['METRIC_DEFINITION','TIME_COMPARISON','SECURITY','AUDIENCE','PAGE_SCOPE','FILTER_SCOPE','OTHER']},question:{type:'string'},reason:{type:'string'},required:{type:'boolean'}}}}}};
const relationshipSchema={type:'object',additionalProperties:false,required:['fromTable','fromColumn','toTable','toColumn'],properties:{fromTable:{type:'string'},fromColumn:{type:'string'},toTable:{type:'string'},toColumn:{type:'string'}}};
const measureSchema={type:'object',additionalProperties:false,required:['id','name','businessDefinition','aggregation','field','numeratorMeasureId','denominatorMeasureId','format'],properties:{id:{type:'string'},name:{type:'string'},businessDefinition:{type:'string'},aggregation:{type:'string',enum:['SUM','DISTINCTCOUNT','COUNT','AVERAGE','RATIO']},field:{type:'string'},numeratorMeasureId:{type:'string'},denominatorMeasureId:{type:'string'},format:{type:'string',enum:['currency','integer','decimal','percentage']}}};
const visualSchema={type:'object',additionalProperties:false,required:['id','type','title','categoryField','measureIds','fields','altText'],properties:{id:{type:'string'},type:{type:'string',enum:['card','bar','column','line','table','slicer']},title:{type:'string'},categoryField:{type:'string'},measureIds:stringArray,fields:stringArray,altText:{type:'string'}}};
export const reportDesignSchema={type:'object',additionalProperties:false,required:['artifact_kind','schema_version','projectName','overview','audience','dataModel','measures','pages','filters','branding','accessibility','standardsApplied','assumptions','warnings','generationRequirements'],properties:{artifact_kind:{type:'string',enum:['ReportDesign']},schema_version:{type:'integer',enum:[1]},projectName:{type:'string'},overview:{type:'string'},audience:{type:'string'},dataModel:{type:'object',additionalProperties:false,required:['factTables','dimensionTables','relationships'],properties:{factTables:stringArray,dimensionTables:stringArray,relationships:{type:'array',items:relationshipSchema}}},measures:{type:'array',items:measureSchema},pages:{type:'array',items:{type:'object',additionalProperties:false,required:['id','name','purpose','visuals'],properties:{id:{type:'string'},name:{type:'string'},purpose:{type:'string'},visuals:{type:'array',items:visualSchema}}}},filters:stringArray,branding:{type:'object',additionalProperties:false,required:['themeName','primary','accent'],properties:{themeName:{type:'string'},primary:{type:'string'},accent:{type:'string'}}},accessibility:stringArray,standardsApplied:{type:'array',items:{type:'object',additionalProperties:false,required:['citation','decision'],properties:{citation:{type:'string'},decision:{type:'string'}}}},assumptions:stringArray,warnings:stringArray,generationRequirements:stringArray}};

function record(value:unknown){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('AI_RESPONSE_INVALID');return value as Record<string,unknown>}
function strings(value:unknown){if(!Array.isArray(value)||!value.every(item=>typeof item==='string'))throw new Error('AI_RESPONSE_INVALID');return value as string[]}
export function validateInterpretation(value:unknown):RequirementInterpretation{const v=record(value);if(!['POWER_BI_REPORT','OUT_OF_SCOPE'].includes(String(v.request_kind))||typeof v.objective!=='string'||typeof v.audience!=='string')throw new Error('AI_RESPONSE_INVALID');const clarifications=(Array.isArray(v.clarifications)?v.clarifications:[]).map(item=>{const q=record(item);if(typeof q.id!=='string'||typeof q.question!=='string'||typeof q.reason!=='string'||typeof q.required!=='boolean'||!['METRIC_DEFINITION','TIME_COMPARISON','SECURITY','AUDIENCE','PAGE_SCOPE','FILTER_SCOPE','OTHER'].includes(String(q.category)))throw new Error('AI_RESPONSE_INVALID');return q as unknown as Clarification});if(new Set(clarifications.map(q=>q.id)).size!==clarifications.length)return(()=>{throw new Error('AI_RESPONSE_INVALID')})();return{request_kind:v.request_kind as RequirementInterpretation['request_kind'],objective:v.objective,businessQuestions:strings(v.businessQuestions),kpis:strings(v.kpis),dimensions:strings(v.dimensions),filters:strings(v.filters),audience:v.audience,pages:strings(v.pages),assumptions:strings(v.assumptions),ambiguities:strings(v.ambiguities),clarifications}}
export function validateReportDesign(value:unknown,allowedCitations:readonly string[]):ReportDesign{const v=record(value);if(v.artifact_kind!=='ReportDesign'||v.schema_version!==1||typeof v.projectName!=='string'||!Array.isArray(v.pages)||!Array.isArray(v.measures))throw new Error('REPORT_DESIGN_INVALID');const citations=new Set(allowedCitations);const applied=Array.isArray(v.standardsApplied)?v.standardsApplied.map(record):[];if(!applied.length||applied.some(item=>typeof item.citation!=='string'||typeof item.decision!=='string'||!citations.has(item.citation)))throw new Error('REPORT_DESIGN_CITATION_INVALID');return v as unknown as ReportDesign}

async function post(path:string,body:unknown){const start=performance.now();let response:Response;try{response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}catch{throw new Error('AI_SERVICE_UNAVAILABLE')}const latencyMs=Math.round(performance.now()-start);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`AI_SERVICE_UNAVAILABLE: ${String(data?.error?.code??response.status)}`);return{data,latencyMs}}
export async function foundryStatus():Promise<FoundryStatus>{const response=await fetch('/api/ai/status');if(!response.ok)throw new Error('AI_SERVICE_UNAVAILABLE');return response.json()}
async function structured<T>(name:string,schema:unknown,messages:Array<{role:'system'|'user';content:string}>,validate:(value:unknown)=>T):Promise<AIResult<T>>{const{data,latencyMs}=await post('/api/ai/chat',{messages,response_format:{type:'json_schema',json_schema:{name,strict:true,schema}}});const content=data?.choices?.[0]?.message?.content;if(typeof content!=='string')throw new Error('AI_RESPONSE_INVALID');let parsed:unknown;try{parsed=JSON.parse(content)}catch{throw new Error('AI_RESPONSE_INVALID')}return{value:validate(parsed),metrics:{model:String(data.model??'configured deployment'),latencyMs,promptTokens:data.usage?.prompt_tokens??null,completionTokens:data.usage?.completion_tokens??null,totalTokens:data.usage?.total_tokens??null}}}
export async function interpretRequirement(prompt:string,schema:unknown,tenant:TenantSettings){const system='You are a Power BI solution architect. Classify whether the request is for a Power BI report. Interpret only the supplied request and request-specific schema. Return the required JSON. Derive at most five material clarification questions dynamically. Never treat tenant policy as user data, never invent fields, and never infer authorization. Mark unrelated requests OUT_OF_SCOPE. Questions about time comparison use TIME_COMPARISON; ambiguity between filters and access control uses SECURITY.';return structured('power_bi_requirement_interpretation',interpretationSchema,[{role:'system',content:system},{role:'user',content:JSON.stringify({requirement:prompt,dataStructure:schema,tenantConfiguration:{locale:tenant.organisation.locale,timezone:tenant.organisation.timezone,generationCapabilities:tenant.generation.supportedCapabilities}})}],validateInterpretation)}
export async function generateGroundedReportDesign(snapshot:unknown,schema:unknown,tenant:TenantSettings,chunks:Array<{citation:string;text:string}>){const allowed=chunks.map(chunk=>chunk.citation);const system='Create the required structured Power BI ReportDesign. It is an internal compiler contract. Use only exact table and column identifiers from the supplied request schema. Every non-empty field, categoryField, and filter must use the fully qualified Table.Column form; never return a display label or unqualified column name there. Use only supported visual and aggregation enum values. RATIO measures reference numerator and denominator measure IDs; other measures use field as Table.Column. Visual measureIds reference declared measure IDs, never measure names. Every customer-standard decision cites one supplied citation. Do not emit executable DAX, M, SQL, credentials, or unsupported fields. Put uncertainties in warnings.';return structured('grounded_power_bi_report_design',reportDesignSchema,[{role:'system',content:system},{role:'user',content:JSON.stringify({confirmedRequirements:snapshot,dataStructure:schema,tenantConfiguration:{organisation:tenant.organisation,branding:tenant.branding,generation:tenant.generation},retrievedStandards:chunks})}],value=>validateReportDesign(value,allowed))}
export async function embedTexts(input:string[]):Promise<AIResult<number[][]>>{const{data,latencyMs}=await post('/api/ai/embeddings',{input});const vectors=Array.isArray(data.data)?data.data.map((item:any)=>item.embedding):null;if(!vectors||vectors.length!==input.length||vectors.some((vector:unknown)=>!Array.isArray(vector)||!vector.every(item=>typeof item==='number')))throw new Error('EMBEDDING_RESPONSE_INVALID');return{value:vectors,metrics:{model:String(data.model??'configured deployment'),latencyMs,promptTokens:data.usage?.prompt_tokens??null,completionTokens:null,totalTokens:data.usage?.total_tokens??null}}}
