import {afterEach,expect,it,vi} from 'vitest';
import {generateGroundedReportDesign,inspectMeasureIntegrity,interpretRequirement,reportDesignSchema,validateInterpretation,validateReportDesign,type ReportDesign} from './foundry';
import {defaultTenantSettings} from './tenant';

const interpretation={request_kind:'POWER_BI_REPORT',objective:'Track sales',businessQuestions:['How much revenue?'],kpis:['Total Sales'],dimensions:['Region'],filters:['Sales.Region'],audience:'Executives',pages:['Executive Summary'],assumptions:[],ambiguities:['Sales definition'],clarifications:[{id:'sales-definition',category:'METRIC_DEFINITION',question:'How is sales defined?',reason:'The schema contains several monetary fields.',required:true}]};
afterEach(()=>vi.unstubAllGlobals());
it('validates structured interpretation and rejects malformed responses',()=>{
  expect(validateInterpretation(interpretation).clarifications[0].question).toContain('sales');
  expect(()=>validateInterpretation({...interpretation,kpis:'sales'})).toThrow('AI_RESPONSE_INVALID');
  expect(()=>validateInterpretation({...interpretation,clarifications:[interpretation.clarifications[0],interpretation.clarifications[0]]})).toThrow('AI_RESPONSE_INVALID');
});
const integrityDesign=():ReportDesign=>({artifact_kind:'ReportDesign',schema_version:1,projectName:'GenericReport',overview:'Generic',audience:'Leaders',dataModel:{factTables:['Facts'],dimensionTables:[],relationships:[]},measures:[{id:'all',name:'All records',businessDefinition:'All records',aggregation:'COUNT',field:'Facts.Id',numeratorMeasureId:'',denominatorMeasureId:'',format:'integer'},{id:'part',name:'Selected records',businessDefinition:'Selected records',aggregation:'FILTERED_COUNT',field:'Facts.Id',filterField:'Facts.Status',filterValue:'Open',numeratorMeasureId:'',denominatorMeasureId:'',format:'integer'},{id:'share',name:'Selected share',businessDefinition:'Selected records divided by all records',aggregation:'RATIO',field:'',numeratorMeasureId:'part',denominatorMeasureId:'all',format:'percentage'}],pages:[{id:'summary',name:'Summary',purpose:'Summary',visuals:[{id:'share-card',type:'card',title:'Selected share',categoryField:'',measureIds:['share'],fields:[],altText:'Selected share'}]}],filters:[],branding:{themeName:'Tenant',primary:'#000',accent:'#fff'},accessibility:[],standardsApplied:[{citation:'standard#1',decision:'Use a card'}],assumptions:[],warnings:[],generationRequirements:[]});
it('enforces canonical measure, operand, filtered-count, and visual reference integrity',()=>{const valid=integrityDesign();expect(inspectMeasureIntegrity(valid)).toEqual([]);const invalid=integrityDesign();invalid.measures.push({...invalid.measures[0]});invalid.measures[2].numeratorMeasureId='';invalid.pages[0].visuals[0].measureIds=['missing'];expect(inspectMeasureIntegrity(invalid).map(issue=>issue.code)).toEqual(expect.arrayContaining(['DUPLICATE_MEASURE_ID','DUPLICATE_MEASURE_NAME','MISSING_RATIO_OPERAND','UNRESOLVED_VISUAL_MEASURE']))});
it('rejects unresolved operands, self-reference, unsupported expressions, incomplete percentage totals, and invalid unused declarations',()=>{const value=integrityDesign();value.measures.push({id:'unused',name:'Unused invalid ratio',businessDefinition:'Invalid even when unused',aggregation:'RATIO',field:'',numeratorMeasureId:'unknown',denominatorMeasureId:'unused',format:'percentage'},{id:'pct',name:'Percent of total',businessDefinition:'Share',aggregation:'PERCENTAGE_OF_TOTAL',field:'',numeratorMeasureId:'part',denominatorMeasureId:'all',format:'percentage'},{id:'custom',name:'Custom expression',businessDefinition:'Unsupported',aggregation:'MEDIAN' as any,field:'Facts.Id',numeratorMeasureId:'',denominatorMeasureId:'',format:'decimal'});const issues=inspectMeasureIntegrity(value);expect(issues.map(issue=>issue.code)).toEqual(expect.arrayContaining(['UNRESOLVED_MEASURE_OPERAND','SELF_REFERENTIAL_MEASURE','INCOMPLETE_PERCENTAGE_OF_TOTAL','UNSUPPORTED_MEASURE_TYPE']))});
it('keeps every strict structured-output measure property required',()=>{const measure=(reportDesignSchema as any).properties.measures.items;expect(new Set(measure.required)).toEqual(new Set(Object.keys(measure.properties))) });
it('parses a real-shaped chat completion and retains measured usage',async()=>{
  vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({model:'gpt-4.1',choices:[{message:{content:JSON.stringify(interpretation)}}],usage:{prompt_tokens:120,completion_tokens:80,total_tokens:200}}),{status:200,headers:{'Content-Type':'application/json'}})));
  const result=await interpretRequirement('build a sales report',{},defaultTenantSettings);
  expect(result.value.objective).toBe('Track sales');expect(result.metrics).toMatchObject({model:'gpt-4.1',promptTokens:120,completionTokens:80,totalTokens:200});
});
it('fails closed when Foundry is unavailable or returns invalid JSON',async()=>{
  vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('offline')));await expect(interpretRequirement('x',{},defaultTenantSettings)).rejects.toThrow('AI_SERVICE_UNAVAILABLE');
  vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({choices:[{message:{content:'not-json'}}]}),{status:200})));await expect(interpretRequirement('x',{},defaultTenantSettings)).rejects.toThrow('AI_RESPONSE_INVALID');
});
it('requires grounded Report Design citations to come from retrieved chunks',async()=>{
  const plan={artifact_kind:'ReportDesign',schema_version:1,projectName:'SalesReport',overview:'Sales',audience:'Executives',dataModel:{factTables:['Sales'],dimensionTables:[],relationships:[]},measures:[],pages:[],filters:[],branding:{themeName:'Tenant',primary:'#005A9C',accent:'#2D7D9A'},accessibility:[],standardsApplied:[{citation:'local-knowledge:test.md@1#T-001',decision:'Use standard'}],assumptions:[],warnings:[],generationRequirements:[]};
  expect(validateReportDesign(plan,[plan.standardsApplied[0].citation])).toEqual(plan);expect(()=>validateReportDesign(plan,['other'])).toThrow('REPORT_DESIGN_CITATION_INVALID');
  vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({model:'gpt-4.1',choices:[{message:{content:JSON.stringify(plan)}}],usage:{total_tokens:50}}),{status:200})));
  expect((await generateGroundedReportDesign({}, {},defaultTenantSettings,[{citation:plan.standardsApplied[0].citation,text:'rule'}])).value.standardsApplied).toHaveLength(1);
});
