import {afterEach,expect,it,vi} from 'vitest';
import {generateGroundedReportDesign,inspectMeasureIntegrity,interpretRequirement,normalizeMeasureContracts,repairGroundedReportDesignLayout,reportDesignSchema,validateInterpretation,validateReportDesign,type ReportDesign} from './foundry';
import {defaultTenantSettings} from './tenant';

const interpretation={request_kind:'POWER_BI_REPORT',objective:'Track sales',businessQuestions:['How much revenue?'],kpis:['Total Sales'],dimensions:['Region'],filters:['Sales.Region'],audience:'Executives',pages:['Executive Summary'],assumptions:[],ambiguities:['Sales definition'],clarifications:[{id:'sales-definition',category:'METRIC_DEFINITION',question:'How is sales defined?',reason:'The schema contains several monetary fields.',required:true}]};
afterEach(()=>vi.unstubAllGlobals());
it('validates structured interpretation and rejects malformed responses',()=>{
  expect(validateInterpretation(interpretation).clarifications[0].question).toContain('sales');
  expect(()=>validateInterpretation({...interpretation,kpis:'sales'})).toThrow('AI_RESPONSE_INVALID');
  expect(()=>validateInterpretation({...interpretation,clarifications:[interpretation.clarifications[0],interpretation.clarifications[0]]})).toThrow('AI_RESPONSE_INVALID');
});
const integrityDesign=():ReportDesign=>({artifact_kind:'ReportDesign',schema_version:1,projectName:'GenericReport',overview:'Generic',audience:'Leaders',dataModel:{factTables:['Facts'],dimensionTables:[],relationships:[]},measures:[{id:'all',name:'All records',businessDefinition:'All records',aggregation:'COUNT',field:'Facts.Id',numeratorMeasureId:'',denominatorMeasureId:'',format:'integer'},{id:'part',name:'Selected records',businessDefinition:'Selected records',aggregation:'FILTERED_COUNT',field:'Facts.Id',filterField:'Facts.Status',filterValue:'Open',numeratorMeasureId:'',denominatorMeasureId:'',format:'integer'},{id:'share',name:'Selected share',businessDefinition:'Selected records divided by all records',aggregation:'RATIO',field:'',numeratorMeasureId:'part',denominatorMeasureId:'all',format:'percentage'}],pages:[{id:'summary',name:'Summary',purpose:'Summary',visuals:[{id:'share-card',type:'card',title:'Selected share',categoryField:'',measureIds:['share'],fields:[],altText:'Selected share'}]}],filters:[],branding:{themeName:'Tenant',primary:'#000',accent:'#fff'},accessibility:[],standardsApplied:[{citation:'standard#1',decision:'Use a card'}],assumptions:[],warnings:[],generationRequirements:[]});
const requestSchema={tables:[{name:'Facts',columns:[{name:'Id'},{name:'Status'},{name:'Date'}]}]};
it('enforces canonical measure, operand, filtered-count, and visual reference integrity',()=>{const valid=integrityDesign();expect(inspectMeasureIntegrity(valid)).toEqual([]);const invalid=integrityDesign();invalid.measures.push({...invalid.measures[0]});invalid.measures[2].numeratorMeasureId='';invalid.pages[0].visuals[0].measureIds=['missing'];expect(inspectMeasureIntegrity(invalid).map(issue=>issue.code)).toEqual(expect.arrayContaining(['DUPLICATE_MEASURE_ID','DUPLICATE_MEASURE_NAME','MISSING_RATIO_OPERAND','UNRESOLVED_VISUAL_MEASURE']))});
it('rejects unresolved operands, self-reference, unsupported expressions, incomplete percentage totals, and invalid unused declarations',()=>{const value=integrityDesign();value.measures.push({id:'unused',name:'Unused invalid ratio',businessDefinition:'Invalid even when unused',aggregation:'RATIO',field:'',numeratorMeasureId:'unknown',denominatorMeasureId:'unused',format:'percentage'},{id:'pct',name:'Percent of total',businessDefinition:'Share',aggregation:'PERCENTAGE_OF_TOTAL',field:'',numeratorMeasureId:'part',denominatorMeasureId:'all',format:'percentage'},{id:'custom',name:'Custom expression',businessDefinition:'Unsupported',aggregation:'MEDIAN' as any,field:'Facts.Id',numeratorMeasureId:'',denominatorMeasureId:'',format:'decimal'});const issues=inspectMeasureIntegrity(value);expect(issues.map(issue=>issue.code)).toEqual(expect.arrayContaining(['UNRESOLVED_MEASURE_OPERAND','SELF_REFERENTIAL_MEASURE','INCOMPLETE_PERCENTAGE_OF_TOTAL','UNSUPPORTED_MEASURE_TYPE']))});
it('rejects aggregation contracts that mix ratio or filter semantics',()=>{const value=integrityDesign();value.measures[0]={...value.measures[0],numeratorMeasureId:'part',denominatorMeasureId:'all',filterField:'Facts.Status',filterValue:'Open',contextField:'Facts.Date'};expect(inspectMeasureIntegrity(value,requestSchema).map(issue=>issue.code)).toContain('INCOHERENT_MEASURE_SHAPE');expect(()=>validateReportDesign(value,['standard#1'],requestSchema)).toThrow('REPORT_DESIGN_MEASURE_INTEGRITY')});
it('accepts a coherent filtered count and rejects unknown source, filter, and context fields',()=>{const valid=integrityDesign();expect(inspectMeasureIntegrity(valid,requestSchema)).toEqual([]);const invalid=integrityDesign();invalid.measures[0].field='Facts.Unknown';invalid.measures[1].filterField='Facts.UnknownStatus';invalid.measures.push({id:'pct',name:'Percent of total',businessDefinition:'Share',aggregation:'PERCENTAGE_OF_TOTAL',field:'',numeratorMeasureId:'part',denominatorMeasureId:'all',contextField:'Facts.UnknownDate',format:'percentage'});expect(inspectMeasureIntegrity(invalid,requestSchema).map(issue=>issue.code)).toEqual(expect.arrayContaining(['UNKNOWN_MEASURE_FIELD','UNKNOWN_FILTER_FIELD','UNKNOWN_CONTEXT_FIELD']))});
it('detects missing denominators and two- and three-node dependency cycles while allowing an acyclic chain',()=>{const missing=integrityDesign();missing.measures[2].denominatorMeasureId='';expect(inspectMeasureIntegrity(missing).find(issue=>issue.code==='MISSING_RATIO_OPERAND')?.reason).toContain('denominator');const two=integrityDesign();two.measures.push({id:'other',name:'Other ratio',businessDefinition:'Other',aggregation:'RATIO',field:'',numeratorMeasureId:'share',denominatorMeasureId:'all',format:'percentage'});two.measures[2].numeratorMeasureId='other';expect(inspectMeasureIntegrity(two).map(issue=>issue.code)).toContain('CYCLIC_MEASURE_DEPENDENCY');const three=integrityDesign();three.measures.push({id:'middle',name:'Middle ratio',businessDefinition:'Middle',aggregation:'RATIO',field:'',numeratorMeasureId:'last',denominatorMeasureId:'all',format:'percentage'},{id:'last',name:'Last ratio',businessDefinition:'Last',aggregation:'RATIO',field:'',numeratorMeasureId:'share',denominatorMeasureId:'all',format:'percentage'});three.measures[2].numeratorMeasureId='middle';expect(inspectMeasureIntegrity(three).map(issue=>issue.code)).toContain('CYCLIC_MEASURE_DEPENDENCY');const acyclic=integrityDesign();acyclic.measures.push({id:'derived',name:'Derived share',businessDefinition:'Derived',aggregation:'RATIO',field:'',numeratorMeasureId:'share',denominatorMeasureId:'all',format:'percentage'});expect(inspectMeasureIntegrity(acyclic)).toEqual([])});
it('enforces supported visual binding cardinality with page and visual context',()=>{for(const type of ['card','bar','column','line'] as const){const value=integrityDesign();value.pages[0].visuals[0].type=type;value.pages[0].visuals[0].measureIds=[];const issue=inspectMeasureIntegrity(value).find(item=>item.code==='INVALID_VISUAL_BINDING_CARDINALITY');expect(issue).toMatchObject({pageId:'summary',visualId:'share-card'});expect(issue?.reason).toContain(type)}expect(inspectMeasureIntegrity(integrityDesign())).toEqual([])});
it('accepts supported chart multi-measure cardinality',()=>{const value=integrityDesign();value.pages[0].visuals[0]={...value.pages[0].visuals[0],type:'line',categoryField:'Facts.Status',measureIds:['all','part']};expect(inspectMeasureIntegrity(value)).toEqual([])});
it('reuses canonical measures across a Date category without synthetic by-month declarations',()=>{const value=integrityDesign();value.pages[0].visuals[0]={...value.pages[0].visuals[0],type:'line',title:'Monthly record trend',categoryField:'Facts.Date',measureIds:['all','share']};expect(inspectMeasureIntegrity(value,requestSchema)).toEqual([]);expect(value.measures.some(measure=>measure.id.includes('_ByMonth'))).toBe(false)});
it('deterministically reuses structurally equivalent context measures without title inference',()=>{const value=integrityDesign();value.measures.push({...value.measures[0],id:'all-period',name:'All records in category',contextField:'Facts.Date'},{...value.measures[1],id:'part-period',name:'Selected records in category',contextField:'Facts.Date'},{...value.measures[2],id:'share-period',name:'Selected share in category',numeratorMeasureId:'part-period',denominatorMeasureId:'all-period',contextField:'Facts.Date'});value.pages[0].visuals[0]={...value.pages[0].visuals[0],type:'line',categoryField:'Facts.Date',measureIds:['all-period','share-period']};const normalized=normalizeMeasureContracts(value);expect(normalized.actions).toHaveLength(3);expect(normalized.actions.map(action=>[action.measureId,action.canonicalMeasureId])).toEqual(expect.arrayContaining([['all-period','all'],['part-period','part'],['share-period','share']]));expect(normalized.normalizedReportDesign.measures.map(measure=>measure.id)).toEqual(['all','part','share']);expect(normalized.normalizedReportDesign.pages[0].visuals[0].measureIds).toEqual(['all','share']);expect(inspectMeasureIntegrity(normalized.normalizedReportDesign,requestSchema)).toEqual([]);expect(value.measures).toHaveLength(6)});
it('refuses context normalization when candidate measure IDs are duplicated',()=>{const value=integrityDesign();value.measures.push({...value.measures[0],id:'period-duplicate',name:'Period duplicate one',contextField:'Facts.Date'},{...value.measures[0],id:'period-duplicate',name:'Period duplicate two',contextField:'Facts.Date'});value.pages[0].visuals[0]={...value.pages[0].visuals[0],type:'line',categoryField:'Facts.Date',measureIds:['period-duplicate']};const normalized=normalizeMeasureContracts(value);expect(normalized.actions).toEqual([]);expect(normalized.normalizedReportDesign.measures).toHaveLength(5);expect(inspectMeasureIntegrity(normalized.normalizedReportDesign,requestSchema).map(issue=>issue.code)).toContain('DUPLICATE_MEASURE_ID')});
it('refuses context normalization when candidate measure names are duplicated',()=>{const value=integrityDesign();value.measures.push({...value.measures[0],id:'period-one',name:'Duplicated period name',contextField:'Facts.Date'},{...value.measures[0],id:'period-two',name:'Duplicated period name',contextField:'Facts.Date'});value.pages[0].visuals[0]={...value.pages[0].visuals[0],type:'line',categoryField:'Facts.Date',measureIds:['period-one','period-two']};const normalized=normalizeMeasureContracts(value);expect(normalized.actions).toEqual([]);expect(normalized.normalizedReportDesign.measures).toHaveLength(5);expect(inspectMeasureIntegrity(normalized.normalizedReportDesign,requestSchema).map(issue=>issue.code)).toContain('DUPLICATE_MEASURE_NAME')});
it('does not normalize a context measure when no exact canonical contract exists',()=>{const value=integrityDesign();value.measures.push({...value.measures[0],id:'different-period',name:'Different period measure',field:'Facts.Status',contextField:'Facts.Date'});const normalized=normalizeMeasureContracts(value);expect(normalized.actions).toEqual([]);expect(inspectMeasureIntegrity(normalized.normalizedReportDesign,requestSchema).map(issue=>issue.code)).toContain('INCOHERENT_MEASURE_SHAPE')});
it('retains an unused contextual duplicate so strict integrity rejects the invalid unused declaration',()=>{const value=integrityDesign();value.measures.push({...value.measures[0],id:'unused-period',name:'Unused period count',contextField:'Facts.Date'});const normalized=normalizeMeasureContracts(value);expect(normalized.actions).toEqual([]);expect(normalized.normalizedReportDesign.measures.some(measure=>measure.id==='unused-period')).toBe(true);expect(inspectMeasureIntegrity(normalized.normalizedReportDesign,requestSchema).map(issue=>issue.code)).toContain('INCOHERENT_MEASURE_SHAPE')});
it('retains a contextual duplicate used by a card without a category binding',()=>{const value=integrityDesign();value.measures.push({...value.measures[0],id:'card-period',name:'Card period count',contextField:'Facts.Date'});value.pages[0].visuals[0].measureIds=['card-period'];const normalized=normalizeMeasureContracts(value);expect(normalized.actions).toEqual([]);expect(inspectMeasureIntegrity(normalized.normalizedReportDesign,requestSchema).map(issue=>issue.code)).toContain('INCOHERENT_MEASURE_SHAPE')});
it('does not trust a populated categoryField on a card whose compiler binding ignores it',()=>{const value=integrityDesign();value.measures.push({...value.measures[0],id:'card-category-period',name:'Card category period',contextField:'Facts.Date'});value.pages[0].visuals[0]={...value.pages[0].visuals[0],categoryField:'Facts.Date',measureIds:['card-category-period']};const normalized=normalizeMeasureContracts(value);expect(normalized.actions).toEqual([]);expect(inspectMeasureIntegrity(normalized.normalizedReportDesign,requestSchema).map(issue=>issue.code)).toContain('INCOHERENT_MEASURE_SHAPE')});
it('does not trust categoryField on a table whose compiler consumes fields instead',()=>{const value=integrityDesign();value.measures.push({...value.measures[0],id:'table-category-period',name:'Table category period',contextField:'Facts.Date'});value.pages[0].visuals[0]={...value.pages[0].visuals[0],type:'table',categoryField:'Facts.Date',measureIds:['table-category-period'],fields:[]};const normalized=normalizeMeasureContracts(value);expect(normalized.actions).toEqual([]);expect(inspectMeasureIntegrity(normalized.normalizedReportDesign,requestSchema).map(issue=>issue.code)).toContain('INCOHERENT_MEASURE_SHAPE')});
it('retains a contextual duplicate used with a different visual category',()=>{const value=integrityDesign();value.measures.push({...value.measures[0],id:'wrong-period',name:'Wrong period count',contextField:'Facts.Date'});value.pages[0].visuals[0]={...value.pages[0].visuals[0],type:'line',categoryField:'Facts.Status',measureIds:['wrong-period']};const normalized=normalizeMeasureContracts(value);expect(normalized.actions).toEqual([]);expect(inspectMeasureIntegrity(normalized.normalizedReportDesign,requestSchema).map(issue=>issue.code)).toContain('INCOHERENT_MEASURE_SHAPE')});
it('retains a contextual operand chain whose terminal visual does not supply the declared context',()=>{const value=integrityDesign();value.measures.push({...value.measures[0],id:'all-period-card',name:'All period card',contextField:'Facts.Date'},{...value.measures[1],id:'part-period-card',name:'Part period card',contextField:'Facts.Date'},{...value.measures[2],id:'share-period-card',name:'Share period card',numeratorMeasureId:'part-period-card',denominatorMeasureId:'all-period-card',contextField:'Facts.Date'});value.pages[0].visuals[0].measureIds=['share-period-card'];const normalized=normalizeMeasureContracts(value);expect(normalized.actions).toEqual([]);expect(normalized.normalizedReportDesign.measures).toHaveLength(6);expect(inspectMeasureIntegrity(normalized.normalizedReportDesign,requestSchema).map(issue=>issue.code)).toContain('INCOHERENT_MEASURE_SHAPE')});
it('enforces table binding cardinality and reports actionable visual context',()=>{const empty=integrityDesign();empty.pages[0].visuals[0]={...empty.pages[0].visuals[0],type:'table',categoryField:'',measureIds:[],fields:[]};const issue=inspectMeasureIntegrity(empty).find(item=>item.code==='INVALID_VISUAL_BINDING_CARDINALITY');expect(issue).toMatchObject({pageId:'summary',visualId:'share-card',recommendedAction:'Provide the exact bindings required by the supported visual contract.'});expect(issue?.reason).toContain("Page 'Summary' visual 'Selected share' (table)");expect(issue?.reason).toContain('expects at least 1 field or measure');expect(issue?.reason).toContain('received 0 measure binding(s) and 0 field binding(s)');expect(()=>validateReportDesign(empty,['standard#1'])).toThrow('REPORT_DESIGN_MEASURE_INTEGRITY');for(const bindings of [{fields:['Facts.Status'],measureIds:[]},{fields:[],measureIds:['all']},{fields:['Facts.Status'],measureIds:['all']}]){const valid=integrityDesign();valid.pages[0].visuals[0]={...valid.pages[0].visuals[0],type:'table',categoryField:'',...bindings};expect(inspectMeasureIntegrity(valid)).toEqual([]);expect(validateReportDesign(valid,['standard#1'])).toBe(valid)}});
it('enforces slicer binding cardinality and reports actionable visual context',()=>{const cases=[{fields:[],categoryField:'',measureIds:[],actual:'received 0 effective field/category binding(s) and 0 measure binding(s)'},{fields:['Facts.Status'],categoryField:'',measureIds:['all'],actual:'received 1 effective field/category binding(s) and 1 measure binding(s)'},{fields:['Facts.Status','Facts.Id'],categoryField:'',measureIds:[],actual:'received 2 effective field/category binding(s) and 0 measure binding(s)'},{fields:['Facts.Status'],categoryField:'Facts.Status',measureIds:[],actual:'received 2 effective field/category binding(s) and 0 measure binding(s)'},{fields:['Facts.Status'],categoryField:'Facts.Id',measureIds:[],actual:'received 2 effective field/category binding(s) and 0 measure binding(s)'},{fields:['Facts.Status','Facts.Id'],categoryField:'Facts.Group',measureIds:[],actual:'received 3 effective field/category binding(s) and 0 measure binding(s)'}];for(const bindings of cases){const invalid=integrityDesign();invalid.pages[0].visuals[0]={...invalid.pages[0].visuals[0],type:'slicer',...bindings};const issue=inspectMeasureIntegrity(invalid).find(item=>item.code==='INVALID_VISUAL_BINDING_CARDINALITY');expect(issue).toMatchObject({pageId:'summary',visualId:'share-card',recommendedAction:'Provide the exact bindings required by the supported visual contract.'});expect(issue?.reason).toContain("Page 'Summary' visual 'Selected share' (slicer)");expect(issue?.reason).toContain('expects exactly one field or category binding and zero measures');expect(issue?.reason).toContain(bindings.actual);expect(()=>validateReportDesign(invalid,['standard#1'])).toThrow('REPORT_DESIGN_MEASURE_INTEGRITY')}for(const bindings of [{fields:['Facts.Status'],categoryField:''},{fields:[],categoryField:'Facts.Status'}]){const valid=integrityDesign();valid.pages[0].visuals[0]={...valid.pages[0].visuals[0],type:'slicer',measureIds:[],...bindings};expect(inspectMeasureIntegrity(valid)).toEqual([]);expect(validateReportDesign(valid,['standard#1'])).toBe(valid)}});
it('makes Report Design validation reject known integrity defects',()=>{const valid=integrityDesign(),citation=valid.standardsApplied[0].citation;expect(validateReportDesign(valid,[citation])).toBe(valid);const invalid=integrityDesign();invalid.measures[2].denominatorMeasureId='';expect(()=>validateReportDesign(invalid,[citation])).toThrow('REPORT_DESIGN_MEASURE_INTEGRITY')});
it('keeps every strict structured-output measure property required',()=>{const measure=(reportDesignSchema as any).properties.measures.items;expect(new Set(measure.required)).toEqual(new Set(Object.keys(measure.properties))) });
it('parses a real-shaped chat completion and retains measured usage',async()=>{
  vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({model:'gpt-4.1',choices:[{message:{content:JSON.stringify(interpretation)}}],usage:{prompt_tokens:120,completion_tokens:80,total_tokens:200}}),{status:200,headers:{'Content-Type':'application/json'}})));
  const result=await interpretRequirement('build a sales report',{},defaultTenantSettings);
  expect(result.value.objective).toBe('Track sales');expect(result.metrics).toMatchObject({model:'gpt-4.1',promptTokens:120,completionTokens:80,totalTokens:200});
});
it('fails closed when Foundry is unavailable or returns invalid JSON',async()=>{
  vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('offline')));await expect(interpretRequirement('x',{},defaultTenantSettings)).rejects.toThrow('AI_SERVICE_UNAVAILABLE');
  vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({choices:[{message:{content:'not-json'}}]}),{status:200})));await expect(interpretRequirement('x',{},defaultTenantSettings)).rejects.toThrow('AI_RESPONSE_INVALID');
});
it('requires grounded Report Design citations to come from retrieved chunks',async()=>{
  const plan={artifact_kind:'ReportDesign',schema_version:1,projectName:'SalesReport',overview:'Sales',audience:'Executives',dataModel:{factTables:['Sales'],dimensionTables:[],relationships:[]},measures:[],pages:[],filters:[],branding:{themeName:'Tenant',primary:'#005A9C',accent:'#2D7D9A'},accessibility:[],standardsApplied:[{citation:'local-knowledge:test.md@1#T-001',decision:'Use standard'}],assumptions:[],warnings:[],generationRequirements:[]};
  expect(validateReportDesign(plan,[plan.standardsApplied[0].citation])).toEqual(plan);expect(()=>validateReportDesign(plan,['other'])).toThrow('REPORT_DESIGN_CITATION_INVALID');
  vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({model:'gpt-4.1',choices:[{message:{content:JSON.stringify(plan)}}],usage:{total_tokens:50}}),{status:200})));
  expect((await generateGroundedReportDesign({}, {},defaultTenantSettings,[{citation:plan.standardsApplied[0].citation,text:'rule'}])).value.standardsApplied).toHaveLength(1);
});
it('guides Foundry toward bounded single-binding slicers without relying on the prompt for enforcement',async()=>{
  const plan=integrityDesign();let requestBody:any;
  vi.stubGlobal('fetch',vi.fn().mockImplementation(async(_path,_init)=>{requestBody=JSON.parse((_init as RequestInit).body as string);return new Response(JSON.stringify({model:'gpt-4.1',choices:[{message:{content:JSON.stringify(plan)}}],usage:{total_tokens:50}}),{status:200})}));
  await generateGroundedReportDesign({}, {},defaultTenantSettings,[{citation:'standard#1',text:'rule'}]);
  const system=String(requestBody.messages[0].content);
  expect(system).toContain('Declare every measure used by every visual exactly once');expect(system).toContain('Reuse a canonical measure across category contexts');expect(system).toContain('Each measure has one coherent shape');expect(system).toContain('Never combine these roles in one measure');expect(system).toContain('exactly one field or category binding');expect(system).toContain('multiple requested filters as separate slicer visuals');expect(system).toContain('Measure-bound slicers are unsupported');expect(system).toContain('Respect actual compiler geometry instead of a visual-count shortcut');expect(system).toContain('third row can contain cards only');expect(system).toContain('right edge at most 1280');expect(system).toContain('bottom edge at most 720');expect(system).toContain('bounded compiler contract');
});
it('sends one evidence-bound layout repair request and preserves strict citation validation',async()=>{const repaired=integrityDesign(),original=integrityDesign(),geometry={normalizationFindings:[{code:'LAYOUT_CAPACITY_EXCEEDED',pageId:'summary',attemptedLayoutSlots:[{visualId:'share-card',bottom:780}]}],pageLayouts:[]};let requestBody:any;vi.stubGlobal('fetch',vi.fn().mockImplementation(async(_path,_init)=>{requestBody=JSON.parse((_init as RequestInit).body as string);return new Response(JSON.stringify({model:'gpt-4.1',choices:[{message:{content:JSON.stringify(repaired)}}],usage:{prompt_tokens:10,completion_tokens:20,total_tokens:30}}),{status:200})}));const result=await repairGroundedReportDesignLayout({requirement:'Keep required KPIs'},requestSchema,defaultTenantSettings,[{citation:'standard#1',text:'rule'}],original,geometry);expect(result.value).toEqual(repaired);expect(result.metrics.totalTokens).toBe(30);expect(fetch).toHaveBeenCalledTimes(1);const system=String(requestBody.messages[0].content),payload=JSON.parse(requestBody.messages[1].content);expect(system).toContain('only repair attempt');expect(system).toContain('never remove required business content');expect(system).toContain('deterministic geometry evidence');expect(system).toContain('re-run all normalization, integrity, guardrail, compiler, and deterministic validation gates');expect(payload).toMatchObject({attemptLimit:1,originalReportDesign:original,deterministicGeometryEvidence:geometry});repaired.standardsApplied[0].citation='invented';vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(repaired)}}]}),{status:200})));await expect(repairGroundedReportDesignLayout({},requestSchema,defaultTenantSettings,[{citation:'standard#1',text:'rule'}],original,geometry)).rejects.toThrow('REPORT_DESIGN_CITATION_INVALID')});
