import type {TenantSettings} from './tenant';

export type AIMetrics={model:string;latencyMs:number;promptTokens:number|null;completionTokens:number|null;totalTokens:number|null};
export type AIResult<T>={value:T;metrics:AIMetrics};
export type FoundryStatus={configured:boolean;chatDeployment:string;embeddingDeployment:string;apiMode:string;endpointDisplay?:string;authentication?:string};
export type Clarification={id:string;category:'METRIC_DEFINITION'|'TIME_COMPARISON'|'SECURITY'|'AUDIENCE'|'PAGE_SCOPE'|'FILTER_SCOPE'|'OTHER';question:string;reason:string;required:boolean};
export type RequirementInterpretation={request_kind:'POWER_BI_REPORT'|'OUT_OF_SCOPE';objective:string;businessQuestions:string[];kpis:string[];dimensions:string[];filters:string[];audience:string;pages:string[];assumptions:string[];ambiguities:string[];clarifications:Clarification[]};
export type MeasureAggregation='SUM'|'DISTINCTCOUNT'|'COUNT'|'AVERAGE'|'FILTERED_COUNT'|'RATIO'|'PERCENTAGE_OF_TOTAL';
export type MeasureDesign={id:string;name:string;businessDefinition:string;aggregation:MeasureAggregation;field:string;numeratorMeasureId:string;denominatorMeasureId:string;format:'currency'|'integer'|'decimal'|'percentage';filterField?:string;filterValue?:string;contextField?:string};
export type VisualDesign={id:string;type:'card'|'bar'|'column'|'line'|'table'|'slicer';title:string;categoryField:string;measureIds:string[];fields:string[];altText:string};
export type ReportDesign={artifact_kind:'ReportDesign';schema_version:1;projectName:string;overview:string;audience:string;dataModel:{factTables:string[];dimensionTables:string[];relationships:Array<{fromTable:string;fromColumn:string;toTable:string;toColumn:string}>};measures:MeasureDesign[];pages:Array<{id:string;name:string;purpose:string;visuals:VisualDesign[]}>;filters:string[];branding:{themeName:string;primary:string;accent:string};accessibility:string[];standardsApplied:Array<{citation:string;decision:string}>;assumptions:string[];warnings:string[];generationRequirements:string[]};

const stringArray={type:'array',items:{type:'string'}};
export const interpretationSchema={type:'object',additionalProperties:false,required:['request_kind','objective','businessQuestions','kpis','dimensions','filters','audience','pages','assumptions','ambiguities','clarifications'],properties:{request_kind:{type:'string',enum:['POWER_BI_REPORT','OUT_OF_SCOPE']},objective:{type:'string'},businessQuestions:stringArray,kpis:stringArray,dimensions:stringArray,filters:stringArray,audience:{type:'string'},pages:stringArray,assumptions:stringArray,ambiguities:stringArray,clarifications:{type:'array',items:{type:'object',additionalProperties:false,required:['id','category','question','reason','required'],properties:{id:{type:'string'},category:{type:'string',enum:['METRIC_DEFINITION','TIME_COMPARISON','SECURITY','AUDIENCE','PAGE_SCOPE','FILTER_SCOPE','OTHER']},question:{type:'string'},reason:{type:'string'},required:{type:'boolean'}}}}}};
const relationshipSchema={type:'object',additionalProperties:false,required:['fromTable','fromColumn','toTable','toColumn'],properties:{fromTable:{type:'string'},fromColumn:{type:'string'},toTable:{type:'string'},toColumn:{type:'string'}}};
const measureSchema={type:'object',additionalProperties:false,required:['id','name','businessDefinition','aggregation','field','numeratorMeasureId','denominatorMeasureId','format','filterField','filterValue','contextField'],properties:{id:{type:'string'},name:{type:'string'},businessDefinition:{type:'string'},aggregation:{type:'string',enum:['SUM','DISTINCTCOUNT','COUNT','AVERAGE','FILTERED_COUNT','RATIO','PERCENTAGE_OF_TOTAL']},field:{type:'string'},numeratorMeasureId:{type:'string'},denominatorMeasureId:{type:'string'},format:{type:'string',enum:['currency','integer','decimal','percentage']},filterField:{type:'string'},filterValue:{type:'string'},contextField:{type:'string'}}};
const visualSchema={type:'object',additionalProperties:false,required:['id','type','title','categoryField','measureIds','fields','altText'],properties:{id:{type:'string'},type:{type:'string',enum:['card','bar','column','line','table','slicer']},title:{type:'string'},categoryField:{type:'string'},measureIds:stringArray,fields:stringArray,altText:{type:'string'}}};
export const reportDesignSchema={type:'object',additionalProperties:false,required:['artifact_kind','schema_version','projectName','overview','audience','dataModel','measures','pages','filters','branding','accessibility','standardsApplied','assumptions','warnings','generationRequirements'],properties:{artifact_kind:{type:'string',enum:['ReportDesign']},schema_version:{type:'integer',enum:[1]},projectName:{type:'string'},overview:{type:'string'},audience:{type:'string'},dataModel:{type:'object',additionalProperties:false,required:['factTables','dimensionTables','relationships'],properties:{factTables:stringArray,dimensionTables:stringArray,relationships:{type:'array',items:relationshipSchema}}},measures:{type:'array',items:measureSchema},pages:{type:'array',items:{type:'object',additionalProperties:false,required:['id','name','purpose','visuals'],properties:{id:{type:'string'},name:{type:'string'},purpose:{type:'string'},visuals:{type:'array',items:visualSchema}}}},filters:stringArray,branding:{type:'object',additionalProperties:false,required:['themeName','primary','accent'],properties:{themeName:{type:'string'},primary:{type:'string'},accent:{type:'string'}}},accessibility:stringArray,standardsApplied:{type:'array',items:{type:'object',additionalProperties:false,required:['citation','decision'],properties:{citation:{type:'string'},decision:{type:'string'}}}},assumptions:stringArray,warnings:stringArray,generationRequirements:stringArray}};

function record(value:unknown){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('AI_RESPONSE_INVALID');return value as Record<string,unknown>}
function strings(value:unknown){if(!Array.isArray(value)||!value.every(item=>typeof item==='string'))throw new Error('AI_RESPONSE_INVALID');return value as string[]}
export function validateInterpretation(value:unknown):RequirementInterpretation{const v=record(value);if(!['POWER_BI_REPORT','OUT_OF_SCOPE'].includes(String(v.request_kind))||typeof v.objective!=='string'||typeof v.audience!=='string')throw new Error('AI_RESPONSE_INVALID');const clarifications=(Array.isArray(v.clarifications)?v.clarifications:[]).map(item=>{const q=record(item);if(typeof q.id!=='string'||typeof q.question!=='string'||typeof q.reason!=='string'||typeof q.required!=='boolean'||!['METRIC_DEFINITION','TIME_COMPARISON','SECURITY','AUDIENCE','PAGE_SCOPE','FILTER_SCOPE','OTHER'].includes(String(q.category)))throw new Error('AI_RESPONSE_INVALID');return q as unknown as Clarification});if(new Set(clarifications.map(q=>q.id)).size!==clarifications.length)return(()=>{throw new Error('AI_RESPONSE_INVALID')})();return{request_kind:v.request_kind as RequirementInterpretation['request_kind'],objective:v.objective,businessQuestions:strings(v.businessQuestions),kpis:strings(v.kpis),dimensions:strings(v.dimensions),filters:strings(v.filters),audience:v.audience,pages:strings(v.pages),assumptions:strings(v.assumptions),ambiguities:strings(v.ambiguities),clarifications}}
export type MeasureIntegrityIssue={code:'DUPLICATE_MEASURE_ID'|'DUPLICATE_MEASURE_NAME'|'UNSUPPORTED_MEASURE_TYPE'|'MISSING_MEASURE_FIELD'|'INCOMPLETE_FILTERED_COUNT'|'MISSING_RATIO_OPERAND'|'UNRESOLVED_MEASURE_OPERAND'|'SELF_REFERENTIAL_MEASURE'|'INCOMPLETE_PERCENTAGE_OF_TOTAL'|'UNRESOLVED_VISUAL_MEASURE';measureId:string;reason:string;recommendedAction:string;pageId?:string;visualId?:string};
export function inspectMeasureIntegrity(design:ReportDesign):MeasureIntegrityIssue[]{
 const issues:MeasureIntegrityIssue[]=[],byId=new Map<string,MeasureDesign>(),canonicalIds=new Set<string>(),names=new Set<string>(),supported=new Set<MeasureAggregation>(['SUM','DISTINCTCOUNT','COUNT','AVERAGE','FILTERED_COUNT','RATIO','PERCENTAGE_OF_TOTAL']);
 const add=(issue:MeasureIntegrityIssue)=>issues.push(issue);
 for(const measure of design.measures){
  const canonicalId=measure.id.trim().toLocaleLowerCase(),canonicalName=measure.name.trim().toLocaleLowerCase();
  if(!canonicalId||canonicalIds.has(canonicalId))add({code:'DUPLICATE_MEASURE_ID',measureId:measure.id,reason:`Measure ID '${measure.id}' is empty or duplicated.`,recommendedAction:'Give every declared measure one unique, stable ID.'});else{canonicalIds.add(canonicalId);byId.set(measure.id,measure)}
  if(!canonicalName||names.has(canonicalName))add({code:'DUPLICATE_MEASURE_NAME',measureId:measure.id,reason:`Measure name '${measure.name}' is empty or duplicated.`,recommendedAction:'Give every declared measure one unique display name.'});else names.add(canonicalName);
 }
 for(const measure of design.measures){
  if(!supported.has(measure.aggregation))add({code:'UNSUPPORTED_MEASURE_TYPE',measureId:measure.id,reason:`Measure '${measure.id}' uses unsupported aggregation '${String(measure.aggregation)}'.`,recommendedAction:'Use one of the bounded structured aggregation types.'});
  if(['SUM','DISTINCTCOUNT','COUNT','AVERAGE','FILTERED_COUNT'].includes(measure.aggregation)&&!measure.field.trim())add({code:'MISSING_MEASURE_FIELD',measureId:measure.id,reason:`Measure '${measure.id}' requires a source field.`,recommendedAction:'Provide an exact Table.Column source field.'});
  if(measure.aggregation==='FILTERED_COUNT'&&(!measure.filterField?.trim()||!measure.filterValue?.trim()))add({code:'INCOMPLETE_FILTERED_COUNT',measureId:measure.id,reason:`Filtered count '${measure.id}' requires filterField and filterValue.`,recommendedAction:'Provide an exact filter field and value or use a supported unfiltered count.'});
  if(measure.aggregation==='RATIO'||measure.aggregation==='PERCENTAGE_OF_TOTAL'){
   for(const [role,id] of [['numerator',measure.numeratorMeasureId],['denominator',measure.denominatorMeasureId]] as const){
    if(!id.trim())add({code:'MISSING_RATIO_OPERAND',measureId:measure.id,reason:`Measure '${measure.id}' is missing its ${role} measure ID.`,recommendedAction:`Declare and reference a supported ${role} measure.`});
    else if(id===measure.id)add({code:'SELF_REFERENTIAL_MEASURE',measureId:measure.id,reason:`Measure '${measure.id}' references itself as its ${role}.`,recommendedAction:'Reference a different declared measure.'});
    else if(!byId.has(id))add({code:'UNRESOLVED_MEASURE_OPERAND',measureId:measure.id,reason:`Measure '${measure.id}' references unknown ${role} '${id}'.`,recommendedAction:`Declare the ${role} measure or correct the exact ID.`});
   }
  }
  if(measure.aggregation==='PERCENTAGE_OF_TOTAL'&&!measure.contextField?.trim())add({code:'INCOMPLETE_PERCENTAGE_OF_TOTAL',measureId:measure.id,reason:`Percentage-of-total measure '${measure.id}' requires a contextField.`,recommendedAction:'Provide the exact Table.Column whose filter is removed for the total.'});
 }
 for(const page of design.pages)for(const visual of page.visuals)for(const id of visual.measureIds)if(!byId.has(id))add({code:'UNRESOLVED_VISUAL_MEASURE',measureId:id,reason:`Page '${page.name}' visual '${visual.title}' references unknown measure '${id}'.`,recommendedAction:'Reference an exact declared measure ID.',pageId:page.id,visualId:visual.id});
 return issues;
}
export function validateReportDesign(value:unknown,allowedCitations:readonly string[]):ReportDesign{const v=record(value);if(v.artifact_kind!=='ReportDesign'||v.schema_version!==1||typeof v.projectName!=='string'||!Array.isArray(v.pages)||!Array.isArray(v.measures))throw new Error('REPORT_DESIGN_INVALID');const citations=new Set(allowedCitations);const applied=Array.isArray(v.standardsApplied)?v.standardsApplied.map(record):[];if(!applied.length||applied.some(item=>typeof item.citation!=='string'||typeof item.decision!=='string'||!citations.has(item.citation)))throw new Error('REPORT_DESIGN_CITATION_INVALID');const design=v as unknown as ReportDesign;inspectMeasureIntegrity(design);return design}

async function post(path:string,body:unknown){const start=performance.now();let response:Response;try{response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}catch{throw new Error('AI_SERVICE_UNAVAILABLE')}const latencyMs=Math.round(performance.now()-start);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`AI_SERVICE_UNAVAILABLE: ${String(data?.error?.code??response.status)}`);return{data,latencyMs}}
export async function foundryStatus():Promise<FoundryStatus>{const response=await fetch('/api/ai/status');if(!response.ok)throw new Error('AI_SERVICE_UNAVAILABLE');return response.json()}
async function structured<T>(name:string,schema:unknown,messages:Array<{role:'system'|'user';content:string}>,validate:(value:unknown)=>T):Promise<AIResult<T>>{const{data,latencyMs}=await post('/api/ai/chat',{messages,response_format:{type:'json_schema',json_schema:{name,strict:true,schema}}});const content=data?.choices?.[0]?.message?.content;if(typeof content!=='string')throw new Error('AI_RESPONSE_INVALID');let parsed:unknown;try{parsed=JSON.parse(content)}catch{throw new Error('AI_RESPONSE_INVALID')}return{value:validate(parsed),metrics:{model:String(data.model??'configured deployment'),latencyMs,promptTokens:data.usage?.prompt_tokens??null,completionTokens:data.usage?.completion_tokens??null,totalTokens:data.usage?.total_tokens??null}}}
export async function interpretRequirement(prompt:string,schema:unknown,tenant:TenantSettings){const system='You are a Power BI solution architect. Classify whether the request is for a Power BI report. Interpret only the supplied request and request-specific schema. Return the required JSON. Derive at most five material clarification questions dynamically. Never treat tenant policy as user data, never invent fields, and never infer authorization. Mark unrelated requests OUT_OF_SCOPE. Questions about time comparison use TIME_COMPARISON; ambiguity between filters and access control uses SECURITY.';return structured('power_bi_requirement_interpretation',interpretationSchema,[{role:'system',content:system},{role:'user',content:JSON.stringify({requirement:prompt,dataStructure:schema,tenantConfiguration:{locale:tenant.organisation.locale,timezone:tenant.organisation.timezone,generationCapabilities:tenant.generation.supportedCapabilities}})}],validateInterpretation)}
export async function generateGroundedReportDesign(snapshot:unknown,schema:unknown,tenant:TenantSettings,chunks:Array<{citation:string;text:string}>){const allowed=chunks.map(chunk=>chunk.citation);const system='Create the required structured Power BI ReportDesign. It is an internal compiler contract. Use only exact table and column identifiers from the supplied request schema. Every non-empty field, categoryField, filterField, contextField, and filter must use the fully qualified Table.Column form; never return a display label or unqualified column name there. Use only supported visual and aggregation enum values. RATIO and PERCENTAGE_OF_TOTAL measures reference declared numerator and denominator measure IDs; PERCENTAGE_OF_TOTAL also declares contextField. FILTERED_COUNT declares field, filterField, and filterValue. Other measures use field as Table.Column. Visual measureIds reference declared measure IDs, never measure names. Every customer-standard decision cites one supplied citation. Do not emit executable DAX, M, SQL, credentials, or unsupported fields. Put uncertainties in warnings.';return structured('grounded_power_bi_report_design',reportDesignSchema,[{role:'system',content:system},{role:'user',content:JSON.stringify({confirmedRequirements:snapshot,dataStructure:schema,tenantConfiguration:{organisation:tenant.organisation,branding:tenant.branding,generation:tenant.generation},retrievedStandards:chunks})}],value=>validateReportDesign(value,allowed))}
export async function embedTexts(input:string[]):Promise<AIResult<number[][]>>{const{data,latencyMs}=await post('/api/ai/embeddings',{input});const vectors=Array.isArray(data.data)?data.data.map((item:any)=>item.embedding):null;if(!vectors||vectors.length!==input.length||vectors.some((vector:unknown)=>!Array.isArray(vector)||!vector.every(item=>typeof item==='number')))throw new Error('EMBEDDING_RESPONSE_INVALID');return{value:vectors,metrics:{model:String(data.model??'configured deployment'),latencyMs,promptTokens:data.usage?.prompt_tokens??null,completionTokens:null,totalTokens:data.usage?.total_tokens??null}}}
