import {expect,it} from 'vitest';
import {compilePowerBI,compilerCapabilities,resolveMeasureRegistry,validateGenericCandidate} from './genericPowerBI';
import {defaultTenantSettings as unvalidatedTenantSettings} from './tenant';
import type {DataStructure} from './schemaIngestion';
import type {ReportDesign} from './foundry';

const defaultTenantSettings=structuredClone(unvalidatedTenantSettings);defaultTenantSettings.governance.maxVisualsPerPage=compilerCapabilities.maxVisualsPerPage;defaultTenantSettings.governance.humanReviewAtVisuals=compilerCapabilities.maxVisualsPerPage;

const data=(name='Orders'):DataStructure=>({kind:'REQUEST_DATA_STRUCTURE',fileName:`${name}.csv`,format:'CSV',parsedAt:'2026-01-01',tables:[{name,sourceName:name,rowCount:2,rows:[['North','100','O1','Open','2026-01-01'],['South','200','O2','Closed','2026-02-01']],columns:[{name:'Region',sourceName:'Region',type:'text',nullable:false,sampleValues:['North','South']},{name:'Revenue',sourceName:'Revenue',type:'integer',nullable:false,sampleValues:['100','200']},{name:'OrderId',sourceName:'OrderId',type:'text',nullable:false,sampleValues:['O1','O2']},{name:'Status',sourceName:'Status',type:'text',nullable:false,sampleValues:['Open','Closed']},{name:'Date',sourceName:'Date',type:'date',nullable:false,sampleValues:['2026-01-01','2026-02-01']}]}],relationships:[]});
const design=(table='Orders'):ReportDesign=>({artifact_kind:'ReportDesign',schema_version:1,projectName:`${table}Performance`,overview:'Performance report',audience:'Leaders',dataModel:{factTables:[table],dimensionTables:[],relationships:[]},measures:[{id:'revenue',name:'Total Revenue',businessDefinition:'Revenue',aggregation:'SUM',field:`${table}.Revenue`,numeratorMeasureId:'',denominatorMeasureId:'',format:'currency'},{id:'orders',name:'Total Orders',businessDefinition:'Orders',aggregation:'DISTINCTCOUNT',field:`${table}.OrderId`,numeratorMeasureId:'',denominatorMeasureId:'',format:'integer'}],pages:[{id:'summary',name:'Summary',purpose:'Overview',visuals:[{id:'card',type:'card',title:'Total Revenue',categoryField:'',measureIds:['revenue'],fields:[],altText:'Total revenue'},{id:'region',type:'bar',title:'Revenue by region',categoryField:`${table}.Region`,measureIds:['revenue'],fields:[],altText:'Revenue by region'},{id:'filter',type:'slicer',title:'Region',categoryField:'',measureIds:[],fields:[`${table}.Region`],altText:'Region filter'}]}],filters:[`${table}.Region`],branding:{themeName:'Tenant',primary:'#005A9C',accent:'#2D7D9A'},accessibility:['Titles'],standardsApplied:[{citation:'local:test#1',decision:'Use standard visuals'}],assumptions:[],warnings:[],generationRequirements:[]});
const trendDesign=(grain:'DAY'|'MONTH'|'QUARTER'|'YEAR')=>{const value=design(),trend=value.pages[0].visuals[1];trend.categoryField='Orders.Date';trend.timeGrain=grain;return value};
it('rejects an unused source header that breaks out of the Power Query M text literal',()=>{
 const source=data(),plan=design(),header='Unused", each 1), Injected = 1 //';
 source.tables[0].columns.push({name:header,sourceName:header,type:'text',nullable:true,sampleValues:[]});
 expect(()=>compilePowerBI(plan,source,defaultTenantSettings)).toThrow('UNSUPPORTED_SOURCE_NAME');
});
it('rejects unsafe candidate keys even when the other generated files exist',()=>{
 const source=data(),plan=design(),candidate=compilePowerBI(plan,source,defaultTenantSettings);
 candidate.files['data/..\\outside.csv']='unsafe';
 expect(validateGenericCandidate(candidate,plan,source).status).toBe('FAIL');
});
it('rejects an unexpected but lexically safe extra file from the exact candidate',()=>{
 const source=data(),plan=design(),candidate=compilePowerBI(plan,source,defaultTenantSettings);
 candidate.files['data/Extra.csv']='x';
 expect(validateGenericCandidate(candidate,plan,source).checks.find(item=>item.id==='EXACT_SOURCE_CANDIDATE')?.status).toBe('FAIL');
});
it.each([
 'Quote"',"Apostrophe'",'Bracket]','M#(lf)','Carriage\rReturn','Line\nFeed','Tab\tName',
 'Expr", each 1)','Comment//Field','Block/*Field','Add(1+2)','Slash/Name','Back\\Name',
 '..','.Hidden','Trailing.','', 'NomÉ', 'Cafe\u0301', 'name: value', 'let',
])('fails closed on unsupported unused source column %j',name=>{
 const source=data(),plan=design();source.tables[0].columns.push({name,sourceName:name,type:'text',nullable:true,sampleValues:[]});
 expect(()=>compilePowerBI(plan,source,defaultTenantSettings)).toThrow('UNSUPPORTED_SOURCE_NAME');
});
it.each(['A/B','A\\B','A]B','A#B','A\nB','..','', 'Café'])('rejects source table names outside the bare TMDL/DAX and file-key profile: %j',name=>{
 const source=data(),plan=design();source.tables[0].name=name;plan.dataModel.factTables=[name];
 expect(()=>compilePowerBI(plan,source,defaultTenantSettings)).toThrow();
});
it.each(['Measure]Break','Measure\nBreak','Measure #(lf)','A/B',''])('rejects unsafe measure names at TMDL and DAX references: %j',name=>{
 const source=data(),plan=design();plan.measures[0].name=name;
 expect(()=>compilePowerBI(plan,source,defaultTenantSettings)).toThrow();
});
it.each(['data/..\\outside.csv','/absolute.tmdl','data/../outside.csv','data//outside.csv','data/./outside.csv','data/trailing/','data/%2e%2e.csv'])('rejects unsafe candidate key %j',key=>{
 const source=data(),plan=design(),candidate=compilePowerBI(plan,source,defaultTenantSettings);candidate.files[key]='synthetic';
 expect(validateGenericCandidate(candidate,plan,source).checks.find(item=>item.id==='EXACT_SOURCE_CANDIDATE')?.status).toBe('FAIL');
});
it('rejects exact generated M, DAX/TMDL, relationship and embedded CSV tampering',()=>{
 const source=data(),plan=design();
 for(const [path,oldText,newText] of [
  ['OrdersPerformance.SemanticModel/definition/tables/Orders.tmdl','type text','each 1'],
  ['OrdersPerformance.SemanticModel/definition/tables/Orders.tmdl','SUM(Orders[Revenue])','SUM(Orders[Status])'],
  ['OrdersPerformance.SemanticModel/definition/model.tmdl','ref table Orders','ref table Other'],
  ['data/Orders.csv','North','Other'],
 ] as const){const candidate=compilePowerBI(plan,source,defaultTenantSettings);candidate.files[path]=candidate.files[path].replace(oldText,newText);expect(validateGenericCandidate(candidate,plan,source).checks.find(item=>item.id==='EXACT_SOURCE_CANDIDATE')?.status).toBe('FAIL')}
});
it('preserves four unrelated renamed synthetic domains under one source grammar',()=>{
 for(const [table,dimension,amount,id] of [
  ['ClinicAppointments','Clinic','Duration','AppointmentId'],
  ['WarehouseMoves','Zone','Units','MoveId'],
  ['CourseEnrollments','Campus','EnrollmentCount','EnrollmentId'],
  ['EquipmentMaintenance','Workshop','ServiceHours','WorkOrderId'],
 ] as const){
  const source=data(),plan=design();source.tables[0].name=table;source.tables[0].sourceName=table;source.fileName=`${table}.csv`;
  for(const [index,name] of [[0,dimension],[1,amount],[2,id]] as const){source.tables[0].columns[index].name=name;source.tables[0].columns[index].sourceName=name}
  plan.projectName=`${table}Performance`;plan.dataModel.factTables=[table];
  plan.measures[0].field=`${table}.${amount}`;plan.measures[1].field=`${table}.${id}`;
  plan.pages[0].visuals[1].categoryField=`${table}.${dimension}`;
  plan.pages[0].visuals[2].fields=[`${table}.${dimension}`];plan.filters=[`${table}.${dimension}`];
  const candidate=compilePowerBI(plan,source,defaultTenantSettings);
  expect(validateGenericCandidate(candidate,plan,source).status,table).toBe('PASS');
  expect(candidate.files[`${table}Performance.SemanticModel/definition/tables/${table}.tmdl`]).toContain(`table ${table}`);
 }
});
it('compiles a structured generic design into validated PBIP/PBIR source',()=>{const source=data(),plan=design(),candidate=compilePowerBI(plan,source,defaultTenantSettings),validation=validateGenericCandidate(candidate,plan,source);expect(validation.status).toBe('PASS');expect(candidate.files['OrdersPerformance.pbip']).toContain('OrdersPerformance.Report');expect(Object.keys(candidate.files).filter(path=>path.endsWith('/visual.json'))).toHaveLength(3);expect(Object.values(candidate.files).join('\n')).toContain('SUM(Orders[Revenue])')});
it.each(['Revenue','rEvEnUe','Region'])('preserves the visible %s measure while isolating a colliding source column',name=>{const source=data(),plan=design();plan.measures[0].name=name;const candidate=compilePowerBI(plan,source,defaultTenantSettings),tables=Object.entries(candidate.files).filter(([path])=>path.endsWith('.tmdl')&&path.includes('/definition/tables/')),technical=tables.find(([path])=>path.includes('/__APBRA_Measures_'));expect(technical).toBeDefined();expect(technical![1]).toContain(`measure '${name}' = SUM(Orders[Revenue])`);expect(candidate.files['OrdersPerformance.SemanticModel/definition/tables/Orders.tmdl']).not.toContain(`measure '${name}' =`);expect(validateGenericCandidate(candidate,plan,source).checks.find(item=>item.id==='SEMANTIC_NAMESPACE')?.status).toBe('PASS');expect(validateGenericCandidate(candidate,plan,source).status).toBe('PASS');const visuals=Object.values(candidate.files).filter(value=>value.includes('cardVisual'));expect(visuals.join('\n')).toContain(`${technical![0].split('/').at(-1)!.slice(0,-5)}.${name}`)});
it('rejects a tampered measure home or case/Unicode-equivalent source-column identity',()=>{const source=data(),plan=design();plan.measures[0].name='Revenue';const candidate=compilePowerBI(plan,source,defaultTenantSettings),visualPath=Object.keys(candidate.files).find(path=>path.endsWith('/visual.json')&&candidate.files[path].includes('cardVisual'))!;candidate.files[visualPath]=candidate.files[visualPath].replaceAll('__APBRA_Measures_','Orders_');expect(validateGenericCandidate(candidate,plan,source).checks.find(item=>item.id==='SEMANTIC_NAMESPACE')?.status).toBe('FAIL');source.tables[0].columns.push({...source.tables[0].columns[1],name:'Ｒｅｖｅｎｕｅ'});expect(()=>compilePowerBI(plan,source,defaultTenantSettings)).toThrow('SEMANTIC_NAMESPACE_COLLISION')});
it('produces materially different packages from different schema/design contracts',()=>{const first=compilePowerBI(design('Orders'),data('Orders'),defaultTenantSettings),second=compilePowerBI(design('Tickets'),data('Tickets'),defaultTenantSettings);expect(Object.keys(first.files)).not.toEqual(Object.keys(second.files));expect(second.files['TicketsPerformance.SemanticModel/definition/tables/Tickets.tmdl']).toContain('table Tickets')});
it('preserves Unicode request data through UTF-8 Base64 embedding',()=>{const source=data();source.tables[0].rows=[['Côte d’Ivoire — 日本','100','O1'],['München – café','200','O2']];const candidate=compilePowerBI(design(),source,defaultTenantSettings);const tmdl=candidate.files['OrdersPerformance.SemanticModel/definition/tables/Orders.tmdl'];const encoded=tmdl.match(/Binary.FromText\("([A-Za-z0-9+/=]+)"/)![1];const bytes=Uint8Array.from(atob(encoded),character=>character.charCodeAt(0));expect(new TextDecoder().decode(bytes)).toBe(candidate.files['data/Orders.csv']);expect(candidate.files['data/Orders.csv']).toContain('Côte d’Ivoire — 日本');});
it('fails deterministic validation when a generated reference is removed',()=>{const source=data(),plan=design(),candidate=compilePowerBI(plan,source,defaultTenantSettings);delete candidate.files['OrdersPerformance.Report/definition.pbir'];expect(validateGenericCandidate(candidate,plan,source).status).toBe('FAIL')});
it('compiles deterministic filtered counts, differences, ratios, and percentage-of-total expressions',()=>{const source=data(),plan=design();plan.measures.push({id:'open',name:'Open Orders',businessDefinition:'Open orders',aggregation:'FILTERED_COUNT',field:'Orders.OrderId',filterField:'Orders.Status',filterValue:'Open',numeratorMeasureId:'',denominatorMeasureId:'',format:'integer'},{id:'closed-gap',name:'Order Gap',businessDefinition:'All orders minus open orders',aggregation:'DIFFERENCE',field:'',numeratorMeasureId:'orders',denominatorMeasureId:'open',format:'integer'},{id:'rate',name:'Open Rate',businessDefinition:'Open divided by all',aggregation:'RATIO',field:'',numeratorMeasureId:'open',denominatorMeasureId:'orders',format:'percentage'},{id:'share',name:'Regional Share',businessDefinition:'Regional share of all orders',aggregation:'PERCENTAGE_OF_TOTAL',field:'',numeratorMeasureId:'orders',denominatorMeasureId:'orders',contextField:'Orders.Region',format:'percentage'});plan.pages[0].visuals[0].measureIds=['rate'];const candidate=compilePowerBI(plan,source,defaultTenantSettings),tmdl=candidate.files['OrdersPerformance.SemanticModel/definition/tables/Orders.tmdl'];expect(tmdl).toContain('CALCULATE(COUNT(Orders[OrderId]), Orders[Status] = "Open")');expect(tmdl).toContain('[Total Orders] - [Open Orders]');expect(tmdl).toContain('DIVIDE([Open Orders], [Total Orders])');expect(tmdl).toContain('REMOVEFILTERS(Orders[Region])');expect(validateGenericCandidate(candidate,plan,source).status).toBe('PASS')});
it('defensively rejects incomplete registries before producing candidate bytes',()=>{for(const mutate of [(plan:ReportDesign)=>plan.measures.push({...plan.measures[0]}),(plan:ReportDesign)=>plan.measures.push({id:'ratio',name:'Ratio',businessDefinition:'Ratio',aggregation:'RATIO',field:'',numeratorMeasureId:'',denominatorMeasureId:'orders',format:'percentage'}),(plan:ReportDesign)=>plan.pages[0].visuals[0].measureIds=['missing']]){const plan=design();mutate(plan);expect(()=>resolveMeasureRegistry(plan)).toThrow('MEASURE_INTEGRITY');expect(()=>compilePowerBI(plan,data(),defaultTenantSettings)).toThrow('MEASURE_INTEGRITY')}});
it('treats an invalid unused declared measure as compilation-unsafe',()=>{const plan=design();plan.measures.push({id:'unused',name:'Unused',businessDefinition:'Incomplete ratio',aggregation:'RATIO',field:'',numeratorMeasureId:'missing',denominatorMeasureId:'orders',format:'percentage'});expect(()=>compilePowerBI(plan,data(),defaultTenantSettings)).toThrow('UNRESOLVED_MEASURE_OPERAND unused')});
it('rejects empty required visual bindings before measureBinding can receive undefined',()=>{for(const type of ['card','bar','column','line'] as const){const plan=design();plan.pages[0].visuals[0].type=type;plan.pages[0].visuals[0].measureIds=[];expect(()=>compilePowerBI(plan,data(),defaultTenantSettings)).toThrow('INVALID_VISUAL_BINDING_CARDINALITY')}});
it('defensively rejects an empty table while compiling every supported non-empty table binding',()=>{const empty=design();empty.pages[0].visuals=[{...empty.pages[0].visuals[0],type:'table',categoryField:'',measureIds:[],fields:[]}];expect(()=>compilePowerBI(empty,data(),defaultTenantSettings)).toThrow('INVALID_VISUAL_BINDING_CARDINALITY');for(const bindings of [{fields:['Orders.Region'],measureIds:[]},{fields:[],measureIds:['orders']},{fields:['Orders.Region'],measureIds:['orders']}]){const plan=design();plan.pages[0].visuals=[{...plan.pages[0].visuals[0],type:'table',categoryField:'',...bindings}];expect(()=>compilePowerBI(plan,data(),defaultTenantSettings)).not.toThrow()}});
it('defensively rejects invalid slicer bindings while compiling exactly one field or category',()=>{for(const bindings of [{fields:[],categoryField:'',measureIds:[]},{fields:['Orders.Region'],categoryField:'',measureIds:['orders']},{fields:['Orders.Region','Orders.Status'],categoryField:'',measureIds:[]},{fields:['Orders.Region'],categoryField:'Orders.Region',measureIds:[]},{fields:['Orders.Region'],categoryField:'Orders.Status',measureIds:[]},{fields:['Orders.Region','Orders.Status'],categoryField:'Orders.OrderId',measureIds:[]}]){const plan=design();plan.pages[0].visuals=[{...plan.pages[0].visuals[0],type:'slicer',...bindings}];expect(()=>compilePowerBI(plan,data(),defaultTenantSettings)).toThrow('INVALID_VISUAL_BINDING_CARDINALITY')}for(const bindings of [{fields:['Orders.Region'],categoryField:''},{fields:[],categoryField:'Orders.Region'}]){const plan=design();plan.pages[0].visuals=[{...plan.pages[0].visuals[0],type:'slicer',measureIds:[],...bindings}];expect(()=>compilePowerBI(plan,data(),defaultTenantSettings)).not.toThrow()}});
it('rejects cyclic derived measures while retaining valid acyclic derived chains',()=>{const cyclic=design();cyclic.measures.push({id:'a',name:'A',businessDefinition:'A',aggregation:'RATIO',field:'',numeratorMeasureId:'b',denominatorMeasureId:'orders',format:'percentage'},{id:'b',name:'B',businessDefinition:'B',aggregation:'RATIO',field:'',numeratorMeasureId:'a',denominatorMeasureId:'orders',format:'percentage'});expect(()=>compilePowerBI(cyclic,data(),defaultTenantSettings)).toThrow('CYCLIC_MEASURE_DEPENDENCY');const acyclic=design();acyclic.measures.push({id:'a',name:'A',businessDefinition:'A',aggregation:'RATIO',field:'',numeratorMeasureId:'revenue',denominatorMeasureId:'orders',format:'percentage'},{id:'b',name:'B',businessDefinition:'B',aggregation:'RATIO',field:'',numeratorMeasureId:'a',denominatorMeasureId:'orders',format:'percentage'});expect(()=>compilePowerBI(acyclic,data(),defaultTenantSettings)).not.toThrow()});
it.each([['DAY',null],['MONTH','Date.StartOfMonth'],['QUARTER','Date.StartOfQuarter'],['YEAR','Date.StartOfYear']] as const)('compiles and candidate-validates an explicit %s trend grain',(grain,mFunction)=>{const source=data(),plan=trendDesign(grain),candidate=compilePowerBI(plan,source,defaultTenantSettings),validation=validateGenericCandidate(candidate,plan,source),joined=Object.values(candidate.files).join('\n');expect(validation.checks.find(item=>item.id==='TIME_GRAIN_REPRESENTATION')?.status).toBe('PASS');expect(validation.status).toBe('PASS');if(mFunction){expect(joined).toContain(mFunction);expect(joined).toContain(`Orders.__APBRA_Date_${grain}_`)}else expect(joined).not.toContain('__APBRA_Date_DAY_')});
it('fails candidate validation when generated MONTH model or visual evidence is altered',()=>{const source=data(),plan=trendDesign('MONTH'),candidate=compilePowerBI(plan,source,defaultTenantSettings),tmdlPath='OrdersPerformance.SemanticModel/definition/tables/Orders.tmdl',visualPath=Object.keys(candidate.files).find(path=>path.endsWith('/visual.json')&&candidate.files[path].includes('__APBRA_Date_MONTH_'))!;candidate.files[tmdlPath]=candidate.files[tmdlPath].replace('Date.StartOfMonth','Date.From');expect(validateGenericCandidate(candidate,plan,source).checks.find(item=>item.id==='TIME_GRAIN_REPRESENTATION')?.status).toBe('FAIL');const fresh=compilePowerBI(plan,source,defaultTenantSettings),parsed=JSON.parse(fresh.files[visualPath]);parsed.visual.query.queryState.Category.projections[0].queryRef='Orders.Date';fresh.files[visualPath]=JSON.stringify(parsed);expect(validateGenericCandidate(fresh,plan,source).checks.find(item=>item.id==='TIME_GRAIN_REPRESENTATION')?.status).toBe('FAIL')});
it('rejects exact and case-variant generated time-grain column collisions in compilation and candidate validation',()=>{for(const transform of [(value:string)=>value,(value:string)=>value.toLowerCase()]){const source=data(),plan=trendDesign('MONTH'),candidate=compilePowerBI(plan,source,defaultTenantSettings),generated=Object.values(candidate.files).join('\n').match(/Orders\.(__APBRA_Date_MONTH_[a-f0-9]{8})/)![1],collision=transform(generated);source.tables[0].columns.push({name:collision,sourceName:collision,type:'date',nullable:false,sampleValues:['2026-01-01']});expect(()=>compilePowerBI(plan,source,defaultTenantSettings)).toThrow('TIME_GRAIN_COLUMN_COLLISION');expect(validateGenericCandidate(candidate,plan,source).checks.find(item=>item.id==='TIME_GRAIN_REPRESENTATION')?.status).toBe('FAIL')}});
it('rejects unsupported WEEK without falling through to YEAR and rejects non-date grain bindings',()=>{const week=trendDesign('DAY');week.pages[0].visuals[1].timeGrain='WEEK' as any;expect(()=>compilePowerBI(week,data(),defaultTenantSettings)).toThrow("UNSUPPORTED_TIME_GRAIN: WEEK for 'Orders.Date'");const wrong=trendDesign('MONTH');wrong.pages[0].visuals[1].categoryField='Orders.Region';expect(()=>compilePowerBI(wrong,data(),defaultTenantSettings)).toThrow('INVALID_TIME_GRAIN_FIELD')});
it('fails closed when configured or actual page capacity exceeds the compiler',()=>{const invalid=structuredClone(defaultTenantSettings);invalid.governance.maxVisualsPerPage=compilerCapabilities.maxVisualsPerPage+1;expect(()=>compilePowerBI(design(),data(),invalid)).toThrow('GENERATION_CONFIGURATION_INVALID');const constrained=structuredClone(defaultTenantSettings);constrained.governance.maxVisualsPerPage=2;expect(()=>compilePowerBI(design(),data(),constrained)).toThrow('VISUAL_CAPACITY_EXCEEDED');const overflow=design();overflow.pages[0].visuals=Array.from({length:compilerCapabilities.maxVisualsPerPage+1},(_,index)=>({...overflow.pages[0].visuals[0],id:`card-${index}`}));expect(()=>compilePowerBI(overflow,data(),defaultTenantSettings)).toThrow('VISUAL_CAPACITY_EXCEEDED')});
it('rejects an unsupported configured trend grain before compilation',()=>{const invalid=structuredClone(defaultTenantSettings);invalid.generation.supportedTrendGrains=['WEEK' as any];expect(()=>compilePowerBI(design(),data(),invalid)).toThrow('GENERATION_CONFIGURATION_INVALID')});
