import {expect,it} from 'vitest';
import {compilePowerBI,validateGenericCandidate} from './genericPowerBI';
import {defaultTenantSettings} from './tenant';
import type {DataStructure} from './schemaIngestion';
import type {ReportDesign} from './foundry';

const data=(name='Orders'):DataStructure=>({kind:'REQUEST_DATA_STRUCTURE',fileName:`${name}.csv`,format:'CSV',parsedAt:'2026-01-01',tables:[{name,sourceName:name,rowCount:2,rows:[['North','100','O1'],['South','200','O2']],columns:[{name:'Region',sourceName:'Region',type:'text',nullable:false,sampleValues:['North','South']},{name:'Revenue',sourceName:'Revenue',type:'integer',nullable:false,sampleValues:['100','200']},{name:'OrderId',sourceName:'OrderId',type:'text',nullable:false,sampleValues:['O1','O2']}]}],relationships:[]});
const design=(table='Orders'):ReportDesign=>({artifact_kind:'ReportDesign',schema_version:1,projectName:`${table}Performance`,overview:'Performance report',audience:'Leaders',dataModel:{factTables:[table],dimensionTables:[],relationships:[]},measures:[{id:'revenue',name:'Total Revenue',businessDefinition:'Revenue',aggregation:'SUM',field:`${table}.Revenue`,numeratorMeasureId:'',denominatorMeasureId:'',format:'currency'},{id:'orders',name:'Total Orders',businessDefinition:'Orders',aggregation:'DISTINCTCOUNT',field:`${table}.OrderId`,numeratorMeasureId:'',denominatorMeasureId:'',format:'integer'}],pages:[{id:'summary',name:'Summary',purpose:'Overview',visuals:[{id:'card',type:'card',title:'Total Revenue',categoryField:'',measureIds:['revenue'],fields:[],altText:'Total revenue'},{id:'region',type:'bar',title:'Revenue by region',categoryField:`${table}.Region`,measureIds:['revenue'],fields:[],altText:'Revenue by region'},{id:'filter',type:'slicer',title:'Region',categoryField:`${table}.Region`,measureIds:[],fields:[`${table}.Region`],altText:'Region filter'}]}],filters:[`${table}.Region`],branding:{themeName:'Tenant',primary:'#005A9C',accent:'#2D7D9A'},accessibility:['Titles'],standardsApplied:[{citation:'local:test#1',decision:'Use standard visuals'}],assumptions:[],warnings:[],generationRequirements:[]});
it('compiles a structured generic design into validated PBIP/PBIR source',()=>{const source=data(),plan=design(),candidate=compilePowerBI(plan,source,defaultTenantSettings),validation=validateGenericCandidate(candidate,plan,source);expect(validation.status).toBe('PASS');expect(candidate.files['OrdersPerformance.pbip']).toContain('OrdersPerformance.Report');expect(Object.keys(candidate.files).filter(path=>path.endsWith('/visual.json'))).toHaveLength(3);expect(Object.values(candidate.files).join('\n')).toContain('SUM(Orders[Revenue])')});
it('produces materially different packages from different schema/design contracts',()=>{const first=compilePowerBI(design('Orders'),data('Orders'),defaultTenantSettings),second=compilePowerBI(design('Tickets'),data('Tickets'),defaultTenantSettings);expect(Object.keys(first.files)).not.toEqual(Object.keys(second.files));expect(second.files['TicketsPerformance.SemanticModel/definition/tables/Tickets.tmdl']).toContain('table Tickets')});
it('preserves Unicode request data through UTF-8 Base64 embedding',()=>{const source=data();source.tables[0].rows=[['Côte d’Ivoire — 日本','100','O1'],['München – café','200','O2']];const candidate=compilePowerBI(design(),source,defaultTenantSettings);const tmdl=candidate.files['OrdersPerformance.SemanticModel/definition/tables/Orders.tmdl'];const encoded=tmdl.match(/Binary.FromText\("([A-Za-z0-9+/=]+)"/)![1];const bytes=Uint8Array.from(atob(encoded),character=>character.charCodeAt(0));expect(new TextDecoder().decode(bytes)).toBe(candidate.files['data/Orders.csv']);expect(candidate.files['data/Orders.csv']).toContain('Côte d’Ivoire — 日本');});
it('fails deterministic validation when a generated reference is removed',()=>{const source=data(),plan=design(),candidate=compilePowerBI(plan,source,defaultTenantSettings);delete candidate.files['OrdersPerformance.Report/definition.pbir'];expect(validateGenericCandidate(candidate,plan,source).status).toBe('FAIL')});
