import React,{useEffect,useRef,useState} from 'react';
import {ApiError,authApi,casesApi,companiesApi,invitationsApi,membershipsApi,profileApi,type CaseAccess,type CaseRecord,type CaseSummary,type IdentityProviders,type IssuedInvitation,type Membership,type RequestVersion,type Session} from './api';
import {DurableConversation} from './durableConversation';

type Notice={tone:'info'|'error'|'success';text:string}|null;
export const protectedErrorMessage=(error:unknown)=>error instanceof ApiError&&error.status===404?'That report is unavailable or you no longer have access.':error instanceof ApiError&&error.code==='PROVIDER_UNAVAILABLE'?'The sign-in provider is unavailable. Please try again later.':error instanceof ApiError&&error.code==='OIDC_RESPONSE_INVALID'?'Sign-in could not be validated. Please try again.':error instanceof ApiError&&error.status===401?'Your APBRA session has expired. Sign in again to continue.':error instanceof ApiError&&error.code==='STALE_VERSION'?'This report changed in another session. Reload it before saving your changes.':error instanceof ApiError&&error.code==='LAST_OWNER_REQUIRED'?'A company must retain an active Company Owner. This owner cannot be deactivated or changed here.':error instanceof Error?error.message:'The request could not be completed.';
export const companyCreationErrorMessage=(error:unknown)=>error instanceof ApiError&&error.status===401?'Your APBRA session has expired. Sign in again to continue.':error instanceof ApiError&&error.code==='COMPANY_NAME_INVALID'?'Enter a company name of up to 200 characters without control characters.':error instanceof ApiError&&error.code==='COMPANY_CREATION_NOT_AVAILABLE'?'Your company access changed. Review your current company or invitation state.':error instanceof ApiError&&error.code==='IDEMPOTENCY_CONFLICT'?'This creation attempt was already used with a different name. Review the name before trying again.':'Company creation could not be completed. Please try again.';
export const profileErrorMessage=(error:unknown)=>error instanceof ApiError&&error.status===401?'Your APBRA session has expired. Sign in again to continue.':error instanceof ApiError&&error.code==='PROFILE_INVALID'?'Enter a display name of up to 200 characters without control characters.':'Your profile could not be saved. Please try again.';
export const clearedCompanyContext=()=>({active:null as CaseRecord|null,versions:[] as RequestVersion[],draft:'',cases:[] as CaseSummary[],view:'home' as const,caseReportReady:false,newRequest:''});
export const createKey=()=>crypto.randomUUID();

export function SignedOut({message,providers}:{message?:string;providers?:IdentityProviders}){
  const options=providers?.items??[];
  return <main className="auth-page"><div className="auth-shell"><section className="auth-story" aria-label="APBRA reporting workspace"><div className="auth-brand"><span className="brand-mark" aria-hidden="true">A</span><strong>APBRA</strong></div><div className="auth-story-body"><span className="eyebrow">A clearer way to report</span><p className="auth-story-headline">From a business question to a report you can review.</p><p>Bring the goal, supporting information, decisions and report history together in one private workspace.</p><div className="auth-story-steps"><span><strong>01</strong> Describe your goal</span><span><strong>02</strong> Review the meaning</span><span><strong>03</strong> Build a candidate</span></div></div><div className="auth-story-footer">A private, deliberate reporting journey</div></section><section className="auth-card"><div className="auth-card-top"><span className="auth-lock" aria-hidden="true">◈</span><span>Private reporting workspace</span></div><p className="eyebrow">Welcome to APBRA</p><h1>Sign in to continue</h1><p>{message??'Your external identity establishes who you are. APBRA still checks active company membership and private-case access for every protected action.'}</p>{options.length?options.map(provider=><a key={provider.profile_id} className="primary-link" href={authApi.loginUrl({profileId:provider.profile_id})}>Sign in with {provider.display_label} <span aria-hidden="true">→</span></a>):<p role="status">No qualified sign-in provider is available. Contact the APBRA operator.</p>}{Boolean(providers?.development_identities.length)&&<details><summary>Local development identities</summary><div className="dev-identities">{providers?.development_identities.map(identity=><a key={identity} href={authApi.loginUrl({profileId:'local-test',identity})}>{identity}</a>)}</div></details>}</section></div></main>
}

export function CompanyCreationForm({name,onName,onCreate,busy}:{name:string;onName:(value:string)=>void;onCreate:()=>void;busy:boolean}){
  return <form className="company-creation-form" onSubmit={event=>{event.preventDefault();onCreate()}}><label htmlFor="company-name">Company or workspace name</label><input id="company-name" name="companyName" type="text" autoComplete="organization" required value={name} onChange={event=>onName(event.target.value)} placeholder="Name your workspace"/><p>This name helps people recognise the workspace. It does not verify legal or domain ownership.</p><button type="submit" disabled={busy||!name.trim()}>{busy?'Creating company…':'Create Company / Workspace'}</button></form>;
}

export function CompanySelection({companies,busy,onSelect}:{companies:NonNullable<Session['available_companies']>;busy:boolean;onSelect:(membershipId:string)=>void}){
  return <div className="company-selection">{companies.map(company=><button type="button" key={company.membership_id} disabled={busy} onClick={()=>onSelect(company.membership_id)}><strong>{company.name}</strong><small>Workspace ID: {company.company_id}</small></button>)}</div>;
}

function ProfileEditor({displayName,csrfToken,onUpdated,onError}:{displayName:string;csrfToken:string;onUpdated:()=>Promise<void>;onError:(error:unknown)=>void}){
  const [draft,setDraft]=useState(displayName),[busy,setBusy]=useState(false);
  useEffect(()=>setDraft(displayName),[displayName]);
  async function save(){const value=draft.trim();if(!value||value===displayName)return;setBusy(true);try{await profileApi.update(value,csrfToken);await onUpdated()}catch(error){onError(error)}finally{setBusy(false)}}
  return <details className="profile-editor"><summary>My profile</summary><form onSubmit={event=>{event.preventDefault();void save()}}><label htmlFor="profile-display-name">Display name</label><input id="profile-display-name" value={draft} onChange={event=>setDraft(event.target.value)}/><p>Your display name is editable. It does not change your sign-in identity, company role or private report access.</p><button type="submit" disabled={busy||!draft.trim()||draft.trim()===displayName}>{busy?'Saving profile…':'Save profile'}</button></form></details>;
}

export function CaseList({items,activeId,onOpen}:{items:CaseSummary[];activeId?:string;onOpen:(id:string)=>void}){
  return <section className="case-list" aria-labelledby="case-list-title"><div className="section-title"><div><span className="eyebrow">Your private work</span><h2 id="case-list-title">My reports</h2><p>Reports available to your current membership.</p></div><span className="status-badge">{items.length} total</span></div>{items.length===0?<div className="empty-state"><span className="empty-state-icon" aria-hidden="true">▤</span><h3>No reports in progress</h3><p>Start with a business question. Your work will appear here when you create a report.</p></div>:<ul>{items.map(item=><li key={item.id}><button className={item.id===activeId?'case-row active':'case-row'} aria-current={item.id===activeId?'page':undefined} onClick={()=>onOpen(item.id)}><span className="case-row-icon" aria-hidden="true">▤</span><span className="case-row-copy"><strong>{item.report_title??item.current_request.request_text}</strong><small>Updated {new Date(item.updated_at).toLocaleDateString()} <span aria-hidden="true">·</span> Request v{item.version}</small></span><span className="case-row-arrow" aria-hidden="true">→</span></button></li>)}</ul>}</section>
}

export function CaseEditor({record,versions,requestText,onRequestText,onSave,onRefresh,busy}:{record:CaseRecord;versions:RequestVersion[];requestText:string;onRequestText:(value:string)=>void;onSave:()=>void;onRefresh:()=>void;busy:boolean}){
  return <section className="case-editor" aria-labelledby="case-goal-title"><div className="section-title"><div><span className="eyebrow">Step 1 · Goal</span><h2 id="case-goal-title">Your reporting goal</h2><p>Keep the question accurate before you review APBRA’s understanding.</p></div><button className="subtle" disabled={busy} onClick={onRefresh}>Reload report</button></div><div className="goal-editor"><label htmlFor="case-request-edit">Current business request</label><textarea id="case-request-edit" rows={5} maxLength={12000} value={requestText} onChange={event=>onRequestText(event.target.value)}/><div className="goal-editor-footer"><span>Edits create a new saved version and require a fresh confirmation.</span><button disabled={busy||!requestText.trim()||requestText===record.current_request.request_text} onClick={onSave}>{busy?'Saving…':'Save new version'}</button></div></div><details className="request-history"><summary>Earlier request versions · {versions.length||1}</summary><ol className="version-history">{(versions.length?versions:[record.current_request]).map(version=><li key={version.id}><strong>Version {version.sequence}</strong><time>{new Date(version.created_at).toLocaleString()}</time><p>{version.request_text}</p></li>)}</ol></details><details className="expert-details"><summary>Details for experts</summary><p>Case reference: {record.id}. Current request version: {record.version}. Saved request versions remain immutable.</p></details></section>
}

export const reportJourneySteps=['Goal','Information','Understanding','Confirm','Build','Report'] as const;
export type ReportJourneyStep='goal'|'information'|'understanding'|'confirm'|'build'|'report';
const journeyStepKeys:ReportJourneyStep[]=['goal','information','understanding','confirm','build','report'];
const journeyDescriptions=[
  'Keep your saved business question accurate. Save any changes before reviewing the understanding.',
  'Add the data and reference material that explain your goal.',
  'Review the proposed meaning and answer any useful questions.',
  'Check the exact understanding before you choose to confirm it.',
  'Review the report design, then choose whether to build a candidate.',
  'Review the build result and download an available candidate for inspection.',
];

export function ReportCreationWizard({goal,children,hasUnsavedGoal=false}:{goal:React.ReactNode;children:(step:Exclude<ReportJourneyStep,'goal'>)=>React.ReactNode;hasUnsavedGoal?:boolean}){
  const [step,setStep]=useState<ReportJourneyStep>('goal');
  const heading=useRef<HTMLHeadingElement>(null),initialStep=useRef(true);
  const index=journeyStepKeys.indexOf(step);
  useEffect(()=>{if(initialStep.current){initialStep.current=false;return}heading.current?.focus()},[step]);
  return <section className="report-wizard" aria-label="Create your report">
    <nav aria-label="Report steps"><ol className="journey-steps">{reportJourneySteps.map((label,position)=><li key={label} className={position===index?'active':'available'}><button type="button" aria-current={position===index?'step':undefined} onClick={()=>setStep(journeyStepKeys[position])}><span className="step-number" aria-hidden="true">{position+1}</span><span className="step-copy"><small>{position===index?'Viewing':'Open step'}</small><strong>{label}</strong></span></button></li>)}</ol></nav>
    <div className="wizard-step-heading"><span className="eyebrow">Step {index+1} of {reportJourneySteps.length}</span><h2 ref={heading} tabIndex={-1}>{reportJourneySteps[index]}</h2><p>{journeyDescriptions[index]}</p></div>
    {hasUnsavedGoal&&<p className="state-callout warning" role="status">Your goal has unsaved changes. Return to Goal and save the new version before reviewing the updated requirements.</p>}
    <div hidden={step!=='goal'}>{goal}</div>
    <div hidden={step==='goal'}>{children(step==='goal'?'information':step)}</div>
    <div className="wizard-navigation"><button type="button" className="subtle" disabled={index===0} onClick={()=>setStep(journeyStepKeys[index-1])}>Back</button><p>Moving between steps keeps your work. Use each step’s action to save, review, confirm or build.</p><button type="button" disabled={index===journeyStepKeys.length-1} onClick={()=>setStep(journeyStepKeys[index+1])}>{index===journeyStepKeys.length-1?'Last step':`Next: ${reportJourneySteps[index+1]}`}</button></div>
  </section>;
}

export type ColorMode='light'|'dark'|'system';
export const personalColorMode=(value:unknown):ColorMode=>value==='light'||value==='dark'?value:'system';
const colorModeStorageKey='apbra-personal-color-mode';

type WorkspaceIconName='home'|'create'|'reports'|'current'|'profile'|'settings'|'lock'|'menu';
function WorkspaceIcon({name}:{name:WorkspaceIconName}){
  const paths:Record<WorkspaceIconName,React.ReactNode>={
    home:<><path d="m3 10 9-7 9 7"/><path d="M5 9v12h14V9M9 21v-7h6v7"/></>,
    create:<><path d="M12 4v16M4 12h16"/></>,
    reports:<><rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 16v-3m4 3V8m4 8v-5"/></>,
    current:<><path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9zM14 3v6h6M8 13h8m-8 4h6"/></>,
    profile:<><circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></>,
    settings:<><path d="M4 6h16M4 12h16M4 18h16M8 3v6m8 0v6m-6 0v6"/></>,
    lock:<><rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></>,
    menu:<><path d="M4 6h16M4 12h16M4 18h16"/></>,
  };
  return <svg className="workspace-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" focusable="false">{paths[name]}</svg>;
}

function InvitationAdmin({csrfToken,currentMembershipId,currentRole,onError}:{csrfToken:string;currentMembershipId:string;currentRole:string;onError:(error:unknown)=>void}){
  const [subject,setSubject]=useState(''),[role,setRole]=useState<'COMPANY_ADMIN'|'MEMBER'|'EXPERT'>('MEMBER'),[issued,setIssued]=useState<IssuedInvitation|null>(null),[members,setMembers]=useState<Membership[]>([]),[busy,setBusy]=useState(false),[roleDrafts,setRoleDrafts]=useState<Record<string,'MEMBER'|'COMPANY_ADMIN'>>({});
  const refresh=async()=>setMembers((await membershipsApi.list()).items);
  useEffect(()=>{void refresh().catch(onError)},[]);
  async function issue(){if(!subject.trim())return;setBusy(true);try{setIssued(await invitationsApi.issue(subject.trim(),role,csrfToken));setSubject('')}catch(error){onError(error)}finally{setBusy(false)}}
  async function revoke(){if(!issued)return;setBusy(true);try{await invitationsApi.revoke(issued.invitation.id,csrfToken);setIssued(null)}catch(error){onError(error)}finally{setBusy(false)}}
  async function deactivate(membershipId:string){setBusy(true);try{await membershipsApi.deactivate(membershipId,csrfToken);await refresh()}catch(error){onError(error)}finally{setBusy(false)}}
  async function changeRole(membershipId:string,nextRole:'MEMBER'|'COMPANY_ADMIN'){setBusy(true);try{await membershipsApi.changeRole(membershipId,nextRole,csrfToken);await refresh()}catch(error){onError(error)}finally{setBusy(false)}}
  const inviteLink=issued?`${window.location.origin}/invite#token=${encodeURIComponent(issued.token)}`:'';
  return <section className="panel invitation-admin"><h2>Company access</h2><p>Create a single-use APBRA membership invitation for an exact subject at your qualified identity provider. The bearer link is displayed only in this current view.</p><div className="form-grid"><label>External subject<input value={subject} onChange={event=>setSubject(event.target.value)} placeholder="Exact provider subject"/></label><label>Application role<select value={role} onChange={event=>setRole(event.target.value as typeof role)}><option value="MEMBER">Member</option><option value="EXPERT">Expert</option><option value="COMPANY_ADMIN">Company admin</option></select></label></div><button disabled={busy||!subject.trim()} onClick={()=>void issue()}>Issue invitation</button>{issued&&<div className="issued-invitation" role="status"><label>One-time invitation link<input readOnly value={inviteLink}/></label><p>Expires {new Date(issued.invitation.expires_at).toLocaleString()}.</p><button className="subtle" disabled={busy} onClick={()=>void revoke()}>Revoke invitation</button></div>}<h3>Memberships</h3><ul className="membership-list">{members.map(member=><li key={member.id}><span><strong>{member.display_name}</strong><small>{member.subject} · {member.role.replaceAll('_',' ')} · {member.active?'Active':'Deactivated'}</small></span>{member.active&&member.id!==currentMembershipId&&member.role!=='COMPANY_OWNER'&&<button className="subtle" disabled={busy} onClick={()=>void deactivate(member.id)}>Deactivate</button>}{currentRole==='COMPANY_OWNER'&&member.active&&['MEMBER','COMPANY_ADMIN'].includes(member.role)&&<div className="member-role-control"><label htmlFor={`member-role-${member.id}`}>Role for {member.display_name}</label><select id={`member-role-${member.id}`} value={roleDrafts[member.id]??member.role} disabled={busy} onChange={event=>setRoleDrafts(previous=>({...previous,[member.id]:event.target.value as 'MEMBER'|'COMPANY_ADMIN'}))}><option value="MEMBER">Member</option><option value="COMPANY_ADMIN">Company admin</option></select><button className="subtle" disabled={busy||!roleDrafts[member.id]||roleDrafts[member.id]===member.role} onClick={()=>void changeRole(member.id,roleDrafts[member.id])}>Save role</button></div>}</li>)}</ul></section>
}

function CaseAccessAdmin({record,csrfToken,currentMembershipId,onError}:{record:CaseRecord;csrfToken:string;currentMembershipId:string;onError:(error:unknown)=>void}){
  const [access,setAccess]=useState<CaseAccess[]>([]),[members,setMembers]=useState<Membership[]>([]),[selected,setSelected]=useState(''),[level,setLevel]=useState<'EDITOR'|'VIEWER'>('VIEWER'),[busy,setBusy]=useState(false);
  const refresh=async()=>{const [accessResult,memberResult]=await Promise.all([casesApi.access(record.id),membershipsApi.list()]);setAccess(accessResult.items);setMembers(memberResult.items)};
  useEffect(()=>{void refresh().catch(onError)},[record.id]);
  async function grant(){if(!selected)return;setBusy(true);try{await casesApi.grantAccess(record.id,selected,level,csrfToken);setSelected('');await refresh()}catch(error){onError(error)}finally{setBusy(false)}}
  async function revoke(membershipId:string){setBusy(true);try{await casesApi.revokeAccess(record.id,membershipId,csrfToken);await refresh()}catch(error){onError(error)}finally{setBusy(false)}}
  const granted=new Set(access.filter(item=>item.active).map(item=>item.membership_id)),available=members.filter(item=>item.active&&item.id!==currentMembershipId&&!granted.has(item.id));
  return <section className="panel case-access-admin"><h2>Private report access</h2><p>The report remains private. Grant a named active company member view or edit access; company membership alone is insufficient.</p><div className="form-grid"><label>Company member<select value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Select a member</option>{available.map(member=><option key={member.id} value={member.id}>{member.display_name} · {member.subject}</option>)}</select></label><label>Report permission<select value={level} onChange={event=>setLevel(event.target.value as typeof level)}><option value="VIEWER">View</option><option value="EDITOR">Edit</option></select></label></div><button disabled={busy||!selected} onClick={()=>void grant()}>Grant report access</button><h3>Current access</h3><ul className="membership-list">{access.filter(item=>item.active).map(item=><li key={item.membership_id}><span><strong>{item.display_name}</strong><small>{item.subject} · {item.access_level.toLowerCase()}</small></span>{item.access_level!=='OWNER'&&<button className="subtle" disabled={busy} onClick={()=>void revoke(item.membership_id)}>Revoke</button>}</li>)}</ul></section>
}

export function PrivateCaseWorkspace({adminPanel}:{adminPanel?:(membershipId:string)=>React.ReactNode}={}){
  const [colorMode,setColorMode]=useState<ColorMode>('system');
  const [navigationOpen,setNavigationOpen]=useState(false);
  const navigationToggle=useRef<HTMLButtonElement>(null);
  useEffect(()=>{
    const narrow=window.matchMedia('(max-width:768px)');
    const closeOnDesktop=()=>{if(!narrow.matches)setNavigationOpen(false)};
    narrow.addEventListener('change',closeOnDesktop);
    return()=>narrow.removeEventListener('change',closeOnDesktop);
  },[]);
  useEffect(()=>{try{setColorMode(personalColorMode(localStorage.getItem(colorModeStorageKey)))}catch{/* Browser appearance remains available when storage is blocked. */}},[]);
  function changeColorMode(value:string){const mode=personalColorMode(value);setColorMode(mode);try{localStorage.setItem(colorModeStorageKey,mode)}catch{/* The current view still uses the selected appearance. */}}
  const [session,setSession]=useState<Session|null>(null),[providers,setProviders]=useState<IdentityProviders|null>(null),[loading,setLoading]=useState(true),[cases,setCases]=useState<CaseSummary[]>([]),[active,setActive]=useState<CaseRecord|null>(null),[caseReportReady,setCaseReportReady]=useState(false),[versions,setVersions]=useState<RequestVersion[]>([]),[draft,setDraft]=useState(''),[newRequest,setNewRequest]=useState(''),[companyName,setCompanyName]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState<Notice>(null),[invitation,setInvitation]=useState<string|null>(null),[view,setView]=useState<'home'|'create'|'reports'|'case'|'admin'|'profile'>('home');const createRequest=useRef<{text:string;key:string}|null>(null),companyRequest=useRef<{name:string;key:string}|null>(null),openRequest=useRef(0),contextEpoch=useRef(0);
  const clearCompanyContext=()=>{const cleared=clearedCompanyContext();contextEpoch.current+=1;openRequest.current+=1;createRequest.current=null;setActive(cleared.active);setVersions(cleared.versions);setDraft(cleared.draft);setCases(cleared.cases);setView(cleared.view);setCaseReportReady(cleared.caseReportReady);setNewRequest(cleared.newRequest)};
  const expire=(error:unknown)=>{if(error instanceof ApiError&&error.status===401){clearCompanyContext();setSession({authenticated:false})}setNotice({tone:'error',text:protectedErrorMessage(error)})};
  const profileError=(error:unknown)=>{if(error instanceof ApiError&&error.status===401)expire(error);else setNotice({tone:'error',text:profileErrorMessage(error)})};
  const loadCases=async()=>{const epoch=contextEpoch.current,result=await casesApi.list();if(epoch===contextEpoch.current)setCases(result.items)};
  const openCase=async(id:string)=>{const request=++openRequest.current;setBusy(true);setNotice(null);try{const [record,history]=await Promise.all([casesApi.get(id),casesApi.versions(id)]);if(request!==openRequest.current)return;setCaseReportReady(false);setActive(record);setDraft(record.current_request.request_text);setVersions(history.items);setView('case')}catch(error){if(request===openRequest.current)expire(error)}finally{if(request===openRequest.current)setBusy(false)}};
  useEffect(()=>{let current=true;const fragment=new URLSearchParams(window.location.hash.replace(/^#/,'')),token=fragment.get('token'),query=new URLSearchParams(window.location.search),authError=query.get('auth_error');if(token){setInvitation(token);history.replaceState({},'',location.pathname+location.search)}if(authError){setNotice({tone:'error',text:authError==='cancelled'?'Sign-in was cancelled. Please try again.':authError==='unavailable'?'The sign-in provider is unavailable. Please try again later.':'Sign-in could not be completed. Please try again.'});query.delete('auth_error');history.replaceState({},'',location.pathname+(query.toString()?`?${query}`:'')+location.hash)}void Promise.all([authApi.session(),authApi.providers()]).then(async([value,options])=>{if(!current)return;setSession(value);setProviders(options);if(value.actor)await loadCases()}).catch(error=>{if(current)setNotice({tone:'error',text:protectedErrorMessage(error)})}).finally(()=>{if(current)setLoading(false)});return()=>{current=false}},[]);
  async function createCase(){const text=newRequest.trim();if(!text||!session?.csrf_token)return;const epoch=contextEpoch.current;setBusy(true);setNotice(null);if(!createRequest.current||createRequest.current.text!==text)createRequest.current={text,key:createKey()};try{const record=await casesApi.create(text,createRequest.current.key,session.csrf_token);if(epoch!==contextEpoch.current)return;createRequest.current=null;setNewRequest('');await loadCases();if(epoch!==contextEpoch.current)return;await openCase(record.id);if(epoch===contextEpoch.current)setNotice({tone:'success',text:'Report request created and saved.'})}catch(error){if(epoch===contextEpoch.current)expire(error)}finally{setBusy(false)}}
  async function createCompany(){
    const name=companyName.trim();
    if(!name||!session?.csrf_token||session.membership_state!=='COMPANY_CREATION_AVAILABLE'||busy)return;
    setBusy(true);setNotice(null);
    if(!companyRequest.current||companyRequest.current.name!==name)companyRequest.current={name,key:createKey()};
    let creationAcknowledged=false;
    try{
      await companiesApi.create(name,companyRequest.current.key,session.csrf_token);
      creationAcknowledged=true;
      clearCompanyContext();
      const value=await authApi.session();setSession(value);
      if(!value.actor)throw new Error('The new company session is not yet available.');
      companyRequest.current=null;setCompanyName('');
      try{await loadCases();setNotice({tone:'success',text:'Your company workspace is ready. You are its Company Owner.'})}
      catch{setNotice({tone:'info',text:'Your company workspace is ready, but reports could not be loaded. Refresh to try again.'})}
    }catch(error){
      if(error instanceof ApiError&&error.code==='COMPANY_CREATION_NOT_AVAILABLE'){
        try{const value=await authApi.session();setSession(value);if(value.actor)await loadCases()}catch{/** Keep the original bounded error. */}
      }
      if(error instanceof ApiError&&error.status===401)expire(error);
      else setNotice({tone:'error',text:creationAcknowledged?'Your company may be ready, but the session could not be refreshed. Reload to check before trying again.':companyCreationErrorMessage(error)});
    }finally{setBusy(false)}
  }
  async function refreshProfile(){const value=await authApi.session();if(session?.actor?.membership_id!==value.actor?.membership_id)clearCompanyContext();setSession(value)}
  async function save(){if(!active||!session?.csrf_token||!draft.trim())return;const epoch=contextEpoch.current;setBusy(true);setNotice(null);try{const record=await casesApi.update(active.id,draft.trim(),active.version,session.csrf_token);if(epoch!==contextEpoch.current)return;setActive(record);setDraft(record.current_request.request_text);const history=await casesApi.versions(record.id);if(epoch!==contextEpoch.current)return;setVersions(history.items);await loadCases();if(epoch===contextEpoch.current)setNotice({tone:'success',text:'Your updated request was saved.'})}catch(error){if(epoch===contextEpoch.current)expire(error)}finally{setBusy(false)}}
  async function acceptInvitation(){if(!invitation||!session?.csrf_token)return;setBusy(true);try{await invitationsApi.accept(invitation,session.csrf_token);clearCompanyContext();history.replaceState({},'',location.pathname);setInvitation(null);const value=await authApi.session();setSession(value);if(value.actor)await loadCases();setNotice({tone:'success',text:'Invitation accepted. Your APBRA membership is active.'})}catch(error){expire(error)}finally{setBusy(false)}}
  async function logout(){if(!session?.csrf_token)return;setBusy(true);try{await authApi.logout(session.csrf_token);clearCompanyContext();setSession({authenticated:false})}catch(error){expire(error)}finally{setBusy(false)}}
  async function selectCompany(membershipId:string){if(!session?.csrf_token)return;setBusy(true);try{await authApi.selectCompany(membershipId,session.csrf_token);clearCompanyContext();const value=await authApi.session();setSession(value);if(value.actor)await loadCases()}catch(error){expire(error)}finally{setBusy(false)}}
  if(loading)return <main className="auth-page"><section className="auth-card"><span className="brand-mark" aria-hidden="true">A</span><p role="status">Checking secure APBRA session…</p></section></main>;
  if(!session?.authenticated)return <SignedOut providers={providers??undefined} message={notice?.text??(invitation?'Sign in, then reopen the original invitation link to accept it. The invitation secret is not stored in this browser or included in the sign-in return URL.':undefined)}/>;
  if(!session.actor)return <main className="auth-page"><section className="auth-card"><span className="brand-mark">A</span><p className="eyebrow">Authenticated identity</p><h1>{invitation?'Accept your invitation':session.membership_state==='COMPANY_SELECTION_REQUIRED'?'Choose your company':session.membership_state==='INVITATION_AVAILABLE'?'Open your invitation':session.membership_state==='MEMBERSHIP_INACTIVE'?'Company access is inactive':'Create Company / Workspace'}</h1><p>{invitation?'APBRA will bind this identity to the exact company and role named by the single-use invitation.':session.membership_state==='COMPANY_SELECTION_REQUIRED'?'Choose one of your active APBRA memberships. This selection cannot grant a new membership or private report access.':session.membership_state==='INVITATION_AVAILABLE'?'An invitation is available for this identity. Reopen the original invitation link, or ask the inviter to send it again. APBRA will not join a company automatically.':session.membership_state==='MEMBERSHIP_INACTIVE'?'Your previous company membership is no longer active. Ask a company administrator for help.':'Your identity has no active APBRA company membership or pending invitation. You can create a private workspace now.'}</p>{notice&&<div className={`workspace-notice ${notice.tone}`} role={notice.tone==='error'?'alert':'status'}>{notice.text}</div>}{session.membership_state==='COMPANY_SELECTION_REQUIRED'&&session.available_companies&&<CompanySelection companies={session.available_companies} busy={busy} onSelect={membershipId=>void selectCompany(membershipId)}/> }{invitation&&<button disabled={busy} onClick={()=>void acceptInvitation()}>Accept invitation</button>}{session.membership_state==='COMPANY_CREATION_AVAILABLE'&&!invitation&&<CompanyCreationForm name={companyName} onName={value=>{setCompanyName(value);if(companyRequest.current?.name!==value.trim())companyRequest.current=null}} onCreate={()=>void createCompany()} busy={busy}/>} {session.identity&&session.csrf_token&&<ProfileEditor displayName={session.identity.display_name} csrfToken={session.csrf_token} onUpdated={refreshProfile} onError={profileError}/>}<button className="subtle" disabled={busy} onClick={()=>void logout()}>Sign out</button></section></main>;
  const canInvite=['COMPANY_OWNER','COMPANY_ADMIN'].includes(session.actor?.role??'');
  const createPanel=<section id="new-report" className="new-report-card" aria-labelledby="new-report-title"><div className="composer-topline"><span className="eyebrow">Start a new report</span><span className="composer-icon" aria-hidden="true">✦</span></div><h2 id="new-report-title">What would you like to understand?</h2><p>Describe your business question in your own words. You can refine it and add a CSV or XLSX file after creating the report.</p><label htmlFor="new-case-request">Your reporting goal</label><textarea id="new-case-request" rows={5} maxLength={12000} placeholder="For example: Which parts of our operation are changing, and where should we focus next?" value={newRequest} onChange={event=>{setNewRequest(event.target.value);if(createRequest.current?.text!==event.target.value.trim())createRequest.current=null}}/><div className="composer-footer"><span>Private to you until you grant access</span><button disabled={busy||!newRequest.trim()} onClick={()=>void createCase()}>{busy?'Creating report…':'Create report'}<span aria-hidden="true">→</span></button></div></section>;
  const casesPanel=<CaseList items={cases} activeId={active?.id} onOpen={id=>void openCase(id)}/>;
  return <div className="private-workspace" data-theme="clear-glass" data-color-mode={colorMode} data-navigation-open={navigationOpen}>
    <a className="skip-link" href="#workspace-main">Skip to reporting workspace</a>
    <aside id="workspace-navigation" className="workspace-rail" aria-label="Application navigation" onClickCapture={event=>{if((event.target as Element).closest("nav button")){if(navigationOpen)document.getElementById("workspace-main")?.focus();setNavigationOpen(false)}}} onKeyDown={event=>{if(event.key==="Escape"&&navigationOpen){setNavigationOpen(false);navigationToggle.current?.focus()}}}><div className="rail-brand"><button ref={navigationToggle} type="button" className="workspace-menu-toggle subtle" aria-label={navigationOpen?"Close workspace navigation":"Open workspace navigation"} title={navigationOpen?"Close workspace navigation":"Open workspace navigation"} aria-expanded={navigationOpen} aria-controls="workspace-navigation" onClick={()=>setNavigationOpen(open=>!open)}><WorkspaceIcon name="menu"/></button><span className="brand-mark" aria-hidden="true">A</span><div><strong>APBRA</strong><small>Reporting workspace</small></div></div><div className="rail-section-label">Workspace</div><nav aria-label="Workspace sections"><button className={view==='home'?'rail-link active':'rail-link'} aria-current={view==='home'?'page':undefined} onClick={()=>setView('home')}><WorkspaceIcon name="home"/>Home</button><button className={view==='create'?'rail-link active':'rail-link'} aria-current={view==='create'?'page':undefined} onClick={()=>setView('create')}><WorkspaceIcon name="create"/>Create report</button><button className={view==='reports'?'rail-link active':'rail-link'} aria-current={view==='reports'?'page':undefined} onClick={()=>setView('reports')}><WorkspaceIcon name="reports"/>My reports <small>{cases.length}</small></button>{active&&<button className={view==='case'?'rail-link active':'rail-link'} aria-current={view==='case'?'page':undefined} onClick={()=>setView('case')}><WorkspaceIcon name="current"/>Current report</button>}</nav><div className="rail-section-label">Account</div><nav aria-label="Account sections"><button className={view==='profile'?'rail-link active':'rail-link'} aria-current={view==='profile'?'page':undefined} onClick={()=>setView('profile')}><WorkspaceIcon name="profile"/>My profile</button>{canInvite&&<button className={view==='admin'?'rail-link active':'rail-link'} aria-current={view==='admin'?'page':undefined} onClick={()=>setView('admin')}><WorkspaceIcon name="settings"/>Administration</button>}</nav><div className="rail-footer"><span className="rail-privacy"><WorkspaceIcon name="lock"/></span><div><strong>Private workspace</strong><small>Access checked on every action</small></div></div></aside>
    <div className="workspace-frame"><header className="workspace-topbar"><div className="workspace-breadcrumb"><span>Workspace</span><span aria-hidden="true">/</span><strong>{view==='home'?'Home':view==='create'?'Create report':view==='reports'?'My reports':view==='admin'?'Administration':view==='profile'?'My profile':'Current report'}</strong></div><div className="account-controls"><label className="appearance-control">Appearance<select aria-label="Appearance" value={colorMode} onChange={event=>changeColorMode(event.target.value)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><span className="account-avatar" aria-hidden="true">{session.actor.display_name.slice(0,1).toUpperCase()}</span><div><strong>{session.actor.display_name}</strong><span>{session.actor.role.replaceAll('_',' ').toLowerCase()}</span></div><button className="subtle" disabled={busy} onClick={()=>void logout()}>Sign out</button></div></header>
    <main id="workspace-main" className="case-content" tabIndex={-1}>
      {notice&&<div className={'workspace-notice '+notice.tone} role={notice.tone==='error'?'alert':'status'}>{notice.text}</div>}
      {invitation&&<section className="panel invitation-card"><h2>Accept company invitation</h2><p>This invitation links your signed-in identity to the named company membership.</p><button disabled={busy} onClick={()=>void acceptInvitation()}>Accept invitation</button></section>}
      {view==='home'&&<><div className="home-recent"><div className="section-title"><div><span className="eyebrow">Pick up where you left off</span><h1>Your reports</h1></div>{cases.length>0&&<button className="text-action" onClick={()=>setView('reports')}>View all <span aria-hidden="true">→</span></button>}</div>{casesPanel}</div><section className="workspace-hero"><div><span className="eyebrow">Your reporting workspace</span><h2>Start another report when you are ready</h2><p>Continue an existing report below, or start a new business question. Your requirements, files and history stay with each private report.</p><button onClick={()=>setView('create')}>Create report <span aria-hidden="true">→</span></button></div><div className="hero-metric" aria-label={`${cases.length} reports`}><span className="hero-metric-mark" aria-hidden="true">▥</span><strong>{cases.length.toString().padStart(2,'0')}</strong><span>Reports<br/>in your workspace</span></div></section><section className="workspace-guidance" aria-label="How reporting works"><span>01 <strong>Describe</strong> your question</span><span>02 <strong>Review</strong> the understanding</span><span>03 <strong>Build</strong> a private candidate</span></section></>}
      {view==='create'&&<><div className="page-heading"><div><span className="eyebrow">New report</span><h1>Start with your goal</h1><p>You do not need a report specification. Tell us what you want to learn, then add supporting information and review each decision.</p></div></div>{createPanel}<div className="next-step-note"><strong>What happens next?</strong><p>After creating the report, you can add a supported file, review APBRA’s understanding and confirm the exact meaning before a report can be built.</p></div></>}
      {view==='reports'&&<><div className="page-heading"><div><span className="eyebrow">Private reporting</span><h1>My reports</h1><p>Return to a report, review its current request and find earlier work.</p></div><button onClick={()=>setView('create')}>Create report <span aria-hidden="true">→</span></button></div>{casesPanel}</>}
      {view==='case'&&active&&<><div className="case-identity"><div><span className="eyebrow">Private report <span aria-hidden="true">·</span> Request v{active.version}</span><h1>{active.report_title??active.current_request.request_text}</h1><div className="case-meta"><span className={'status-badge '+(caseReportReady?'status-success':'status-info')}>{caseReportReady?'Candidate ready':'In progress'}</span><span>Updated {new Date(active.updated_at).toLocaleDateString()}</span><span>Only authorised members can open this report</span></div></div><button className="subtle" onClick={()=>setView('reports')}>All reports</button></div><div className="case-workspace-grid"><div className="workspace-primary"><ReportCreationWizard key={session.actor.membership_id+':'+active.id} hasUnsavedGoal={draft!==active.current_request.request_text} goal={<CaseEditor record={active} versions={versions} requestText={draft} onRequestText={setDraft} onSave={()=>void save()} onRefresh={()=>void openCase(active.id)} busy={busy}/>}>{visibleStep=>session.csrf_token&&<DurableConversation record={active} csrfToken={session.csrf_token} actorRole={session.actor?.role} visibleStep={visibleStep} onContextChanged={semantic_context_version=>{setCaseReportReady(false);setActive(current=>current&&current.id===active.id?{...current,semantic_context_version}:current)}} onReportReady={setCaseReportReady} onError={expire}/>}</ReportCreationWizard></div><aside className="case-context" aria-label="Report context"><div className="context-card"><span className="eyebrow">At a glance</span><h2>About this report</h2><dl><div><dt>Request version</dt><dd>{active.version}</dd></div><div><dt>Last updated</dt><dd>{new Date(active.updated_at).toLocaleDateString()}</dd></div><div><dt>Access</dt><dd>Private</dd></div></dl><p>Your requirements, supporting information and build history are saved with this report.</p></div>{canInvite&&active.creator_membership_id===session.actor.membership_id&&session.csrf_token&&<details className="workspace-admin"><summary>Manage private report access</summary><CaseAccessAdmin record={active} csrfToken={session.csrf_token} currentMembershipId={session.actor.membership_id} onError={expire}/></details>}</aside></div></>}
      {canInvite&&<div key={session.actor.membership_id} hidden={view!=='admin'}><div className="page-heading"><div><span className="eyebrow">Administration</span><h1>Company and account settings</h1><p>Manage company policy, access and your profile separately from report work.</p></div></div>{adminPanel?.(session.actor.membership_id)}{canInvite&&session.csrf_token&&session.actor&&<details className="workspace-admin company-admin"><summary>Manage company access</summary><InvitationAdmin csrfToken={session.csrf_token} currentMembershipId={session.actor.membership_id} currentRole={session.actor.role} onError={expire}/></details>}</div>}{view==='profile'&&<section className="panel"><h1>My profile</h1>{session.csrf_token&&session.identity&&<ProfileEditor displayName={session.identity.display_name} csrfToken={session.csrf_token} onUpdated={refreshProfile} onError={profileError}/>}</section>}
    </main></div>
  </div>
}
