import {expect,it} from 'vitest';
import {renderToStaticMarkup} from 'react-dom/server';
import {ApiError,type CaseRecord} from './api';
import {CaseEditor,CaseList,SignedOut,protectedErrorMessage} from './privateCases';

const record:CaseRecord={id:'case-1',company_id:'company-1',creator_membership_id:'member-1',current_request_version_id:'request-2',version:2,semantic_context_version:1,created_at:'2026-09-23T00:00:00Z',updated_at:'2026-09-23T01:00:00Z',current_request:{id:'request-2',sequence:2,request_text:'Updated business request',created_at:'2026-09-23T01:00:00Z'}};

it('renders a truthful signed-out boundary without company or role inputs',()=>{const html=renderToStaticMarkup(<SignedOut/>);expect(html).toContain('Sign in to continue');expect(html).toContain('checks active company membership and private-case access');expect(html).not.toMatch(/company id|select role/i)});
it('renders only supplied authorized case summaries with a clear selected state',()=>{const html=renderToStaticMarkup(<CaseList items={[record]} activeId="case-1" onOpen={()=>{}}/>);expect(html).toContain('Updated business request');expect(html).toContain('Request v2');expect(html).toContain('Reports available to your current membership.');expect(html).toContain('aria-current="page"')});
it('makes an empty workspace actionable without claiming a report exists',()=>{const html=renderToStaticMarkup(<CaseList items={[]} onOpen={()=>{}}/>);expect(html).toContain('No reports in progress');expect(html).toContain('Start with a business question');expect(html).not.toContain('aria-current="page"')});
it('renders immutable request history separately from the editable current request',()=>{const html=renderToStaticMarkup(<CaseEditor record={record} versions={[{id:'request-1',sequence:1,request_text:'Original business request',created_at:'2026-09-23T00:00:00Z'},record.current_request]} requestText={record.current_request.request_text} onRequestText={()=>{}} onSave={()=>{}} onRefresh={()=>{}} busy={false}/>);expect(html).toContain('Original business request');expect(html).toContain('Updated business request');expect(html).toContain('Earlier request versions · 2');expect(html).toContain('require a fresh confirmation');expect(html).not.toContain('expected_version')});
it('does not disclose whether a protected foreign or private report exists',()=>{expect(protectedErrorMessage(new ApiError(404,'CASE_NOT_FOUND','hidden'))).toBe('That report is unavailable or you no longer have access.');expect(protectedErrorMessage(new ApiError(401,'AUTH_REQUIRED','expired'))).toContain('session has expired');expect(protectedErrorMessage(new ApiError(409,'STALE_VERSION','stale'))).toContain('changed in another session')});
