import React,{useEffect,useRef,useState} from 'react';
import {ApiError,authApi,casesApi,invitationsApi,membershipsApi,type CaseAccess,type CaseRecord,type CaseSummary,type IssuedInvitation,type Membership,type RequestVersion,type Session} from './api';

type Notice={tone:'info'|'error'|'success';text:string}|null;
export const protectedErrorMessage=(error:unknown)=>error instanceof ApiError&&error.status===404?'That case is unavailable or you no longer have access.':error instanceof ApiError&&error.status===401?'Your APBRA session has expired. Sign in again to continue.':error instanceof ApiError&&error.code==='STALE_VERSION'?'This case changed in another session. Reload it before saving your changes.':error instanceof Error?error.message:'The request could not be completed.';
export const createKey=()=>crypto.randomUUID();

export function SignedOut({message}:{message?:string}){
  const local=typeof window!=='undefined'&&['localhost','127.0.0.1'].includes(window.location.hostname);
  return <main className="auth-page"><section className="auth-card"><span className="brand-mark">A</span><p className="eyebrow">APBRA secure workspace</p><h1>Sign in to continue</h1><p>{message??'Your external identity establishes who you are. APBRA still checks active company membership and private-case access for every protected action.'}</p><a className="primary-link" href={authApi.loginUrl(undefined,'/')}>Sign in</a>{local&&<details><summary>Local development identities</summary><div className="dev-identities">{['owner','member','uninvited','foreign'].map(identity=><a key={identity} href={authApi.loginUrl(identity,'/')}>{identity}</a>)}</div></details>}</section></main>
}

export function CaseList({items,activeId,onOpen}:{items:CaseSummary[];activeId?:string;onOpen:(id:string)=>void}){
  return <section className="panel case-list"><div className="section-title"><div><h2>Your reporting cases</h2><p>Only cases your current membership and private access permit are shown.</p></div><span className="status-badge">{items.length} case{items.length===1?'':'s'}</span></div>{items.length===0?<div className="empty-state"><h3>No reporting cases yet</h3><p>Create one from a business request. A project and file are optional.</p></div>:<ul>{items.map(item=><li key={item.id}><button className={item.id===activeId?'case-row active':'case-row'} onClick={()=>onOpen(item.id)}><span><strong>{item.current_request.request_text}</strong><small>Updated {new Date(item.updated_at).toLocaleString()} · version {item.version}</small></span><span aria-hidden="true">›</span></button></li>)}</ul>}</section>
}

export function CaseEditor({record,versions,requestText,onRequestText,onSave,onRefresh,busy}:{record:CaseRecord;versions:RequestVersion[];requestText:string;onRequestText:(value:string)=>void;onSave:()=>void;onRefresh:()=>void;busy:boolean}){
  return <section className="panel case-editor"><div className="section-title"><div><span className="eyebrow">Private reporting case</span><h2>Resume business request</h2><p>Case {record.id} · current version {record.version}</p></div><button className="subtle" disabled={busy} onClick={onRefresh}>Reload</button></div><label htmlFor="case-request-edit">Current business request</label><textarea id="case-request-edit" rows={6} maxLength={12000} value={requestText} onChange={event=>onRequestText(event.target.value)}/><div className="command-bar"><button disabled={busy||!requestText.trim()||requestText===record.current_request.request_text} onClick={onSave}>{busy?'Saving…':'Save new version'}</button></div><details><summary>Request history · {versions.length||1} immutable version{(versions.length||1)===1?'':'s'}</summary><ol className="version-history">{(versions.length?versions:[record.current_request]).map(version=><li key={version.id}><strong>Version {version.sequence}</strong><time>{new Date(version.created_at).toLocaleString()}</time><p>{version.request_text}</p></li>)}</ol></details></section>
}

function InvitationAdmin({csrfToken,currentMembershipId,onError}:{csrfToken:string;currentMembershipId:string;onError:(error:unknown)=>void}){
  const [subject,setSubject]=useState(''),[role,setRole]=useState<'COMPANY_ADMIN'|'MEMBER'|'EXPERT'>('MEMBER'),[issued,setIssued]=useState<IssuedInvitation|null>(null),[members,setMembers]=useState<Membership[]>([]),[busy,setBusy]=useState(false);
  const refresh=async()=>setMembers((await membershipsApi.list()).items);
  useEffect(()=>{void refresh().catch(onError)},[]);
  async function issue(){if(!subject.trim())return;setBusy(true);try{setIssued(await invitationsApi.issue(subject.trim(),role,csrfToken));setSubject('')}catch(error){onError(error)}finally{setBusy(false)}}
  async function revoke(){if(!issued)return;setBusy(true);try{await invitationsApi.revoke(issued.invitation.id,csrfToken);setIssued(null)}catch(error){onError(error)}finally{setBusy(false)}}
  async function deactivate(membershipId:string){setBusy(true);try{await membershipsApi.deactivate(membershipId,csrfToken);await refresh()}catch(error){onError(error)}finally{setBusy(false)}}
  const inviteLink=issued?`${window.location.origin}/invite#token=${encodeURIComponent(issued.token)}`:'';
  return <section className="panel invitation-admin"><h2>Company access</h2><p>Create a single-use local invitation for an exact external subject. The bearer link is displayed only in this current view.</p><div className="form-grid"><label>External subject<input value={subject} onChange={event=>setSubject(event.target.value)} placeholder="dev-uninvited"/></label><label>Application role<select value={role} onChange={event=>setRole(event.target.value as typeof role)}><option value="MEMBER">Member</option><option value="EXPERT">Expert</option><option value="COMPANY_ADMIN">Company admin</option></select></label></div><button disabled={busy||!subject.trim()} onClick={()=>void issue()}>Issue invitation</button>{issued&&<div className="issued-invitation" role="status"><label>One-time invitation link<input readOnly value={inviteLink}/></label><p>Expires {new Date(issued.invitation.expires_at).toLocaleString()}.</p><button className="subtle" disabled={busy} onClick={()=>void revoke()}>Revoke invitation</button></div>}<h3>Memberships</h3><ul className="membership-list">{members.map(member=><li key={member.id}><span><strong>{member.display_name}</strong><small>{member.subject} · {member.role.replaceAll('_',' ')} · {member.active?'Active':'Deactivated'}</small></span>{member.active&&member.id!==currentMembershipId&&<button className="subtle" disabled={busy} onClick={()=>void deactivate(member.id)}>Deactivate</button>}</li>)}</ul></section>
}

function CaseAccessAdmin({record,csrfToken,currentMembershipId,onError}:{record:CaseRecord;csrfToken:string;currentMembershipId:string;onError:(error:unknown)=>void}){
  const [access,setAccess]=useState<CaseAccess[]>([]),[members,setMembers]=useState<Membership[]>([]),[selected,setSelected]=useState(''),[level,setLevel]=useState<'EDITOR'|'VIEWER'>('VIEWER'),[busy,setBusy]=useState(false);
  const refresh=async()=>{const [accessResult,memberResult]=await Promise.all([casesApi.access(record.id),membershipsApi.list()]);setAccess(accessResult.items);setMembers(memberResult.items)};
  useEffect(()=>{void refresh().catch(onError)},[record.id]);
  async function grant(){if(!selected)return;setBusy(true);try{await casesApi.grantAccess(record.id,selected,level,csrfToken);setSelected('');await refresh()}catch(error){onError(error)}finally{setBusy(false)}}
  async function revoke(membershipId:string){setBusy(true);try{await casesApi.revokeAccess(record.id,membershipId,csrfToken);await refresh()}catch(error){onError(error)}finally{setBusy(false)}}
  const granted=new Set(access.filter(item=>item.active).map(item=>item.membership_id)),available=members.filter(item=>item.active&&item.id!==currentMembershipId&&!granted.has(item.id));
  return <section className="panel case-access-admin"><h2>Private case access</h2><p>Case ownership remains private. Grant a named active company member view or edit access; company membership alone is insufficient.</p><div className="form-grid"><label>Company member<select value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Select a member</option>{available.map(member=><option key={member.id} value={member.id}>{member.display_name} · {member.subject}</option>)}</select></label><label>Case permission<select value={level} onChange={event=>setLevel(event.target.value as typeof level)}><option value="VIEWER">View</option><option value="EDITOR">Edit</option></select></label></div><button disabled={busy||!selected} onClick={()=>void grant()}>Grant case access</button><h3>Current access</h3><ul className="membership-list">{access.filter(item=>item.active).map(item=><li key={item.membership_id}><span><strong>{item.display_name}</strong><small>{item.subject} · {item.access_level.toLowerCase()}</small></span>{item.access_level!=='OWNER'&&<button className="subtle" disabled={busy} onClick={()=>void revoke(item.membership_id)}>Revoke</button>}</li>)}</ul></section>
}

export function PrivateCaseWorkspace({conversation}:{conversation:(record:CaseRecord)=>React.ReactNode}){
  const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[cases,setCases]=useState<CaseSummary[]>([]),[active,setActive]=useState<CaseRecord|null>(null),[versions,setVersions]=useState<RequestVersion[]>([]),[draft,setDraft]=useState(''),[newRequest,setNewRequest]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState<Notice>(null),[invitation,setInvitation]=useState<string|null>(null);const createRequest=useRef<{text:string;key:string}|null>(null),openRequest=useRef(0);
  const expire=(error:unknown)=>{if(error instanceof ApiError&&error.status===401){setSession({authenticated:false});setActive(null);setCases([])}setNotice({tone:'error',text:protectedErrorMessage(error)})};
  const loadCases=async()=>{const result=await casesApi.list();setCases(result.items)};
  const openCase=async(id:string)=>{const request=++openRequest.current;setBusy(true);setNotice(null);try{const [record,history]=await Promise.all([casesApi.get(id),casesApi.versions(id)]);if(request!==openRequest.current)return;setActive(record);setDraft(record.current_request.request_text);setVersions(history.items)}catch(error){if(request===openRequest.current)expire(error)}finally{if(request===openRequest.current)setBusy(false)}};
  useEffect(()=>{let current=true;const fragment=new URLSearchParams(window.location.hash.replace(/^#/,'')),token=fragment.get('token');if(token){setInvitation(token);history.replaceState({},'',location.pathname+location.search)}void authApi.session().then(async value=>{if(!current)return;setSession(value);if(value.actor)await loadCases()}).catch(error=>{if(current)setNotice({tone:'error',text:protectedErrorMessage(error)})}).finally(()=>{if(current)setLoading(false)});return()=>{current=false}},[]);
  async function createCase(){const text=newRequest.trim();if(!text||!session?.csrf_token)return;setBusy(true);setNotice(null);if(!createRequest.current||createRequest.current.text!==text)createRequest.current={text,key:createKey()};try{const record=await casesApi.create(text,createRequest.current.key,session.csrf_token);createRequest.current=null;setNewRequest('');await loadCases();await openCase(record.id);setNotice({tone:'success',text:'Reporting case created and saved.'})}catch(error){expire(error)}finally{setBusy(false)}}
  async function save(){if(!active||!session?.csrf_token||!draft.trim())return;setBusy(true);setNotice(null);try{const record=await casesApi.update(active.id,draft.trim(),active.version,session.csrf_token);setActive(record);setDraft(record.current_request.request_text);const history=await casesApi.versions(record.id);setVersions(history.items);await loadCases();setNotice({tone:'success',text:'A new immutable request version was saved.'})}catch(error){expire(error)}finally{setBusy(false)}}
  async function acceptInvitation(){if(!invitation||!session?.csrf_token)return;setBusy(true);try{await invitationsApi.accept(invitation,session.csrf_token);history.replaceState({},'',location.pathname);setInvitation(null);const value=await authApi.session();setSession(value);await loadCases();setNotice({tone:'success',text:'Invitation accepted. Your APBRA membership is active.'})}catch(error){expire(error)}finally{setBusy(false)}}
  async function logout(){if(!session?.csrf_token)return;setBusy(true);try{await authApi.logout(session.csrf_token);setSession({authenticated:false});setCases([]);setActive(null)}catch(error){expire(error)}finally{setBusy(false)}}
  if(loading)return <main className="auth-page"><section className="auth-card"><p role="status">Checking secure APBRA session…</p></section></main>;
  if(!session?.authenticated)return <SignedOut message={notice?.text??(invitation?'Sign in, then reopen the original invitation link to accept it. The invitation secret is not stored in this browser or included in the sign-in return URL.':undefined)}/>;
  if(!session.actor)return <main className="auth-page"><section className="auth-card"><span className="brand-mark">A</span><p className="eyebrow">Authenticated identity</p><h1>{invitation?'Accept your invitation':'An invitation is required'}</h1><p>{invitation?'APBRA will bind this identity to the exact company and role named by the single-use invitation.':'Your identity is valid, but it does not currently have an active APBRA company membership.'}</p>{notice&&<div className={`workspace-notice ${notice.tone}`} role={notice.tone==='error'?'alert':'status'}>{notice.text}</div>}{invitation&&<button disabled={busy} onClick={()=>void acceptInvitation()}>Accept invitation</button>}<button className="subtle" disabled={busy} onClick={()=>void logout()}>Sign out</button></section></main>;
  const canInvite=['COMPANY_OWNER','COMPANY_ADMIN'].includes(session.actor?.role??'');
  return <div className="private-workspace"><header className="secure-bar"><div><strong>{session.actor?.display_name??'APBRA member'}</strong><span>{session.actor?.role?.replaceAll('_',' ')}</span></div><button className="subtle" disabled={busy} onClick={()=>void logout()}>Sign out</button></header>{notice&&<div className={`workspace-notice ${notice.tone}`} role={notice.tone==='error'?'alert':'status'}>{notice.text}</div>}<main className="case-content"><div className="page-heading"><div><span className="eyebrow">Invite-only workspace</span><h1>Reporting cases</h1><p>Your original business request and later versions are durably retained.</p></div></div>{invitation&&<section className="panel invitation-card"><h2>Accept company invitation</h2><p>The invitation will bind this authenticated external identity to the exact invited company membership.</p><button disabled={busy} onClick={()=>void acceptInvitation()}>Accept invitation</button></section>}{canInvite&&session.csrf_token&&session.actor&&<InvitationAdmin csrfToken={session.csrf_token} currentMembershipId={session.actor.membership_id} onError={expire}/>}<div className="case-grid"><div><section className="panel"><h2>Create a reporting case</h2><p>No project or file is required.</p><label htmlFor="new-case-request">Original business request</label><textarea id="new-case-request" rows={5} maxLength={12000} value={newRequest} onChange={event=>{setNewRequest(event.target.value);if(createRequest.current?.text!==event.target.value.trim())createRequest.current=null}}/><button disabled={busy||!newRequest.trim()} onClick={()=>void createCase()}>{busy?'Working…':'Create case'}</button></section><CaseList items={cases} activeId={active?.id} onOpen={id=>void openCase(id)}/></div><div>{active?<><CaseEditor record={active} versions={versions} requestText={draft} onRequestText={setDraft} onSave={()=>void save()} onRefresh={()=>void openCase(active.id)} busy={busy}/>{canInvite&&active.creator_membership_id===session.actor.membership_id&&session.csrf_token&&<CaseAccessAdmin record={active} csrfToken={session.csrf_token} currentMembershipId={session.actor.membership_id} onError={expire}/>}<section className="conversation-boundary"><div className="conversation-heading"><span className="eyebrow">Persisted case conversation</span><h2>Continue this reporting case</h2><p>The conversation below is bound to case version {active.version}. Saving or reloading a changed request resets transient clarification and generation state.</p></div>{conversation(active)}</section></>:<section className="panel empty-state"><h2>Select a case to resume</h2><p>Opening a case loads its current business request and version history from the API.</p></section>}</div></div></main></div>
}
