import React,{useEffect,useRef,useState} from 'react';
import {ApiError,authApi,casesApi,invitationsApi,membershipsApi,type CaseAccess,type CaseRecord,type CaseSummary,type IdentityProviders,type IssuedInvitation,type Membership,type RequestVersion,type Session} from './api';
import {DurableConversation} from './durableConversation';

type Notice={tone:'info'|'error'|'success';text:string}|null;
export const protectedErrorMessage=(error:unknown)=>error instanceof ApiError&&error.status===404?'That report is unavailable or you no longer have access.':error instanceof ApiError&&error.code==='PROVIDER_UNAVAILABLE'?'The sign-in provider is unavailable. Please try again later.':error instanceof ApiError&&error.code==='OIDC_RESPONSE_INVALID'?'Sign-in could not be validated. Please try again.':error instanceof ApiError&&error.status===401?'Your APBRA session has expired. Sign in again to continue.':error instanceof ApiError&&error.code==='STALE_VERSION'?'This report changed in another session. Reload it before saving your changes.':error instanceof Error?error.message:'The request could not be completed.';
export const createKey=()=>crypto.randomUUID();

export function SignedOut({message,providers}:{message?:string;providers?:IdentityProviders}){
  const options=providers?.items??[];
  return <main className="auth-page"><div className="auth-shell"><section className="auth-story" aria-label="APBRA reporting workspace"><div className="auth-brand"><span className="brand-mark" aria-hidden="true">A</span><strong>APBRA</strong></div><div className="auth-story-body"><span className="eyebrow">A clearer way to report</span><p className="auth-story-headline">From a business question to a report you can review.</p><p>Bring the goal, supporting information, decisions and report history together in one private workspace.</p><div className="auth-story-steps"><span><strong>01</strong> Describe your goal</span><span><strong>02</strong> Review the meaning</span><span><strong>03</strong> Build a candidate</span></div></div><div className="auth-story-footer">A private, deliberate reporting journey</div></section><section className="auth-card"><div className="auth-card-top"><span className="auth-lock" aria-hidden="true">◈</span><span>Private reporting workspace</span></div><p className="eyebrow">Welcome to APBRA</p><h1>Sign in to continue</h1><p>{message??'Your external identity establishes who you are. APBRA still checks active company membership and private-case access for every protected action.'}</p>{options.length?options.map(provider=><a key={provider.profile_id} className="primary-link" href={authApi.loginUrl({profileId:provider.profile_id})}>Sign in with {provider.display_label} <span aria-hidden="true">→</span></a>):<p role="status">No qualified sign-in provider is available. Contact the APBRA operator.</p>}{Boolean(providers?.development_identities.length)&&<details><summary>Local development identities</summary><div className="dev-identities">{providers?.development_identities.map(identity=><a key={identity} href={authApi.loginUrl({profileId:'local-test',identity})}>{identity}</a>)}</div></details>}</section></div></main>
}

export function CaseList({items,activeId,onOpen}:{items:CaseSummary[];activeId?:string;onOpen:(id:string)=>void}){
  return <section className="case-list" aria-labelledby="case-list-title"><div className="section-title"><div><span className="eyebrow">Your private work</span><h2 id="case-list-title">My reports</h2><p>Reports available to your current membership.</p></div><span className="status-badge">{items.length} total</span></div>{items.length===0?<div className="empty-state"><span className="empty-state-icon" aria-hidden="true">▤</span><h3>No reports in progress</h3><p>Start with a business question. Your work will appear here when you create a report.</p></div>:<ul>{items.map(item=><li key={item.id}><button className={item.id===activeId?'case-row active':'case-row'} aria-current={item.id===activeId?'page':undefined} onClick={()=>onOpen(item.id)}><span className="case-row-icon" aria-hidden="true">▤</span><span className="case-row-copy"><strong>{item.report_title??item.current_request.request_text}</strong><small>Updated {new Date(item.updated_at).toLocaleDateString()} <span aria-hidden="true">·</span> Request v{item.version}</small></span><span className="case-row-arrow" aria-hidden="true">→</span></button></li>)}</ul>}</section>
}

export function CaseEditor({record,versions,requestText,onRequestText,onSave,onRefresh,busy}:{record:CaseRecord;versions:RequestVersion[];requestText:string;onRequestText:(value:string)=>void;onSave:()=>void;onRefresh:()=>void;busy:boolean}){
  return <section className="case-editor" aria-labelledby="case-goal-title"><div className="section-title"><div><span className="eyebrow">Step 1 · Goal</span><h2 id="case-goal-title">Your reporting goal</h2><p>Keep the question accurate before you review APBRA’s understanding.</p></div><button className="subtle" disabled={busy} onClick={onRefresh}>Reload report</button></div><div className="goal-editor"><label htmlFor="case-request-edit">Current business request</label><textarea id="case-request-edit" rows={5} maxLength={12000} value={requestText} onChange={event=>onRequestText(event.target.value)}/><div className="goal-editor-footer"><span>Edits create a new saved version and require a fresh confirmation.</span><button disabled={busy||!requestText.trim()||requestText===record.current_request.request_text} onClick={onSave}>{busy?'Saving…':'Save new version'}</button></div></div><details className="request-history"><summary>Earlier request versions · {versions.length||1}</summary><ol className="version-history">{(versions.length?versions:[record.current_request]).map(version=><li key={version.id}><strong>Version {version.sequence}</strong><time>{new Date(version.created_at).toLocaleString()}</time><p>{version.request_text}</p></li>)}</ol></details><details className="expert-details"><summary>Details for experts</summary><p>Case reference: {record.id}. Current request version: {record.version}. Saved request versions remain immutable.</p></details></section>
}

function InvitationAdmin({csrfToken,currentMembershipId,onError}:{csrfToken:string;currentMembershipId:string;onError:(error:unknown)=>void}){
  const [subject,setSubject]=useState(''),[role,setRole]=useState<'COMPANY_ADMIN'|'MEMBER'|'EXPERT'>('MEMBER'),[issued,setIssued]=useState<IssuedInvitation|null>(null),[members,setMembers]=useState<Membership[]>([]),[busy,setBusy]=useState(false);
  const refresh=async()=>setMembers((await membershipsApi.list()).items);
  useEffect(()=>{void refresh().catch(onError)},[]);
  async function issue(){if(!subject.trim())return;setBusy(true);try{setIssued(await invitationsApi.issue(subject.trim(),role,csrfToken));setSubject('')}catch(error){onError(error)}finally{setBusy(false)}}
  async function revoke(){if(!issued)return;setBusy(true);try{await invitationsApi.revoke(issued.invitation.id,csrfToken);setIssued(null)}catch(error){onError(error)}finally{setBusy(false)}}
  async function deactivate(membershipId:string){setBusy(true);try{await membershipsApi.deactivate(membershipId,csrfToken);await refresh()}catch(error){onError(error)}finally{setBusy(false)}}
  const inviteLink=issued?`${window.location.origin}/invite#token=${encodeURIComponent(issued.token)}`:'';
  return <section className="panel invitation-admin"><h2>Company access</h2><p>Create a single-use APBRA membership invitation for an exact subject at your qualified identity provider. The bearer link is displayed only in this current view.</p><div className="form-grid"><label>External subject<input value={subject} onChange={event=>setSubject(event.target.value)} placeholder="Exact provider subject"/></label><label>Application role<select value={role} onChange={event=>setRole(event.target.value as typeof role)}><option value="MEMBER">Member</option><option value="EXPERT">Expert</option><option value="COMPANY_ADMIN">Company admin</option></select></label></div><button disabled={busy||!subject.trim()} onClick={()=>void issue()}>Issue invitation</button>{issued&&<div className="issued-invitation" role="status"><label>One-time invitation link<input readOnly value={inviteLink}/></label><p>Expires {new Date(issued.invitation.expires_at).toLocaleString()}.</p><button className="subtle" disabled={busy} onClick={()=>void revoke()}>Revoke invitation</button></div>}<h3>Memberships</h3><ul className="membership-list">{members.map(member=><li key={member.id}><span><strong>{member.display_name}</strong><small>{member.subject} · {member.role.replaceAll('_',' ')} · {member.active?'Active':'Deactivated'}</small></span>{member.active&&member.id!==currentMembershipId&&<button className="subtle" disabled={busy} onClick={()=>void deactivate(member.id)}>Deactivate</button>}</li>)}</ul></section>
}

function CaseAccessAdmin({record,csrfToken,currentMembershipId,onError}:{record:CaseRecord;csrfToken:string;currentMembershipId:string;onError:(error:unknown)=>void}){
  const [access,setAccess]=useState<CaseAccess[]>([]),[members,setMembers]=useState<Membership[]>([]),[selected,setSelected]=useState(''),[level,setLevel]=useState<'EDITOR'|'VIEWER'>('VIEWER'),[busy,setBusy]=useState(false);
  const refresh=async()=>{const [accessResult,memberResult]=await Promise.all([casesApi.access(record.id),membershipsApi.list()]);setAccess(accessResult.items);setMembers(memberResult.items)};
  useEffect(()=>{void refresh().catch(onError)},[record.id]);
  async function grant(){if(!selected)return;setBusy(true);try{await casesApi.grantAccess(record.id,selected,level,csrfToken);setSelected('');await refresh()}catch(error){onError(error)}finally{setBusy(false)}}
  async function revoke(membershipId:string){setBusy(true);try{await casesApi.revokeAccess(record.id,membershipId,csrfToken);await refresh()}catch(error){onError(error)}finally{setBusy(false)}}
  const granted=new Set(access.filter(item=>item.active).map(item=>item.membership_id)),available=members.filter(item=>item.active&&item.id!==currentMembershipId&&!granted.has(item.id));
  return <section className="panel case-access-admin"><h2>Private report access</h2><p>The report remains private. Grant a named active company member view or edit access; company membership alone is insufficient.</p><div className="form-grid"><label>Company member<select value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Select a member</option>{available.map(member=><option key={member.id} value={member.id}>{member.display_name} · {member.subject}</option>)}</select></label><label>Report permission<select value={level} onChange={event=>setLevel(event.target.value as typeof level)}><option value="VIEWER">View</option><option value="EDITOR">Edit</option></select></label></div><button disabled={busy||!selected} onClick={()=>void grant()}>Grant report access</button><h3>Current access</h3><ul className="membership-list">{access.filter(item=>item.active).map(item=><li key={item.membership_id}><span><strong>{item.display_name}</strong><small>{item.subject} · {item.access_level.toLowerCase()}</small></span>{item.access_level!=='OWNER'&&<button className="subtle" disabled={busy} onClick={()=>void revoke(item.membership_id)}>Revoke</button>}</li>)}</ul></section>
}

export function PrivateCaseWorkspace(){
  const [session,setSession]=useState<Session|null>(null),[providers,setProviders]=useState<IdentityProviders|null>(null),[loading,setLoading]=useState(true),[cases,setCases]=useState<CaseSummary[]>([]),[active,setActive]=useState<CaseRecord|null>(null),[caseReportReady,setCaseReportReady]=useState(false),[versions,setVersions]=useState<RequestVersion[]>([]),[draft,setDraft]=useState(''),[newRequest,setNewRequest]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState<Notice>(null),[invitation,setInvitation]=useState<string|null>(null),[view,setView]=useState<'home'|'create'|'reports'|'case'>('home');const createRequest=useRef<{text:string;key:string}|null>(null),openRequest=useRef(0);
  const expire=(error:unknown)=>{if(error instanceof ApiError&&error.status===401){setSession({authenticated:false});setActive(null);setCases([])}setNotice({tone:'error',text:protectedErrorMessage(error)})};
  const loadCases=async()=>{const result=await casesApi.list();setCases(result.items)};
  const openCase=async(id:string)=>{const request=++openRequest.current;setBusy(true);setNotice(null);try{const [record,history]=await Promise.all([casesApi.get(id),casesApi.versions(id)]);if(request!==openRequest.current)return;setCaseReportReady(false);setActive(record);setDraft(record.current_request.request_text);setVersions(history.items);setView('case')}catch(error){if(request===openRequest.current)expire(error)}finally{if(request===openRequest.current)setBusy(false)}};
  useEffect(()=>{let current=true;const fragment=new URLSearchParams(window.location.hash.replace(/^#/,'')),token=fragment.get('token'),query=new URLSearchParams(window.location.search),authError=query.get('auth_error');if(token){setInvitation(token);history.replaceState({},'',location.pathname+location.search)}if(authError){setNotice({tone:'error',text:authError==='cancelled'?'Sign-in was cancelled. Please try again.':authError==='unavailable'?'The sign-in provider is unavailable. Please try again later.':'Sign-in could not be completed. Please try again.'});query.delete('auth_error');history.replaceState({},'',location.pathname+(query.toString()?`?${query}`:'')+location.hash)}void Promise.all([authApi.session(),authApi.providers()]).then(async([value,options])=>{if(!current)return;setSession(value);setProviders(options);if(value.actor)await loadCases()}).catch(error=>{if(current)setNotice({tone:'error',text:protectedErrorMessage(error)})}).finally(()=>{if(current)setLoading(false)});return()=>{current=false}},[]);
  async function createCase(){const text=newRequest.trim();if(!text||!session?.csrf_token)return;setBusy(true);setNotice(null);if(!createRequest.current||createRequest.current.text!==text)createRequest.current={text,key:createKey()};try{const record=await casesApi.create(text,createRequest.current.key,session.csrf_token);createRequest.current=null;setNewRequest('');await loadCases();await openCase(record.id);setNotice({tone:'success',text:'Report request created and saved.'})}catch(error){expire(error)}finally{setBusy(false)}}
  async function save(){if(!active||!session?.csrf_token||!draft.trim())return;setBusy(true);setNotice(null);try{const record=await casesApi.update(active.id,draft.trim(),active.version,session.csrf_token);setActive(record);setDraft(record.current_request.request_text);const history=await casesApi.versions(record.id);setVersions(history.items);await loadCases();setNotice({tone:'success',text:'Your updated request was saved.'})}catch(error){expire(error)}finally{setBusy(false)}}
  async function acceptInvitation(){if(!invitation||!session?.csrf_token)return;setBusy(true);try{await invitationsApi.accept(invitation,session.csrf_token);history.replaceState({},'',location.pathname);setInvitation(null);const value=await authApi.session();setSession(value);await loadCases();setNotice({tone:'success',text:'Invitation accepted. Your APBRA membership is active.'})}catch(error){expire(error)}finally{setBusy(false)}}
  async function logout(){if(!session?.csrf_token)return;setBusy(true);try{await authApi.logout(session.csrf_token);setSession({authenticated:false});setCases([]);setActive(null)}catch(error){expire(error)}finally{setBusy(false)}}
  async function selectCompany(membershipId:string){if(!session?.csrf_token)return;setBusy(true);try{await authApi.selectCompany(membershipId,session.csrf_token);const value=await authApi.session();setSession(value);if(value.actor)await loadCases()}catch(error){expire(error)}finally{setBusy(false)}}
  if(loading)return <main className="auth-page"><section className="auth-card"><span className="brand-mark" aria-hidden="true">A</span><p role="status">Checking secure APBRA session…</p></section></main>;
  if(!session?.authenticated)return <SignedOut providers={providers??undefined} message={notice?.text??(invitation?'Sign in, then reopen the original invitation link to accept it. The invitation secret is not stored in this browser or included in the sign-in return URL.':undefined)}/>;
  if(!session.actor)return <main className="auth-page"><section className="auth-card"><span className="brand-mark">A</span><p className="eyebrow">Authenticated identity</p><h1>{invitation?'Accept your invitation':session.membership_state==='COMPANY_SELECTION_REQUIRED'?'Choose your company':session.membership_state==='MEMBERSHIP_INACTIVE'?'Company access is inactive':'Create Company / Workspace'}</h1><p>{invitation?'APBRA will bind this identity to the exact company and role named by the single-use invitation.':session.membership_state==='COMPANY_SELECTION_REQUIRED'?'Choose one of your active APBRA memberships. This selection cannot grant a new membership or private report access.':session.membership_state==='MEMBERSHIP_INACTIVE'?'Your previous company membership is no longer active. Ask a company administrator for help.':'Your identity is valid, but it has no active APBRA company membership. Company creation is a separately governed APBRA-151 flow and is not available in this preview.'}</p>{notice&&<div className={`workspace-notice ${notice.tone}`} role={notice.tone==='error'?'alert':'status'}>{notice.text}</div>}{session.membership_state==='COMPANY_SELECTION_REQUIRED'&&session.available_companies?.map(company=><button key={company.membership_id} disabled={busy} onClick={()=>void selectCompany(company.membership_id)}>{company.name}</button>)}{invitation&&<button disabled={busy} onClick={()=>void acceptInvitation()}>Accept invitation</button>}{session.membership_state==='COMPANY_CREATION_AVAILABLE'&&!invitation&&<button disabled title="Company creation is planned under APBRA-151">Create Company / Workspace (not yet available)</button>}<button className="subtle" disabled={busy} onClick={()=>void logout()}>Sign out</button></section></main>;
  const canInvite=['COMPANY_OWNER','COMPANY_ADMIN'].includes(session.actor?.role??'');
  const createPanel=<section id="new-report" className="new-report-card" aria-labelledby="new-report-title"><div className="composer-topline"><span className="eyebrow">Start a new report</span><span className="composer-icon" aria-hidden="true">✦</span></div><h2 id="new-report-title">What would you like to understand?</h2><p>Describe your business question in your own words. You can refine it and add a CSV or XLSX file after creating the report.</p><label htmlFor="new-case-request">Your reporting goal</label><textarea id="new-case-request" rows={5} maxLength={12000} placeholder="For example: Which parts of our operation are changing, and where should we focus next?" value={newRequest} onChange={event=>{setNewRequest(event.target.value);if(createRequest.current?.text!==event.target.value.trim())createRequest.current=null}}/><div className="composer-footer"><span>Private to you until you grant access</span><button disabled={busy||!newRequest.trim()} onClick={()=>void createCase()}>{busy?'Creating report…':'Create report'}<span aria-hidden="true">→</span></button></div></section>;
  const casesPanel=<CaseList items={cases} activeId={active?.id} onOpen={id=>void openCase(id)}/>;
  return <div className="private-workspace">
    <a className="skip-link" href="#workspace-main">Skip to reporting workspace</a>
    <aside className="workspace-rail" aria-label="Application navigation"><div className="rail-brand"><span className="brand-mark" aria-hidden="true">A</span><div><strong>APBRA</strong><small>Reporting workspace</small></div></div><div className="rail-section-label">Workspace</div><nav aria-label="Workspace sections"><button className={view==='home'?'rail-link active':'rail-link'} aria-current={view==='home'?'page':undefined} onClick={()=>setView('home')}><span aria-hidden="true">⌂</span>Home</button><button className={view==='create'?'rail-link active':'rail-link'} aria-current={view==='create'?'page':undefined} onClick={()=>setView('create')}><span aria-hidden="true">＋</span>Create report</button><button className={view==='reports'?'rail-link active':'rail-link'} aria-current={view==='reports'?'page':undefined} onClick={()=>setView('reports')}><span aria-hidden="true">▤</span>My reports <small>{cases.length}</small></button>{active&&<button className={view==='case'?'rail-link active':'rail-link'} aria-current={view==='case'?'page':undefined} onClick={()=>setView('case')}><span aria-hidden="true">▣</span>Current report</button>}</nav><div className="rail-footer"><span className="rail-privacy" aria-hidden="true">◈</span><div><strong>Private workspace</strong><small>Access checked on every action</small></div></div></aside>
    <div className="workspace-frame"><header className="workspace-topbar"><div className="workspace-breadcrumb"><span>Workspace</span><span aria-hidden="true">/</span><strong>{view==='home'?'Home':view==='create'?'Create report':view==='reports'?'My reports':'Current report'}</strong></div><div className="account-controls"><span className="account-avatar" aria-hidden="true">{session.actor.display_name.slice(0,1).toUpperCase()}</span><div><strong>{session.actor.display_name}</strong><span>{session.actor.role.replaceAll('_',' ').toLowerCase()}</span></div><button className="subtle" disabled={busy} onClick={()=>void logout()}>Sign out</button></div></header>
    <main id="workspace-main" className="case-content">
      {notice&&<div className={'workspace-notice '+notice.tone} role={notice.tone==='error'?'alert':'status'}>{notice.text}</div>}
      {invitation&&<section className="panel invitation-card"><h2>Accept company invitation</h2><p>This invitation links your signed-in identity to the named company membership.</p><button disabled={busy} onClick={()=>void acceptInvitation()}>Accept invitation</button></section>}
      {view==='home'&&<><section className="workspace-hero"><div><span className="eyebrow">Your reporting workspace</span><h1>Clarity starts with a question.</h1><p>Bring your business goal and supporting information together. APBRA keeps the understanding, report builds and earlier versions in one private place.</p><button onClick={()=>setView('create')}>Create report <span aria-hidden="true">→</span></button></div><div className="hero-metric" aria-label={`${cases.length} reports`}><span className="hero-metric-mark" aria-hidden="true">▥</span><strong>{cases.length.toString().padStart(2,'0')}</strong><span>Reports<br/>in your workspace</span></div></section><div className="home-recent"><div className="section-title"><div><span className="eyebrow">Pick up where you left off</span><h2>Recent work</h2></div>{cases.length>0&&<button className="text-action" onClick={()=>setView('reports')}>View all <span aria-hidden="true">→</span></button>}</div>{casesPanel}</div><section className="workspace-guidance" aria-label="How reporting works"><span>01 <strong>Describe</strong> your question</span><span>02 <strong>Review</strong> the understanding</span><span>03 <strong>Build</strong> a private candidate</span></section></>}
      {view==='create'&&<><div className="page-heading"><div><span className="eyebrow">New report</span><h1>Start with your goal</h1><p>You do not need a report specification. Tell us what you want to learn, then add supporting information and review each decision.</p></div></div>{createPanel}<div className="next-step-note"><strong>What happens next?</strong><p>After creating the report, you can add a supported file, review APBRA’s understanding and confirm the exact meaning before a report can be built.</p></div></>}
      {view==='reports'&&<><div className="page-heading"><div><span className="eyebrow">Private reporting</span><h1>My reports</h1><p>Return to a report, review its current request and find earlier work.</p></div><button onClick={()=>setView('create')}>Create report <span aria-hidden="true">→</span></button></div>{casesPanel}</>}
      {view==='case'&&active&&<><div className="case-identity"><div><span className="eyebrow">Private report <span aria-hidden="true">·</span> Request v{active.version}</span><h1>{active.report_title??active.current_request.request_text}</h1><div className="case-meta"><span className={'status-badge '+(caseReportReady?'status-success':'status-info')}>{caseReportReady?'Candidate ready':'In progress'}</span><span>Updated {new Date(active.updated_at).toLocaleDateString()}</span><span>Only authorised members can open this report</span></div></div><button className="subtle" onClick={()=>setView('reports')}>All reports</button></div><div className="case-workspace-grid"><div className="workspace-primary"><CaseEditor record={active} versions={versions} requestText={draft} onRequestText={setDraft} onSave={()=>void save()} onRefresh={()=>void openCase(active.id)} busy={busy}/>{session.csrf_token&&<DurableConversation record={active} csrfToken={session.csrf_token} actorRole={session.actor.role} onContextChanged={semantic_context_version=>{setCaseReportReady(false);setActive(current=>current&&current.id===active.id?{...current,semantic_context_version}:current)}} onReportReady={setCaseReportReady} onError={expire}/>}</div><aside className="case-context" aria-label="Report context"><div className="context-card"><span className="eyebrow">At a glance</span><h2>About this report</h2><dl><div><dt>Request version</dt><dd>{active.version}</dd></div><div><dt>Last updated</dt><dd>{new Date(active.updated_at).toLocaleDateString()}</dd></div><div><dt>Access</dt><dd>Private</dd></div></dl><p>Your requirements, supporting information and build history are saved with this report.</p></div>{canInvite&&active.creator_membership_id===session.actor.membership_id&&session.csrf_token&&<details className="workspace-admin"><summary>Manage private report access</summary><CaseAccessAdmin record={active} csrfToken={session.csrf_token} currentMembershipId={session.actor.membership_id} onError={expire}/></details>}</aside></div></>}
      {canInvite&&session.csrf_token&&session.actor&&<details className="workspace-admin company-admin"><summary>Manage company access</summary><InvitationAdmin csrfToken={session.csrf_token} currentMembershipId={session.actor.membership_id} onError={expire}/></details>}
    </main></div>
  </div>
}
