import {expect,it} from 'vitest';
import {inspectMeasureIntegrity,type ReportDesign,type VisualDesign} from './foundry';
import {compilePowerBI,validateGenericCandidate} from './genericPowerBI';
import {evaluateGuardrails} from './guardrail';
import {normalizeReportDesign} from './reportDesignNormalization';
import type {DataStructure} from './schemaIngestion';
import {defaultTenantSettings} from './tenant';

const schema:DataStructure={kind:'REQUEST_DATA_STRUCTURE',fileName:'generic.csv',format:'CSV',parsedAt:'2026-09-20',tables:[{name:'Facts',sourceName:'Facts',rowCount:1,rows:[['1','Open','A','Group']],columns:[{name:'Id',sourceName:'Id',type:'text',nullable:false,sampleValues:['1']},{name:'Status',sourceName:'Status',type:'text',nullable:false,sampleValues:['Open']},{name:'Type',sourceName:'Type',type:'text',nullable:false,sampleValues:['A']},{name:'Group',sourceName:'Group',type:'text',nullable:false,sampleValues:['Group']},{name:'A-B',sourceName:'A-B',type:'text',nullable:false,sampleValues:['x']},{name:'AB',sourceName:'AB',type:'text',nullable:false,sampleValues:['y']}]}],relationships:[]};
const slicer=(overrides:Partial<VisualDesign>={}):VisualDesign=>({id:'filters',type:'slicer',title:'Filters',categoryField:'',measureIds:[],fields:['Facts.Status'],altText:'Filter records',...overrides});
const design=(visual:VisualDesign=slicer()):ReportDesign=>({artifact_kind:'ReportDesign',schema_version:1,projectName:'GenericReport',overview:'Generic report',audience:'Leaders',dataModel:{factTables:['Facts'],dimensionTables:[],relationships:[]},measures:[{id:'count',name:'Record count',businessDefinition:'Records',aggregation:'COUNT',field:'Facts.Id',numeratorMeasureId:'',denominatorMeasureId:'',format:'integer'}],pages:[{id:'summary',name:'Summary',purpose:'Summary',visuals:[visual]}],filters:[],branding:{themeName:'Tenant',primary:'#005A9C',accent:'#2D7D9A'},accessibility:['Titles'],standardsApplied:[{citation:'standard#1',decision:'Use clear filters'}],assumptions:[],warnings:[],generationRequirements:[]});
const normalize=(visual:VisualDesign)=>normalizeReportDesign(design(visual),schema);

it('expands a multi-field slicer into independent valid slicers',()=>{const result=normalize(slicer({fields:['Facts.Type','Facts.Status']}));expect(result.status).toBe('NORMALIZED');expect(result.normalizedReportDesign.pages[0].visuals.map(item=>item.fields)).toEqual([['Facts.Type'],['Facts.Status']]);expect(inspectMeasureIntegrity(result.normalizedReportDesign)).toEqual([])});
it('collapses duplicate same-field sources to one slicer',()=>{const result=normalize(slicer({fields:['Facts.Status'],categoryField:'Facts.Status'}));expect(result.normalizedReportDesign.pages[0].visuals).toHaveLength(1);expect(result.normalizationActions[0].reason).toBe('DUPLICATE_BINDING_COLLAPSED')});
it('expands distinct field and category bindings',()=>{const result=normalize(slicer({fields:['Facts.Type'],categoryField:'Facts.Status'}));expect(result.normalizedReportDesign.pages[0].visuals.map(item=>item.fields[0])).toEqual(['Facts.Type','Facts.Status']);expect(result.normalizationActions[0].reason).toBe('MIXED_BINDINGS_EXPANDED')});
it('expands multiple fields plus category and deduplicates canonical repeats',()=>{const result=normalize(slicer({fields:['Facts.Type','Facts.Status',' Facts.Type '],categoryField:'Facts.Group'}));expect(result.normalizedReportDesign.pages[0].visuals.map(item=>item.fields[0])).toEqual(['Facts.Type','Facts.Status','Facts.Group'])});
it('leaves valid field-only and category-only slicers unchanged',()=>{for(const visual of [slicer(),slicer({fields:[],categoryField:'Facts.Status'})]){const result=normalize(visual);expect(result.status).toBe('UNCHANGED');expect(result.normalizationActions).toEqual([])}});
it('safe-stops empty, measure-bound, and unknown-field slicers',()=>{const cases:[[VisualDesign,string],[VisualDesign,string],[VisualDesign,string]]=[[slicer({fields:[]}), 'EMPTY_SLICER_BINDING'],[slicer({measureIds:['count']}),'MEASURE_BOUND_SLICER'],[slicer({fields:['Facts.Missing']}),'UNKNOWN_SCHEMA_FIELD']];for(const [visual,code] of cases){const result=normalize(visual);expect(result.status).toBe('FAILED');expect(result.normalizationFindings[0].code).toBe(code)}});
it('safe-stops expansion when the actual compiler grid cannot fit the complete page',()=>{const value=design();value.pages[0].visuals=Array.from({length:4},(_,index)=>slicer({id:`s${index}`}));value.pages[0].visuals[0]=slicer({id:'expand',fields:['Facts.Type','Facts.Status']});const result=normalizeReportDesign(value,schema),finding=result.normalizationFindings.find(item=>item.code==='LAYOUT_CAPACITY_EXCEEDED');expect(result.status).toBe('FAILED');expect(finding).toMatchObject({pageId:'summary',visualId:'expand',requestedResultingVisuals:2,pageBounds:{width:1280,height:720}});expect(finding?.attemptedLayoutSlots?.some(slot=>slot.bottom>720)).toBe(true)});
it('creates stable IDs for identical input without mutating the original',()=>{const original=design(slicer({fields:['Facts.Type','Facts.Status']})),before=structuredClone(original);const first=normalizeReportDesign(original,schema),second=normalizeReportDesign(original,schema);expect(first.normalizedReportDesign.pages[0].visuals.map(item=>item.id)).toEqual(second.normalizedReportDesign.pages[0].visuals.map(item=>item.id));expect(original).toEqual(before);expect(first.originalReportDesign).toBe(original)});
it('avoids collisions for bindings with similar display slugs',()=>{const result=normalize(slicer({fields:['Facts.A-B','Facts.AB']}));const ids=result.normalizedReportDesign.pages[0].visuals.map(item=>item.id);expect(new Set(ids).size).toBe(2);expect(ids[0]).not.toBe(ids[1])});
it('records deterministic compiler-aligned, non-overlapping, in-bounds layout and provenance',()=>{const result=normalize(slicer({fields:['Facts.Type','Facts.Status']})),action=result.normalizationActions[0],slots=result.pageLayouts[0].visuals;expect(action).toMatchObject({code:'NORMALIZED_VISUAL_BINDING',pageId:'summary',originalVisualId:'filters',originalBindings:['Facts.Type','Facts.Status'],resultingBindings:['Facts.Type','Facts.Status'],originalLayoutSlot:{index:0,x:20,y:30}});expect(action.layoutSlots).toHaveLength(2);for(const slot of slots){expect(slot.x).toBeGreaterThanOrEqual(0);expect(slot.y).toBeGreaterThanOrEqual(0);expect(slot.right).toBeLessThanOrEqual(1280);expect(slot.bottom).toBeLessThanOrEqual(720)}expect(action.layoutSlots[0].x).not.toBe(action.layoutSlots[1].x);expect(normalize(slicer({fields:['Facts.Type','Facts.Status']})).normalizationActions[0].layoutSlots).toEqual(action.layoutSlots)});
it('passes integrity, guardrails, compiler and deterministic validation after normalization',()=>{const result=normalize(slicer({fields:['Facts.Type','Facts.Status']})),normalized=result.normalizedReportDesign;expect(inspectMeasureIntegrity(normalized)).toEqual([]);const interpretation={request_kind:'POWER_BI_REPORT' as const,objective:'Analyse records',businessQuestions:[],kpis:[],dimensions:[],filters:[],audience:'Leaders',pages:['Summary'],assumptions:[],ambiguities:[],clarifications:[]};const policy=evaluateGuardrails(interpretation,normalized,schema,defaultTenantSettings);expect(policy.generation).toBe('AVAILABLE');const candidate=compilePowerBI(normalized,schema,defaultTenantSettings);expect(validateGenericCandidate(candidate,normalized,schema).status).toBe('PASS')});
