import {validateConfirmedRequirementContract,type ConfirmedRequirementContract,type ConfirmedRequirementObligation} from './confirmedRequirements';
import type {ReportDesign,VisualDesign} from './foundry';
import type {DataStructure} from './schemaIngestion';

export type LayoutSlot={visualId:string;type:VisualDesign['type'];index:number;x:number;y:number;width:number;height:number;right:number;bottom:number};
export type PageLayout={pageId:string;pageName:string;width:1280;height:720;visuals:LayoutSlot[]};
export type NormalizationAction={code:'NORMALIZED_VISUAL_BINDING';reason:'MULTI_FIELD_SLICER_EXPANDED'|'DUPLICATE_BINDING_COLLAPSED'|'MIXED_BINDINGS_EXPANDED';pageId:string;pageName:string;originalVisualId:string;originalVisualType:'slicer';originalBindings:string[];originalLayoutSlot:LayoutSlot;resultingVisualIds:string[];resultingBindings:string[];layoutSlots:LayoutSlot[]};
export type NormalizationFinding={code:'EMPTY_SLICER_BINDING'|'MEASURE_BOUND_SLICER'|'UNKNOWN_SCHEMA_FIELD'|'LAYOUT_CAPACITY_EXCEEDED';pageId:string;pageName:string;visualId:string;reason:string;recommendedAction:string;requestedResultingVisuals?:number;pageBounds?:{width:1280;height:720};attemptedLayoutSlots?:LayoutSlot[]};
export type ReportDesignNormalization={status:'UNCHANGED'|'NORMALIZED'|'FAILED';originalReportDesign:ReportDesign;normalizedReportDesign:ReportDesign;originalVisualCount:number;normalizedVisualCount:number;normalizationActions:NormalizationAction[];normalizationFindings:NormalizationFinding[];pageLayouts:PageLayout[]};
export type RequirementCoverageKind='PAGE'|'KPI'|'BUSINESS_QUESTION'|'CLARIFICATION'|'FILTER'|'BREAKDOWN'|'TREND'|'LIFECYCLE'|'DIMENSION';
export type RequirementCoverage={id:string;kind:RequirementCoverageKind;source:string;beforeVisualIds:string[];afterVisualIds:string[];beforeCovered:boolean;afterCovered:boolean};
export type ClarificationAnswerMaterialization={clarificationId:string;category:ConfirmedRequirementContract['provenance']['questions'][number]['category'];coverageRequirementIds:string[];answerConfirmed:boolean;status:'MATERIALIZED'|'UNMATERIALIZED'};
export type LayoutRepairSemanticFinding={code:'CONFIRMED_REQUIREMENTS_UNAVAILABLE'|'UNMATERIALIZED_CLARIFICATION_ANSWER'|'REPORT_CONTRACT_CHANGED'|'MEASURE_CONTRACT_CHANGED'|'REQUIRED_PAGE_REMOVED'|'REQUIRED_KPI_UNCOVERED'|'REQUIRED_BUSINESS_QUESTION_UNCOVERED'|'REQUIRED_CLARIFICATION_UNCOVERED'|'REQUIRED_FILTER_UNCOVERED'|'REQUIRED_BREAKDOWN_UNCOVERED'|'REQUIRED_TREND_UNCOVERED'|'REQUIRED_DIMENSION_UNCOVERED'|'REQUIRED_LIFECYCLE_UNCOVERED'|'FIELD_BINDING_CHANGED'|'UNJUSTIFIED_VISUAL_ADDITION'|'OPTIONAL_DUPLICATE_REMOVED'|'OPTIONAL_VISUAL_REMOVED';result:'PASS'|'FAIL';reason:string;visualIds?:string[]};
export type LayoutRepairSemanticInspection={status:'PASS'|'FAIL';findings:LayoutRepairSemanticFinding[];removedVisualIds:string[];retainedVisualIds:string[];coverageBefore:RequirementCoverage[];coverageAfter:RequirementCoverage[];clarificationAnswers:ClarificationAnswerMaterialization[]};

export function isLayoutRepairEligible(normalization:ReportDesignNormalization):boolean{return normalization.status==='FAILED'&&normalization.normalizationFindings.length>0&&normalization.normalizationFindings.every(finding=>finding.code==='LAYOUT_CAPACITY_EXCEEDED')}
const canonicalValue=(value:unknown):unknown=>value&&typeof value==='object'&&!Array.isArray(value)?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([left],[right])=>left.localeCompare(right)).map(([key,item])=>[key,canonicalValue(item)])):Array.isArray(value)?value.map(canonicalValue):value;
const stable=(value:unknown):string=>JSON.stringify(canonicalValue(value));
const same=(left:unknown,right:unknown)=>stable(left)===stable(right);
const exactKey=(value:string)=>value.trim().toLocaleLowerCase();
const visualBindings=(visual:VisualDesign)=>[visual.categoryField,...visual.fields].map(value=>value.trim()).filter(Boolean);
const visualSignature=(visual:VisualDesign)=>stable({type:visual.type,categoryField:visual.categoryField,measureIds:[...visual.measureIds].sort(),fields:[...visual.fields].sort(),title:visual.title,altText:visual.altText});
const flattened=(design:ReportDesign)=>design.pages.flatMap(page=>page.visuals.map(visual=>({key:`${page.id}/${visual.id}`,pageId:page.id,pageName:page.name,visual})));
const contextOf=(value:unknown):ConfirmedRequirementContract|null=>{try{return validateConfirmedRequirementContract(value as ConfirmedRequirementContract)}catch{return null}};

export function inspectLayoutRepairSemantics(original:ReportDesign,repaired:ReportDesign,confirmedValue:unknown):LayoutRepairSemanticInspection{
 const findings:LayoutRepairSemanticFinding[]=[],clarificationAnswers:ClarificationAnswerMaterialization[]=[],confirmed=contextOf(confirmedValue),before=flattened(original),after=flattened(repaired),beforeByKey=new Map(before.map(item=>[item.key,item])),afterByKey=new Map(after.map(item=>[item.key,item]));
 const removedVisualIds=[...beforeByKey.keys()].filter(key=>!afterByKey.has(key)),retainedVisualIds=[...beforeByKey.keys()].filter(key=>afterByKey.has(key));
 const fail=(code:LayoutRepairSemanticFinding['code'],reason:string,visualIds?:string[])=>findings.push({code,result:'FAIL',reason,...(visualIds?.length?{visualIds}: {})});
 const pass=(code:LayoutRepairSemanticFinding['code'],reason:string,visualIds?:string[])=>findings.push({code,result:'PASS',reason,...(visualIds?.length?{visualIds}: {})});
 if(!confirmed){const legacy=confirmedValue&&typeof confirmedValue==='object'?(confirmedValue as {interpretation?:{clarifications?:Array<{id:string;category:ClarificationAnswerMaterialization['category'];question:string;required:boolean;coverageRequirementIds?:string[]}>};answers?:Record<string,string>}):null;for(const clarification of legacy?.interpretation?.clarifications?.filter(item=>item.required)??[]){const answer=legacy?.answers?.[clarification.id]?.trim();clarificationAnswers.push({clarificationId:clarification.id,category:clarification.category,coverageRequirementIds:[...(clarification.coverageRequirementIds??[])],answerConfirmed:Boolean(answer),status:'UNMATERIALIZED'});fail('UNMATERIALIZED_CLARIFICATION_ANSWER',`Required clarification '${clarification.id}' ${answer?'is free text without a validated typed effect':'has no validated typed selection'}; coverage must safe-stop.`)}fail('CONFIRMED_REQUIREMENTS_UNAVAILABLE','Layout repair cannot be accepted without a typed confirmed-requirement coverage contract.');return{status:'FAIL',findings,removedVisualIds,retainedVisualIds,coverageBefore:[],coverageAfter:[],clarificationAnswers}}
 const reportFields=['artifact_kind','schema_version','projectName','overview','audience','dataModel','branding','accessibility','standardsApplied','assumptions','generationRequirements'] as const;
 for(const field of reportFields)if(!same(original[field],repaired[field]))fail('REPORT_CONTRACT_CHANGED',`Layout repair changed '${field}', which is outside layout-only authority.`);
 if(!original.warnings.every(warning=>repaired.warnings.includes(warning)))fail('REPORT_CONTRACT_CHANGED','Layout repair removed or changed an existing warning; repair may only append warnings.');
 if(!same([...original.filters].sort(),[...repaired.filters].sort()))fail('REPORT_CONTRACT_CHANGED','Layout repair changed the declared report filter contract.');
 const indexed=<T extends{id:string}>(items:T[])=>new Map(items.map(item=>[item.id,item])),originalMeasures=indexed(original.measures),repairedMeasures=indexed(repaired.measures),originalPages=indexed(original.pages),repairedPages=indexed(repaired.pages);
 if(originalMeasures.size!==original.measures.length||repairedMeasures.size!==repaired.measures.length||originalMeasures.size!==repairedMeasures.size||[...originalMeasures].some(([id,value])=>!repairedMeasures.has(id)||!same(value,repairedMeasures.get(id))))fail('MEASURE_CONTRACT_CHANGED','Layout repair added, removed, duplicated, or changed a measure contract.');
 if(originalPages.size!==original.pages.length||repairedPages.size!==repaired.pages.length||[...repairedPages].some(([id])=>!originalPages.has(id))||[...originalPages].some(([id,page])=>{const candidate=repairedPages.get(id);return candidate&&(page.name!==candidate.name||page.purpose!==candidate.purpose)}))fail('REPORT_CONTRACT_CHANGED','Layout repair added, duplicated, renamed, or repurposed a report page.');
 if(beforeByKey.size!==before.length||afterByKey.size!==after.length)fail('REPORT_CONTRACT_CHANGED','Visual IDs must remain unique within each report page.');
 for(const key of retainedVisualIds)if(!same(beforeByKey.get(key)!.visual,afterByKey.get(key)!.visual))fail('FIELD_BINDING_CHANGED',`Retained visual '${key}' changed its type, bindings, title, or accessibility contract.`,[key]);
 for(const item of after.filter(candidate=>!beforeByKey.has(candidate.key))){const equivalent=before.find(source=>removedVisualIds.includes(source.key)&&visualSignature(source.visual)===visualSignature(item.visual));if(!equivalent)fail('UNJUSTIFIED_VISUAL_ADDITION',`Visual '${item.key}' is not an exact structural replacement for a removed original visual.`,[item.key])}
 const allFields=new Set([...original.filters,...original.measures.flatMap(measure=>[measure.field,measure.filterField??'',measure.contextField??'']),...before.flatMap(item=>visualBindings(item.visual))].filter(Boolean).map(exactKey));
 const measureMatches=(measure:ReportDesign['measures'][number],expected:ConfirmedRequirementObligation['measures'][number])=>same({id:measure.id,name:measure.name,businessDefinition:measure.businessDefinition,aggregation:measure.aggregation,field:measure.field,numeratorMeasureId:measure.numeratorMeasureId,denominatorMeasureId:measure.denominatorMeasureId,format:measure.format,filterField:measure.filterField??'',filterValue:measure.filterValue??'',contextField:measure.contextField??''},expected);
 const resolveContract=(contract:ConfirmedRequirementObligation)=>{const resolvedMeasures=contract.measures.map(expected=>original.measures.find(measure=>measureMatches(measure,expected))).filter((measure):measure is ReportDesign['measures'][number]=>Boolean(measure));return{allMeasuresResolved:resolvedMeasures.length===contract.measures.length,measureIds:contract.measureNames.map(name=>resolvedMeasures.find(measure=>measure.name===name)?.id).filter((id):id is string=>Boolean(id)),fields:contract.fields.filter(field=>allFields.has(exactKey(field))),pageIds:contract.pageNames.map(name=>original.pages.find(page=>exactKey(page.name)===exactKey(name))?.id).filter((id):id is string=>Boolean(id))}};
 const matchesScope=(item:{pageId:string},pageIds:string[])=>pageIds.length===0||pageIds.includes(item.pageId),hasBinding=(visual:VisualDesign,field:string)=>visualBindings(visual).some(binding=>exactKey(binding)===exactKey(field));
 const coveredVisuals=(items:typeof before,design:ReportDesign,contract:ConfirmedRequirementObligation)=>{const resolved=resolveContract(contract);if(!resolved.allMeasuresResolved||resolved.measureIds.length!==contract.measureNames.length||resolved.fields.length!==contract.fields.length||resolved.pageIds.length!==contract.pageNames.length)return[];const scoped=items.filter(item=>matchesScope(item,resolved.pageIds));if(contract.kind==='FILTER'){const visualContributors=scoped.filter(item=>item.visual.type==='slicer'&&resolved.fields.some(field=>hasBinding(item.visual,field))),reportFilterContributors=resolved.fields.filter(field=>design.filters.some(filter=>exactKey(filter)===exactKey(field))).map(field=>`report-filter:${field}`),covered=resolved.fields.every(field=>visualContributors.some(item=>hasBinding(item.visual,field))||design.filters.some(filter=>exactKey(filter)===exactKey(field)));return covered?[...new Set([...visualContributors.map(item=>item.key),...reportFilterContributors])]:[]}const measureContributors=scoped.filter(item=>item.visual.measureIds.some(id=>resolved.measureIds.includes(id))),fieldContributors=scoped.filter(item=>resolved.fields.some(field=>hasBinding(item.visual,field))),measureCoverage=resolved.measureIds.every(id=>scoped.some(item=>item.visual.measureIds.includes(id))),fieldCoverage=resolved.fields.every(field=>scoped.some(item=>hasBinding(item.visual,field))),timeCoverage=contract.kind!=='TREND'||resolved.fields.every(field=>scoped.some(item=>hasBinding(item.visual,field)));if(!measureCoverage||!fieldCoverage||!timeCoverage)return[];return[...new Set([...measureContributors.map(item=>item.key),...fieldContributors.map(item=>item.key)])]};
 const coverage:RequirementCoverage[]=[],contractCoverage=new Map<string,RequirementCoverage>();
 for(const required of confirmed.pages.filter(page=>page.required)){const originalMatches=original.pages.filter(page=>exactKey(page.name)===exactKey(required.name)),repairedMatches=repaired.pages.filter(page=>exactKey(page.name)===exactKey(required.name)&&originalMatches.some(source=>source.id===page.id));coverage.push({id:`page:${required.name}`,kind:'PAGE',source:required.name,beforeVisualIds:originalMatches.map(page=>page.id),afterVisualIds:repairedMatches.map(page=>page.id),beforeCovered:originalMatches.length===1,afterCovered:repairedMatches.length===1})}
 for(const contract of confirmed.obligations){const beforeIds=coveredVisuals(before,original,contract),afterIds=coveredVisuals(after,repaired,contract),resolved=resolveContract(contract),identifiersResolved=resolved.allMeasuresResolved&&resolved.measureIds.length===contract.measureNames.length&&resolved.fields.length===contract.fields.length&&resolved.pageIds.length===contract.pageNames.length,value:RequirementCoverage={id:contract.id,kind:contract.kind,source:contract.id,beforeVisualIds:beforeIds,afterVisualIds:afterIds,beforeCovered:!contract.required||identifiersResolved&&beforeIds.length>=contract.minimumRepresentations,afterCovered:!contract.required||identifiersResolved&&afterIds.length>=contract.minimumRepresentations};coverage.push(value);contractCoverage.set(contract.id,value)}
 for(const dimension of confirmed.dimensions){const beforeIds=before.filter(item=>hasBinding(item.visual,dimension)).map(item=>item.key),afterIds=after.filter(item=>hasBinding(item.visual,dimension)).map(item=>item.key);coverage.push({id:`dimension:${dimension}`,kind:'DIMENSION',source:dimension,beforeVisualIds:beforeIds,afterVisualIds:afterIds,beforeCovered:beforeIds.length>0,afterCovered:afterIds.length>0})}
 for(const mapping of confirmed.businessQuestions){const obligations=mapping.coverageRequirementIds.map(id=>contractCoverage.get(id)),beforeCovered=obligations.length>0&&obligations.every(Boolean)&&obligations.every(item=>item!.beforeCovered),afterCovered=obligations.length>0&&obligations.every(Boolean)&&obligations.every(item=>item!.afterCovered);coverage.push({id:`question:${mapping.question}`,kind:'BUSINESS_QUESTION',source:mapping.question,beforeVisualIds:[...new Set(obligations.flatMap(item=>item?.beforeVisualIds??[]))],afterVisualIds:[...new Set(obligations.flatMap(item=>item?.afterVisualIds??[]))],beforeCovered,afterCovered})}
 for(const clarification of confirmed.provenance.questions.filter(item=>item.required)){const selection=confirmed.provenance.selections.find(item=>item.clarificationId===clarification.id),obligations=clarification.coverageRequirementIds.map(id=>contractCoverage.get(id)),beforeIds=[...new Set(obligations.flatMap(item=>item?.beforeVisualIds??[]))],afterIds=[...new Set(obligations.flatMap(item=>item?.afterVisualIds??[]))],beforeCovered=Boolean(selection)&&obligations.every(item=>item?.beforeCovered),afterCovered=Boolean(selection)&&obligations.every(item=>item?.afterCovered);clarificationAnswers.push({clarificationId:clarification.id,category:clarification.category,coverageRequirementIds:[...clarification.coverageRequirementIds],answerConfirmed:Boolean(selection),status:'MATERIALIZED'});coverage.push({id:`clarification:${clarification.id}`,kind:'CLARIFICATION',source:clarification.question,beforeVisualIds:beforeIds,afterVisualIds:afterIds,beforeCovered,afterCovered})}
 const codeByKind:Record<RequirementCoverageKind,LayoutRepairSemanticFinding['code']>={PAGE:'REQUIRED_PAGE_REMOVED',KPI:'REQUIRED_KPI_UNCOVERED',BUSINESS_QUESTION:'REQUIRED_BUSINESS_QUESTION_UNCOVERED',CLARIFICATION:'REQUIRED_CLARIFICATION_UNCOVERED',FILTER:'REQUIRED_FILTER_UNCOVERED',BREAKDOWN:'REQUIRED_BREAKDOWN_UNCOVERED',TREND:'REQUIRED_TREND_UNCOVERED',DIMENSION:'REQUIRED_DIMENSION_UNCOVERED',LIFECYCLE:'REQUIRED_LIFECYCLE_UNCOVERED'};
 for(const obligation of coverage)if(!obligation.beforeCovered||!obligation.afterCovered)fail(codeByKind[obligation.kind],`Confirmed ${obligation.kind.toLocaleLowerCase()} obligation '${obligation.source}' is not covered ${!obligation.beforeCovered?'by the original design':'after layout repair'}.`,obligation.afterVisualIds);
 const hasFailure=findings.some(finding=>finding.result==='FAIL');
 if(!hasFailure)for(const key of removedVisualIds){const removed=beforeByKey.get(key)!.visual,equivalent=after.some(item=>visualSignature(item.visual)===visualSignature(removed));if(equivalent)pass('OPTIONAL_DUPLICATE_REMOVED',`Removed visual '${key}' has an exact retained equivalent and all confirmed obligations remain covered.`,[key]);else pass('OPTIONAL_VISUAL_REMOVED',`Removed visual '${key}' is not required by any uncovered confirmed obligation.`,[key])}
 return{status:findings.some(finding=>finding.result==='FAIL')?'FAIL':'PASS',findings,removedVisualIds,retainedVisualIds,coverageBefore:coverage.map(item=>({...item,afterVisualIds:[],afterCovered:item.beforeCovered})),coverageAfter:coverage.map(item=>({...item,beforeVisualIds:[],beforeCovered:item.afterCovered})),clarificationAnswers};
}

const PAGE_WIDTH=1280 as const,PAGE_HEIGHT=720 as const;
const canonical=(value:string)=>value.trim().toLowerCase();
const hash=(value:string)=>{let result=0x811c9dc5;for(const char of value)result=Math.imul(result^char.charCodeAt(0),16777619)>>>0;return result.toString(16).padStart(8,'0')};
const slug=(binding:string)=>{const value=binding.split('.').at(-1)??binding;return value.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9]+/g,'').slice(0,28)||'Field'};
const layout=(visual:VisualDesign,index:number):LayoutSlot=>{const x=20+(index%2)*610,y=30+Math.floor(index/2)*260,width=visual.type==='card'?285:580,height=visual.type==='card'?120:230;return{visualId:visual.id,type:visual.type,index,x,y,width,height,right:x+width,bottom:y+height}};
const withinPage=(slot:LayoutSlot)=>slot.x>=0&&slot.y>=0&&slot.right<=PAGE_WIDTH&&slot.bottom<=PAGE_HEIGHT;
const countVisuals=(design:ReportDesign)=>design.pages.reduce((count,page)=>count+page.visuals.length,0);

export function normalizeReportDesign(originalReportDesign:ReportDesign,schema:DataStructure):ReportDesignNormalization{
 const normalizedReportDesign=structuredClone(originalReportDesign),actions:NormalizationAction[]=[],findings:NormalizationFinding[]=[],pageLayouts:PageLayout[]=[];
 const knownFields=new Set(schema.tables.flatMap(table=>table.columns.map(column=>canonical(`${table.name}.${column.name}`))));
 for(const page of normalizedReportDesign.pages){
  const originalPage=originalReportDesign.pages.find(item=>item.id===page.id)??page,usedIds=new Set(page.visuals.map(visual=>visual.id)),normalized:VisualDesign[]=[],additional:VisualDesign[]=[];
  for(let originalIndex=0;originalIndex<page.visuals.length;originalIndex++){
   const visual=page.visuals[originalIndex];if(visual.type!=='slicer'){normalized.push(visual);continue}
   const sourceBindings=[...visual.fields.map(item=>item.trim()).filter(Boolean),...(visual.categoryField.trim()?[visual.categoryField.trim()]:[])],uniqueBindings:string[]=[],seen=new Set<string>();
   for(const binding of sourceBindings){const key=canonical(binding);if(!seen.has(key)){seen.add(key);uniqueBindings.push(binding)}}
   if(visual.measureIds.length){findings.push({code:'MEASURE_BOUND_SLICER',pageId:page.id,pageName:page.name,visualId:visual.id,reason:`Slicer '${visual.title}' contains ${visual.measureIds.length} measure binding(s).`,recommendedAction:'Use ordinary schema fields for slicers and keep measures in supported data visuals.'});normalized.push(visual);continue}
   if(!sourceBindings.length){findings.push({code:'EMPTY_SLICER_BINDING',pageId:page.id,pageName:page.name,visualId:visual.id,reason:`Slicer '${visual.title}' has no field or category binding.`,recommendedAction:'Provide exactly one known schema field for the slicer.'});normalized.push(visual);continue}
   const unknown=uniqueBindings.filter(binding=>!knownFields.has(canonical(binding)));
   if(unknown.length){findings.push({code:'UNKNOWN_SCHEMA_FIELD',pageId:page.id,pageName:page.name,visualId:visual.id,reason:`Slicer '${visual.title}' references unknown schema field(s): ${unknown.join(', ')}.`,recommendedAction:'Use exact Table.Column identifiers present in the uploaded schema.'});normalized.push(visual);continue}
   const duplicateCollapsed=uniqueBindings.length<sourceBindings.length;if(uniqueBindings.length===1&&!duplicateCollapsed&&sourceBindings.length===1){normalized.push(visual);continue}
   usedIds.delete(visual.id);const resulting=uniqueBindings.map(binding=>{const root=`${visual.id}__${slug(binding)}__${hash(canonical(binding))}`;let id=root,suffix=2;while(usedIds.has(id))id=`${root}__${suffix++}`;usedIds.add(id);return{...visual,id,title:uniqueBindings.length===1?visual.title:`${visual.title} — ${binding.split('.').at(-1)??binding}`,fields:[binding],categoryField:'',measureIds:[]} as VisualDesign});
   normalized.push(resulting[0]);additional.push(...resulting.slice(1));const reason=duplicateCollapsed&&uniqueBindings.length===1?'DUPLICATE_BINDING_COLLAPSED':visual.fields.length&&visual.categoryField.trim()?'MIXED_BINDINGS_EXPANDED':'MULTI_FIELD_SLICER_EXPANDED';
   actions.push({code:'NORMALIZED_VISUAL_BINDING',reason,pageId:page.id,pageName:page.name,originalVisualId:visual.id,originalVisualType:'slicer',originalBindings:sourceBindings,originalLayoutSlot:layout(originalPage.visuals[originalIndex],originalIndex),resultingVisualIds:resulting.map(item=>item.id),resultingBindings:resulting.map(item=>item.fields[0]),layoutSlots:[]});
  }
  page.visuals=[...normalized,...additional];const slots=page.visuals.map(layout);pageLayouts.push({pageId:page.id,pageName:page.name,width:PAGE_WIDTH,height:PAGE_HEIGHT,visuals:slots});
  for(const action of actions.filter(item=>item.pageId===page.id))action.layoutSlots=action.resultingVisualIds.map(id=>slots.find(slot=>slot.visualId===id)!);
  const outside=slots.filter(slot=>!withinPage(slot));if(outside.length){const affected=actions.find(action=>action.pageId===page.id&&action.resultingVisualIds.some(id=>outside.some(slot=>slot.visualId===id)));findings.push({code:'LAYOUT_CAPACITY_EXCEEDED',pageId:page.id,pageName:page.name,visualId:affected?.originalVisualId??outside[0].visualId,requestedResultingVisuals:affected?.resultingVisualIds.length??1,pageBounds:{width:PAGE_WIDTH,height:PAGE_HEIGHT},attemptedLayoutSlots:outside,reason:`Page '${page.name}' cannot fit the normalized layout within ${PAGE_WIDTH} x ${PAGE_HEIGHT}; ${outside.map(slot=>`'${slot.visualId}' reaches right ${slot.right} and bottom ${slot.bottom}`).join(', ')}.`,recommendedAction:'Reduce page scope or split visuals across pages before generation.'})}
 }
 return{status:findings.length?'FAILED':actions.length?'NORMALIZED':'UNCHANGED',originalReportDesign,normalizedReportDesign,originalVisualCount:countVisuals(originalReportDesign),normalizedVisualCount:countVisuals(normalizedReportDesign),normalizationActions:actions,normalizationFindings:findings,pageLayouts};
}
