import readXlsxFile from 'read-excel-file/browser';

export type BasicType='text'|'integer'|'decimal'|'date'|'boolean';
export type ParsedColumn={name:string;sourceName:string;type:BasicType;nullable:boolean;sampleValues:string[]};
export type ParsedTable={name:string;sourceName:string;columns:ParsedColumn[];rows:string[][];rowCount:number};
export type ParsedRelationship={fromTable:string;fromColumn:string;toTable:string;toColumn:string;cardinality:'many-to-one';active:true};
export type DataStructure={kind:'REQUEST_DATA_STRUCTURE';fileName:string;format:'CSV'|'XLSX';tables:ParsedTable[];relationships:ParsedRelationship[];parsedAt:string};

const identifier=(value:string,fallback:string)=>{const cleaned=value.trim().replace(/[^A-Za-z0-9_]/g,'_').replace(/_+/g,'_').replace(/^([^A-Za-z_])/,'_$1');return cleaned||fallback};
function inferType(values:string[]):BasicType{const filled=values.filter(Boolean);if(!filled.length)return'text';if(filled.every(v=>/^-?\d+$/.test(v)))return'integer';if(filled.every(v=>/^-?(?:\d+\.\d+|\d+)$/.test(v)))return'decimal';if(filled.every(v=>/^(true|false)$/i.test(v)))return'boolean';if(filled.every(v=>!Number.isNaN(Date.parse(v))&&/[\/-]/.test(v)))return'date';return'text'}
function tableFromRows(sourceName:string,input:unknown[][]):ParsedTable{
  if(!input.length)throw new Error(`EMPTY_TABLE: ${sourceName}`);const header=input[0].map((v,i)=>String(v??'').trim()||`Column${i+1}`);if(new Set(header).size!==header.length)throw new Error(`DUPLICATE_COLUMNS: ${sourceName}`);
  const rows=input.slice(1,5001).filter(row=>row.some(v=>v!==null&&v!==undefined&&String(v)!=='')).map(row=>header.map((_,i)=>{const value=row[i];return value instanceof Date?value.toISOString().slice(0,10):String(value??'')}));
  const columns=header.map((sourceName,i)=>{const values=rows.map(r=>r[i]);return{name:identifier(sourceName,`Column${i+1}`),sourceName,type:inferType(values),nullable:values.some(v=>!v),sampleValues:[...new Set(values.filter(Boolean))].slice(0,3)}});
  return{name:identifier(sourceName,'Table'),sourceName,columns,rows,rowCount:rows.length};
}
export function parseCsv(text:string):unknown[][]{const rows:unknown[][]=[];let row:string[]=[],value='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(char===','&&!quoted){row.push(value);value=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(value);if(row.some(cell=>cell.length))rows.push(row);row=[];value=''}else value+=char}row.push(value);if(row.some(cell=>cell.length))rows.push(row);return rows}
function relationships(tables:ParsedTable[]):ParsedRelationship[]{const result:ParsedRelationship[]=[];for(const one of tables)for(const many of tables){if(one===many)continue;for(const pk of one.columns.filter(c=>/id$/i.test(c.name))){const fk=many.columns.find(c=>c.name.toLowerCase()===pk.name.toLowerCase());if(!fk)continue;const unique=new Set(one.rows.map(r=>r[one.columns.indexOf(pk)]).filter(Boolean));const values=many.rows.map(r=>r[many.columns.indexOf(fk)]).filter(Boolean);if(unique.size===one.rowCount&&values.length>unique.size&&values.every(v=>unique.has(v))&&!result.some(r=>r.fromTable===many.name&&r.fromColumn===fk.name))result.push({fromTable:many.name,fromColumn:fk.name,toTable:one.name,toColumn:pk.name,cardinality:'many-to-one',active:true})}}return result}
export function summarizeDataStructure(value:DataStructure){return{kind:value.kind,fileName:value.fileName,format:value.format,tables:value.tables.map(table=>({name:table.name,sourceName:table.sourceName,rowCount:table.rowCount,columns:table.columns.map(({name,sourceName,type,nullable,sampleValues})=>({name,sourceName,type,nullable,sampleValues}))})),relationships:value.relationships}}
export async function parseDataFile(file:File):Promise<DataStructure>{if(file.size>5_000_000)throw new Error('FILE_TOO_LARGE');const lower=file.name.toLowerCase();let tables:ParsedTable[],format:'CSV'|'XLSX';if(lower.endsWith('.csv')){format='CSV';tables=[tableFromRows(file.name.replace(/\.csv$/i,''),parseCsv(await file.text()))]}else if(lower.endsWith('.xlsx')){format='XLSX';const sheets=await readXlsxFile(file);tables=sheets.filter(sheet=>sheet.data.length).map(sheet=>tableFromRows(sheet.sheet,sheet.data))}else throw new Error('SUPPORTED_FILES: .csv or .xlsx');if(!tables.length)throw new Error('NO_TABLES_DETECTED');return{kind:'REQUEST_DATA_STRUCTURE',fileName:file.name,format,tables,relationships:relationships(tables),parsedAt:new Date().toISOString()}}
export function tableCsv(table:ParsedTable){const escape=(v:string)=>/[",\r\n]/.test(v)?`"${v.replaceAll('"','""')}"`:v;return[table.columns.map(c=>escape(c.name)).join(','),...table.rows.map(row=>row.map(escape).join(','))].join('\n')+'\n'}
